/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/building/en113/en113.glb -t -k -E -R -f 
*/

"use client";

import * as THREE from "three";
import React, { useCallback, useEffect, useRef, useState } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useEN101Store, useEN113Store } from "@/stores/use-building-store";
import { IFloorDetails } from "@/types/model";
import { getData } from "@/actions/actions";
import Link from "next/link";
import { Button } from "@/components/shadcn-ui/button";
import { ExternalLink } from "lucide-react";
import {
  Table,
  TableBody,
  TableCell,
  TableRow,
} from "@/components/shadcn-ui/table";
import { Select } from "@react-three/postprocessing";
import { getFloorActiveStatus } from "@/lib/utils";

type GLTFResult = GLTF & {
  nodes: {
    B14_025_x_145: THREE.Mesh
    B14_025_x_145_1: THREE.Mesh
    B14_025_x_145_2: THREE.Mesh
    B14_025_x_145_3: THREE.Mesh
    B14_025_x_145_4: THREE.Mesh
    B14_025_x_145_5: THREE.Mesh
    B14_025_x_145_6: THREE.Mesh
    B14_025_x_145_7: THREE.Mesh
    B14_025_x_145_8: THREE.Mesh
    B14_025_x_145_9: THREE.Mesh
    B14_025_x_145_10: THREE.Mesh
    B14_025_x_145_11: THREE.Mesh
    B14_025_x_145_12: THREE.Mesh
    B14_025_x_145_13: THREE.Mesh
    B0_010_x_0022: THREE.Mesh
    B0_010_x_0022_1: THREE.Mesh
    B0_010_x_0022_2: THREE.Mesh
    B0_010_x_0022_3: THREE.Mesh
    B0_010_x_0022_4: THREE.Mesh
    B0_010_x_0022_5: THREE.Mesh
    B0_010_x_0022_6: THREE.Mesh
    B0_010_x_0022_7: THREE.Mesh
    B0_010_x_0022_8: THREE.Mesh
    B0_010_x_0022_9: THREE.Mesh
    B0_010_x_0022_10: THREE.Mesh
    B0_010_x_0022_11: THREE.Mesh
    B0_010_x_0022_12: THREE.Mesh
    B0_010_x_0022_13: THREE.Mesh
    B0_010_x_0022_14: THREE.Mesh
    B0_010_x_0022_15: THREE.Mesh
    B0_010_x_0044: THREE.Mesh
    B0_010_x_0044_1: THREE.Mesh
    B0_010_x_0044_2: THREE.Mesh
    B0_010_x_0044_3: THREE.Mesh
    B0_010_x_0044_4: THREE.Mesh
    B0_010_x_0044_5: THREE.Mesh
    B0_010_x_0044_6: THREE.Mesh
    B0_010_x_0044_7: THREE.Mesh
    B0_010_x_0044_8: THREE.Mesh
    B0_010_x_0044_9: THREE.Mesh
    B0_010_x_0044_10: THREE.Mesh
    B0_010_x_0044_11: THREE.Mesh
    B0_010_x_0044_12: THREE.Mesh
    B0_010_x_0044_13: THREE.Mesh
    B0_010_x_0044_14: THREE.Mesh
    B0_010_x_0044_15: THREE.Mesh
    B3_025_x_0028: THREE.Mesh
    B3_025_x_0028_1: THREE.Mesh
    B3_025_x_0028_2: THREE.Mesh
    B3_025_x_0028_3: THREE.Mesh
    B3_025_x_0028_4: THREE.Mesh
    B3_025_x_0028_5: THREE.Mesh
    B3_025_x_0028_6: THREE.Mesh
    B3_025_x_0028_7: THREE.Mesh
    B3_025_x_0028_8: THREE.Mesh
    B3_025_x_0028_9: THREE.Mesh
    B3_025_x_0028_10: THREE.Mesh
    B3_025_x_0028_11: THREE.Mesh
    B3_025_x_0028_12: THREE.Mesh
    B3_025_x_0028_13: THREE.Mesh
    หลังคา003: THREE.Mesh
    หลังคา003_1: THREE.Mesh
    หลังคา003_2: THREE.Mesh
    หลังคา003_3: THREE.Mesh
    หลังคา003_4: THREE.Mesh
    หลังคา003_5: THREE.Mesh
  }
  materials: {
    ['Concrete, Cast-in-Place gray.001']: THREE.MeshStandardMaterial
    ปูนฉาบ: THREE.MeshStandardMaterial
    ['Default Wall.001']: THREE.MeshStandardMaterial
    กระเบื้องห้องน้ำ: THREE.MeshStandardMaterial
    หินอ่อน: THREE.MeshStandardMaterial
    ['กระเบื้องพื้น 2']: THREE.MeshStandardMaterial
    กระเบื้อง: THREE.MeshStandardMaterial
    ไม้สัก: THREE.MeshStandardMaterial
    ['Glass.001']: THREE.MeshStandardMaterial
    ไม้อัด: THREE.MeshStandardMaterial
    เหล็ก: THREE.MeshStandardMaterial
    ไม้อัดสัก: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.001']: THREE.MeshStandardMaterial
    ['Concrete, Cast In Situ.001']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.002']: THREE.MeshStandardMaterial
    ['กระเบื้องพื้น 2.001']: THREE.MeshStandardMaterial
    ['กระเบื้อง.001']: THREE.MeshStandardMaterial
    ['หินอ่อน.001']: THREE.MeshStandardMaterial
    ['ปูนฉาบ.001']: THREE.MeshStandardMaterial
    ['Default Wall.002']: THREE.MeshStandardMaterial
    ['กระเบื้องห้องน้ำ.001']: THREE.MeshStandardMaterial
    ['Glass.002']: THREE.MeshStandardMaterial
    ['เหล็ก.001']: THREE.MeshStandardMaterial
    ['ไม้อัด.001']: THREE.MeshStandardMaterial
    ['ไม้สัก.001']: THREE.MeshStandardMaterial
    อะลูมิเนียม: THREE.MeshStandardMaterial
    เหล็กไลท์เกต: THREE.MeshStandardMaterial
    ['ไม้อัดสัก.001']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.002']: THREE.MeshStandardMaterial
    ['Concrete, Cast In Situ.002']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.003']: THREE.MeshStandardMaterial
    ['ปูนฉาบ.002']: THREE.MeshStandardMaterial
    ['Default Wall.003']: THREE.MeshStandardMaterial
    ['กระเบื้องห้องน้ำ.002']: THREE.MeshStandardMaterial
    ['กระเบื้องพื้น 2.002']: THREE.MeshStandardMaterial
    ['กระเบื้อง.002']: THREE.MeshStandardMaterial
    ['หินอ่อน.002']: THREE.MeshStandardMaterial
    ['ไม้สัก.002']: THREE.MeshStandardMaterial
    ['ไม้อัดสัก.002']: THREE.MeshStandardMaterial
    ['Glass.003']: THREE.MeshStandardMaterial
    ['อะลูมิเนียม.001']: THREE.MeshStandardMaterial
    ['เหล็ก.002']: THREE.MeshStandardMaterial
    ['ไม้อัด.002']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.003']: THREE.MeshStandardMaterial
    ['Steel, 45-345']: THREE.MeshStandardMaterial
    ['Concrete, Cast In Situ.003']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.004']: THREE.MeshStandardMaterial
    ['กระเบื้องห้องน้ำ.003']: THREE.MeshStandardMaterial
    ['ปูนฉาบ.003']: THREE.MeshStandardMaterial
    ['Default Wall.004']: THREE.MeshStandardMaterial
    ['Glass.004']: THREE.MeshStandardMaterial
    ['เหล็ก.003']: THREE.MeshStandardMaterial
    ['ไม้อัดสัก.003']: THREE.MeshStandardMaterial
    ['ไม้สัก.003']: THREE.MeshStandardMaterial
    ['ไม้อัด.003']: THREE.MeshStandardMaterial
    ['อะลูมิเนียม.002']: THREE.MeshStandardMaterial
    ['กระเบื้อง.003']: THREE.MeshStandardMaterial
    ['กระเบื้องพื้น 2.003']: THREE.MeshStandardMaterial
    ['หินอ่อน.003']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.004']: THREE.MeshStandardMaterial
    ['Default Roof']: THREE.MeshStandardMaterial
    ['ปูนฉาบ.004']: THREE.MeshStandardMaterial
    ['Default Wall.005']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.005']: THREE.MeshStandardMaterial
    ['Steel, 45-345.001']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.005']: THREE.MeshStandardMaterial
  }
}

export const en113Floors = ["EN11301", "EN11302", "EN11303", "EN11304"] as const;

export type EN113Floor = (typeof en113Floors)[number];

type Props = JSX.IntrinsicElements["group"] & {
  isManage: boolean;
};

export default function EN113Building(props: Props) {
  const { nodes, materials } = useGLTF('/models/building/en113/en113.glb') as GLTFResult
  const groupRef = useRef<any>();
  const [hover, setHover] = useState<EN113Floor | null>(null);
  const { select, setSelect } = useEN113Store((state) => state);
  const [floorDetail, setFloorDetail] = useState<IFloorDetails | null>(null);

  const handleObjectHover = useCallback((object: EN113Floor | null) => {
    setHover(object);
  }, []);

  const handleObjectSelect = useCallback(
    (object: EN113Floor) => {
      setSelect(object);
    },
    [setSelect]
  );

  useEffect(() => {
    const fetchFloorDetail = async () => {
      const data = await getData(
        `buildingFloorDetail/${select?.toUpperCase()}`
      );
      setFloorDetail(data);
    };

    fetchFloorDetail();
  }, [select]);

  const renderModalDetail = (floorCode: string) => {
    const isFloorActive = getFloorActiveStatus(
      select?.substring(0, 5),
      select as string
    );
    if (select === floorCode && !props.isManage) {
      return (
        <Html distanceFactor={70}>
          <div className="pt-[10px] transform translate-x-[80%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ชั้น ${floorCode.substring(5, 7)} - ${floorCode}`}
              </label>
              {isFloorActive && (
                <Link href={`/floor/${floorCode.toUpperCase()}`} target="_blank">
                  <Button variant={"ghost"} size={"icon"}>
                    <ExternalLink className="size-5" />
                  </Button>
                </Link>
              )}
            </div>
            {renderFloorDetail()}
          </div>
        </Html>
      );
    }
  };

  const renderFloorDetail = () => {
    return (
      <Table className="border rounded-md">
        <TableBody>
          <TableRow>
            <TableCell className="p-2">Building Code</TableCell>
            <TableCell className="p-2">
              {floorDetail?.buildingCode || select?.substring(0, 5)}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Floor</TableCell>
            <TableCell className="p-2">
              {floorDetail?.floorNumber || select?.substring(5, 7)}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Meter Energy</TableCell>
            <TableCell className="p-2">
              {floorDetail?.floorMeter ? floorDetail?.floorMeter : "-"}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Meter Power</TableCell>
            <TableCell className="p-2">
              {floorDetail?.floorPower ? floorDetail?.floorPower : "-"}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Average PM 2.5</TableCell>
            <TableCell className="p-2">
              {floorDetail?.averagefloorPM25 ? floorDetail?.averagefloorPM25 : "-"}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Average Temperature</TableCell>
            <TableCell className="p-2">
              {floorDetail?.averagefloorTemp ? floorDetail?.averagefloorTemp : "-"}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Average Humidity</TableCell>
            <TableCell className="p-2">
              {floorDetail?.averagefloorHumidity ? floorDetail?.averagefloorHumidity : "-"}
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    );
  };

  return (
    <group 
      onPointerOver={(e) => {
        e.stopPropagation();
        handleObjectHover(e.object.parent?.name as any);
      }} 
      onPointerOut={(e) => {
        e.stopPropagation();
        handleObjectHover(null)
      }}
      onClick={(e) => {
        e.stopPropagation();
        handleObjectSelect(e.object.parent?.name as any)
      }}
      ref={groupRef} 
      {...props} 
      dispose={null}
      position={[0, 0.5, 0]}
    >
      <Select name="EN11302" enabled={hover === "EN11302" || select === "EN11302"} position={[-2.194, 6.7, -2.497]} rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
        {renderModalDetail("EN11302")}
        <mesh name="B14_025_x_145" geometry={nodes.B14_025_x_145.geometry} material={materials['Concrete, Cast-in-Place gray.001']} />
        <mesh name="B14_025_x_145_1" geometry={nodes.B14_025_x_145_1.geometry} material={materials.ปูนฉาบ} />
        <mesh name="B14_025_x_145_2" geometry={nodes.B14_025_x_145_2.geometry} material={materials['Default Wall.001']} />
        <mesh name="B14_025_x_145_3" geometry={nodes.B14_025_x_145_3.geometry} material={materials.กระเบื้องห้องน้ำ} />
        <mesh name="B14_025_x_145_4" geometry={nodes.B14_025_x_145_4.geometry} material={materials.หินอ่อน} />
        <mesh name="B14_025_x_145_5" geometry={nodes.B14_025_x_145_5.geometry} material={materials['กระเบื้องพื้น 2']} />
        <mesh name="B14_025_x_145_6" geometry={nodes.B14_025_x_145_6.geometry} material={materials.กระเบื้อง} />
        <mesh name="B14_025_x_145_7" geometry={nodes.B14_025_x_145_7.geometry} material={materials.ไม้สัก} />
        <mesh name="B14_025_x_145_8" geometry={nodes.B14_025_x_145_8.geometry} material={materials['Glass.001']} />
        <mesh name="B14_025_x_145_9" geometry={nodes.B14_025_x_145_9.geometry} material={materials.ไม้อัด} />
        <mesh name="B14_025_x_145_10" geometry={nodes.B14_025_x_145_10.geometry} material={materials.เหล็ก} />
        <mesh name="B14_025_x_145_11" geometry={nodes.B14_025_x_145_11.geometry} material={materials.ไม้อัดสัก} />
        <mesh name="B14_025_x_145_12" geometry={nodes.B14_025_x_145_12.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.001']} />
        <mesh name="B14_025_x_145_13" geometry={nodes.B14_025_x_145_13.geometry} material={materials['Concrete, Cast In Situ.001']} />
      </Select>
      <Select name="EN11301" enabled={hover === "EN11301" || select === "EN11301"} position={[3.792, 1.873, 2.974]} rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
      {renderModalDetail("EN11301")}
        <mesh name="B0_010_x_0022" geometry={nodes.B0_010_x_0022.geometry} material={materials['Concrete, Cast-in-Place gray.002']} />
        <mesh name="B0_010_x_0022_1" geometry={nodes.B0_010_x_0022_1.geometry} material={materials['กระเบื้องพื้น 2.001']} />
        <mesh name="B0_010_x_0022_2" geometry={nodes.B0_010_x_0022_2.geometry} material={materials['กระเบื้อง.001']} />
        <mesh name="B0_010_x_0022_3" geometry={nodes.B0_010_x_0022_3.geometry} material={materials['หินอ่อน.001']} />
        <mesh name="B0_010_x_0022_4" geometry={nodes.B0_010_x_0022_4.geometry} material={materials['ปูนฉาบ.001']} />
        <mesh name="B0_010_x_0022_5" geometry={nodes.B0_010_x_0022_5.geometry} material={materials['Default Wall.002']} />
        <mesh name="B0_010_x_0022_6" geometry={nodes.B0_010_x_0022_6.geometry} material={materials['กระเบื้องห้องน้ำ.001']} />
        <mesh name="B0_010_x_0022_7" geometry={nodes.B0_010_x_0022_7.geometry} material={materials['Glass.002']} />
        <mesh name="B0_010_x_0022_8" geometry={nodes.B0_010_x_0022_8.geometry} material={materials['เหล็ก.001']} />
        <mesh name="B0_010_x_0022_9" geometry={nodes.B0_010_x_0022_9.geometry} material={materials['ไม้อัด.001']} />
        <mesh name="B0_010_x_0022_10" geometry={nodes.B0_010_x_0022_10.geometry} material={materials['ไม้สัก.001']} />
        <mesh name="B0_010_x_0022_11" geometry={nodes.B0_010_x_0022_11.geometry} material={materials.อะลูมิเนียม} />
        <mesh name="B0_010_x_0022_12" geometry={nodes.B0_010_x_0022_12.geometry} material={materials.เหล็กไลท์เกต} />
        <mesh name="B0_010_x_0022_13" geometry={nodes.B0_010_x_0022_13.geometry} material={materials['ไม้อัดสัก.001']} />
        <mesh name="B0_010_x_0022_14" geometry={nodes.B0_010_x_0022_14.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.002']} />
        <mesh name="B0_010_x_0022_15" geometry={nodes.B0_010_x_0022_15.geometry} material={materials['Concrete, Cast In Situ.002']} />
      </Select>
      <Select name="EN11303" enabled={hover === "EN11303" || select === "EN11303"} position={[-0.785, 9.941, -1.517]} rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
      {renderModalDetail("EN11303")}
        <mesh name="B0_010_x_0044" geometry={nodes.B0_010_x_0044.geometry} material={materials['Concrete, Cast-in-Place gray.003']} />
        <mesh name="B0_010_x_0044_1" geometry={nodes.B0_010_x_0044_1.geometry} material={materials['ปูนฉาบ.002']} />
        <mesh name="B0_010_x_0044_2" geometry={nodes.B0_010_x_0044_2.geometry} material={materials['Default Wall.003']} />
        <mesh name="B0_010_x_0044_3" geometry={nodes.B0_010_x_0044_3.geometry} material={materials['กระเบื้องห้องน้ำ.002']} />
        <mesh name="B0_010_x_0044_4" geometry={nodes.B0_010_x_0044_4.geometry} material={materials['กระเบื้องพื้น 2.002']} />
        <mesh name="B0_010_x_0044_5" geometry={nodes.B0_010_x_0044_5.geometry} material={materials['กระเบื้อง.002']} />
        <mesh name="B0_010_x_0044_6" geometry={nodes.B0_010_x_0044_6.geometry} material={materials['หินอ่อน.002']} />
        <mesh name="B0_010_x_0044_7" geometry={nodes.B0_010_x_0044_7.geometry} material={materials['ไม้สัก.002']} />
        <mesh name="B0_010_x_0044_8" geometry={nodes.B0_010_x_0044_8.geometry} material={materials['ไม้อัดสัก.002']} />
        <mesh name="B0_010_x_0044_9" geometry={nodes.B0_010_x_0044_9.geometry} material={materials['Glass.003']} />
        <mesh name="B0_010_x_0044_10" geometry={nodes.B0_010_x_0044_10.geometry} material={materials['อะลูมิเนียม.001']} />
        <mesh name="B0_010_x_0044_11" geometry={nodes.B0_010_x_0044_11.geometry} material={materials['เหล็ก.002']} />
        <mesh name="B0_010_x_0044_12" geometry={nodes.B0_010_x_0044_12.geometry} material={materials['ไม้อัด.002']} />
        <mesh name="B0_010_x_0044_13" geometry={nodes.B0_010_x_0044_13.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.003']} />
        <mesh name="B0_010_x_0044_14" geometry={nodes.B0_010_x_0044_14.geometry} material={materials['Steel, 45-345']} />
        <mesh name="B0_010_x_0044_15" geometry={nodes.B0_010_x_0044_15.geometry} material={materials['Concrete, Cast In Situ.003']} />
      </Select>
      <Select name="EN11304" enabled={hover === "EN11304" || select === "EN11304"} position={[-2.188, 13.435, -2.776]} rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
      {renderModalDetail("EN11304")}
        <mesh name="B3_025_x_0028" geometry={nodes.B3_025_x_0028.geometry} material={materials['Concrete, Cast-in-Place gray.004']} />
        <mesh name="B3_025_x_0028_1" geometry={nodes.B3_025_x_0028_1.geometry} material={materials['กระเบื้องห้องน้ำ.003']} />
        <mesh name="B3_025_x_0028_2" geometry={nodes.B3_025_x_0028_2.geometry} material={materials['ปูนฉาบ.003']} />
        <mesh name="B3_025_x_0028_3" geometry={nodes.B3_025_x_0028_3.geometry} material={materials['Default Wall.004']} />
        <mesh name="B3_025_x_0028_4" geometry={nodes.B3_025_x_0028_4.geometry} material={materials['Glass.004']} />
        <mesh name="B3_025_x_0028_5" geometry={nodes.B3_025_x_0028_5.geometry} material={materials['เหล็ก.003']} />
        <mesh name="B3_025_x_0028_6" geometry={nodes.B3_025_x_0028_6.geometry} material={materials['ไม้อัดสัก.003']} />
        <mesh name="B3_025_x_0028_7" geometry={nodes.B3_025_x_0028_7.geometry} material={materials['ไม้สัก.003']} />
        <mesh name="B3_025_x_0028_8" geometry={nodes.B3_025_x_0028_8.geometry} material={materials['ไม้อัด.003']} />
        <mesh name="B3_025_x_0028_9" geometry={nodes.B3_025_x_0028_9.geometry} material={materials['อะลูมิเนียม.002']} />
        <mesh name="B3_025_x_0028_10" geometry={nodes.B3_025_x_0028_10.geometry} material={materials['กระเบื้อง.003']} />
        <mesh name="B3_025_x_0028_11" geometry={nodes.B3_025_x_0028_11.geometry} material={materials['กระเบื้องพื้น 2.003']} />
        <mesh name="B3_025_x_0028_12" geometry={nodes.B3_025_x_0028_12.geometry} material={materials['หินอ่อน.003']} />
        <mesh name="B3_025_x_0028_13" geometry={nodes.B3_025_x_0028_13.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.004']} />
      </Select>
      <group name="EN113RF" position={[2.411, 13.717, 0.358]} rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
        <mesh name="หลังคา003" geometry={nodes.หลังคา003.geometry} material={materials['Default Roof']} />
        <mesh name="หลังคา003_1" geometry={nodes.หลังคา003_1.geometry} material={materials['ปูนฉาบ.004']} />
        <mesh name="หลังคา003_2" geometry={nodes.หลังคา003_2.geometry} material={materials['Default Wall.005']} />
        <mesh name="หลังคา003_3" geometry={nodes.หลังคา003_3.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.005']} />
        <mesh name="หลังคา003_4" geometry={nodes.หลังคา003_4.geometry} material={materials['Steel, 45-345.001']} />
        <mesh name="หลังคา003_5" geometry={nodes.หลังคา003_5.geometry} material={materials['Concrete, Cast-in-Place gray.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/building/en113/en113.glb')
