/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/building/en106/en106.glb -t -k -E -R -f 
*/
"use client"

import * as THREE from 'three'
import React, { useCallback, useEffect, useState } from 'react'
import { Html, useGLTF } from "@react-three/drei";
import { Select } from "@react-three/postprocessing";
import { GLTF } from 'three-stdlib'
import { useEN106Store } from '@/stores/use-building-store'
import { IFloorDetails } from '@/types/model';
import { Table, TableBody, TableCell, TableRow } from '@/components/shadcn-ui/table';
import { getData } from '@/actions/actions';
import Link from 'next/link';
import { Button } from '@/components/shadcn-ui/button';
import { ExternalLink } from 'lucide-react';

type GLTFResult = GLTF & {
  nodes: {
    ระดับขอบบนหลังคา: THREE.Mesh
    ระดับขอบบนหลังคา_1: THREE.Mesh
    ระดับขอบบนหลังคา_2: THREE.Mesh
    ระดับขอบบนหลังคา_3: THREE.Mesh
    ระดับขอบบนหลังคา_4: THREE.Mesh
    ระดับขอบบนหลังคา_5: THREE.Mesh
    ระดับขอบบนหลังคา_6: THREE.Mesh
    ระดับขอบบนหลังคา_7: THREE.Mesh
    ระดับขอบบนหลังคา_8: THREE.Mesh
    ระดับขอบบนหลังคา_9: THREE.Mesh
    ระดับขอบบนหลังคา_10: THREE.Mesh
    ระดับขอบบนหลังคา_11: THREE.Mesh
    ระดับขอบบนหลังคา_12: THREE.Mesh
    ระดับขอบบนหลังคา_13: THREE.Mesh
    ระดับขอบบนหลังคา_14: THREE.Mesh
    ระดับขอบบนหลังคา_15: THREE.Mesh
    ระดับขอบบนหลังคา_16: THREE.Mesh
    ระดับขอบบนหลังคา_17: THREE.Mesh
    B1_150_x_600_mm017: THREE.Mesh
    B1_150_x_600_mm017_1: THREE.Mesh
    B1_150_x_600_mm017_2: THREE.Mesh
    B1_150_x_600_mm017_3: THREE.Mesh
    B1_150_x_600_mm017_4: THREE.Mesh
    B1_150_x_600_mm017_5: THREE.Mesh
    B1_150_x_600_mm017_6: THREE.Mesh
    B1_150_x_600_mm017_7: THREE.Mesh
    B1_150_x_600_mm017_8: THREE.Mesh
    B1_150_x_600_mm017_9: THREE.Mesh
    B1_150_x_600_mm017_10: THREE.Mesh
    ระดับขอบบนหลังคา002: THREE.Mesh
    ระดับขอบบนหลังคา002_1: THREE.Mesh
    ระดับขอบบนหลังคา002_2: THREE.Mesh
    ระดับขอบบนหลังคา002_3: THREE.Mesh
  }
  materials: {
    ['Stainless steel Matt']: THREE.MeshStandardMaterial
    Default: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete(1)']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray']: THREE.MeshStandardMaterial
    ['สีขาว 247']: THREE.MeshStandardMaterial
    ['สีเทา 175']: THREE.MeshStandardMaterial
    ['Default Wall']: THREE.MeshStandardMaterial
    Aluminium: THREE.MeshStandardMaterial
    Aluminum: THREE.MeshStandardMaterial
    ['Glass(1)']: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    ['สีน้ำตาล-แดงส้ม']: THREE.MeshStandardMaterial
    ['wood mahog']: THREE.MeshStandardMaterial
    ['Metal-steel']: THREE.MeshStandardMaterial
    เหล็ก: THREE.MeshStandardMaterial
    ['สีเขียว-เทา']: THREE.MeshStandardMaterial
    สีน้ำเงิน: THREE.MeshStandardMaterial
    ['สีขาว 247.001']: THREE.MeshStandardMaterial
    ['Default Wall.001']: THREE.MeshStandardMaterial
    ['สีเทา 175.001']: THREE.MeshStandardMaterial
    ['Wood-dark']: THREE.MeshStandardMaterial
    ['Glass.001']: THREE.MeshStandardMaterial
    ['Aluminium.001']: THREE.MeshStandardMaterial
    ['Stainless steel Matt.001']: THREE.MeshStandardMaterial
    ['Default.001']: THREE.MeshStandardMaterial
    ['Aluminum.001']: THREE.MeshStandardMaterial
    ['Glass(1).001']: THREE.MeshStandardMaterial
    ['Wood.001']: THREE.MeshStandardMaterial
    ['สีขาว 247.002']: THREE.MeshStandardMaterial
    ['Wisawa-ruamjai-Crimson-red']: THREE.MeshStandardMaterial
    ['Metal Stud Layer']: THREE.MeshStandardMaterial
    ['Wood.002']: THREE.MeshStandardMaterial
  }
}

export const en106Floors = [
  "EN10601",
  "EN10602",
] as const;

export type EN106Floor = typeof en106Floors[number];

type Props = JSX.IntrinsicElements["group"] & {
  isManage: boolean;
};

export default function EN106Building(props: Props) {
  const { nodes, materials } = useGLTF('/models/building/en106/en106.glb') as GLTFResult
  const [hover, setHover] = useState<EN106Floor | null>(null);
  const { select, setSelect } = useEN106Store(state => (state));
  const [floorDetail, setFloorDetail] = useState<IFloorDetails | null>(null);

  const handleObjectHover = useCallback((object: EN106Floor | null) => {
    setHover(object);
  }, []);

  const handleObjectSelect = useCallback((object: EN106Floor) => {
    setSelect(object);
  }, [setSelect]);

  useEffect(() => {
    const fetchFloorDetail = async () => {
      const data = await getData(`buildingFloorDetail/${select?.toUpperCase()}`);
      setFloorDetail(data);
    }

    fetchFloorDetail();
  }, [select]);

  const renderModalDetail = (floorCode: string) => {
    if (select === floorCode && !props.isManage) {
      return (
        <Html distanceFactor={60}>
          <div className="pt-[10px] transform translate-x-[80%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ชั้น ${floorCode.substring(5, 7)} - ${floorCode}`}
              </label>
              <Link href={`/floor/${floorCode.toUpperCase()}`} target="_blank">
                <Button variant={"ghost"} size={"icon"}>
                  <ExternalLink className="size-5" />
                </Button>
              </Link>
            </div>
            {renderFloorDetail()}
          </div>
        </Html>
      )
    }
  }

  const renderFloorDetail = () => {
    if (floorDetail) {
      return (
        <Table className="border rounded-md">
          <TableBody>
            <TableRow>
              <TableCell className="p-2">Building Code</TableCell>
              <TableCell className="p-2">
                {floorDetail?.buildingCode || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Floor</TableCell>
              <TableCell className="p-2">
                {floorDetail?.floorNumber || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Meter Energy</TableCell>
              <TableCell className="p-2">
                {floorDetail?.floorMeter || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Meter Power</TableCell>
              <TableCell className="p-2">
                {floorDetail?.floorPower || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Average PM 2.5</TableCell>
              <TableCell className="p-2">
                {floorDetail?.averagefloorPM25 || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Average Temperature</TableCell>
              <TableCell className="p-2">
                {floorDetail?.averagefloorTemp || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Average Humidity</TableCell>
              <TableCell className="p-2">
                {floorDetail?.averagefloorHumidity || "-"}
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      )
    }
  }
  
  return (
    <group {...props} dispose={null} rotation={[0, 180, 0]}>
      <Select 
        name="EN10601" 
        enabled={hover === "EN10601" || select === "EN10601"}
        onPointerOver={() => {
          handleObjectHover("EN10601");
        }}
        onPointerOut={() => {
          handleObjectHover(null);
        }}
        onClick={() => {
          handleObjectSelect("EN10601");
        }} 
        position={[3.275, 1.401, -0.823]} 
        rotation={[-Math.PI / 2, 0, 0]} 
        scale={0.3}
      >
        {renderModalDetail("EN10601")}
        <mesh name="ระดับขอบบนหลังคา" geometry={nodes.ระดับขอบบนหลังคา.geometry} material={materials['Stainless steel Matt']} />
        <mesh name="ระดับขอบบนหลังคา_1" geometry={nodes.ระดับขอบบนหลังคา_1.geometry} material={materials.Default} />
        <mesh name="ระดับขอบบนหลังคา_2" geometry={nodes.ระดับขอบบนหลังคา_2.geometry} material={materials.Glass} />
        <mesh name="ระดับขอบบนหลังคา_3" geometry={nodes.ระดับขอบบนหลังคา_3.geometry} material={materials['Concrete - Cast-in-Place Concrete(1)']} />
        <mesh name="ระดับขอบบนหลังคา_4" geometry={nodes.ระดับขอบบนหลังคา_4.geometry} material={materials['Concrete, Cast-in-Place gray']} />
        <mesh name="ระดับขอบบนหลังคา_5" geometry={nodes.ระดับขอบบนหลังคา_5.geometry} material={materials['สีขาว 247']} />
        <mesh name="ระดับขอบบนหลังคา_6" geometry={nodes.ระดับขอบบนหลังคา_6.geometry} material={materials['สีเทา 175']} />
        <mesh name="ระดับขอบบนหลังคา_7" geometry={nodes.ระดับขอบบนหลังคา_7.geometry} material={materials['Default Wall']} />
        <mesh name="ระดับขอบบนหลังคา_8" geometry={nodes.ระดับขอบบนหลังคา_8.geometry} material={materials.Aluminium} />
        <mesh name="ระดับขอบบนหลังคา_9" geometry={nodes.ระดับขอบบนหลังคา_9.geometry} material={materials.Aluminum} />
        <mesh name="ระดับขอบบนหลังคา_10" geometry={nodes.ระดับขอบบนหลังคา_10.geometry} material={materials['Glass(1)']} />
        <mesh name="ระดับขอบบนหลังคา_11" geometry={nodes.ระดับขอบบนหลังคา_11.geometry} material={materials.Wood} />
        <mesh name="ระดับขอบบนหลังคา_12" geometry={nodes.ระดับขอบบนหลังคา_12.geometry} material={materials['สีน้ำตาล-แดงส้ม']} />
        <mesh name="ระดับขอบบนหลังคา_13" geometry={nodes.ระดับขอบบนหลังคา_13.geometry} material={materials['wood mahog']} />
        <mesh name="ระดับขอบบนหลังคา_14" geometry={nodes.ระดับขอบบนหลังคา_14.geometry} material={materials['Metal-steel']} />
        <mesh name="ระดับขอบบนหลังคา_15" geometry={nodes.ระดับขอบบนหลังคา_15.geometry} material={materials.เหล็ก} />
        <mesh name="ระดับขอบบนหลังคา_16" geometry={nodes.ระดับขอบบนหลังคา_16.geometry} material={materials['สีเขียว-เทา']} />
        <mesh name="ระดับขอบบนหลังคา_17" geometry={nodes.ระดับขอบบนหลังคา_17.geometry} material={materials.สีน้ำเงิน} />
      </Select>
      <Select 
        name="EN10602" 
        enabled={hover === "EN10602" || select === "EN10602"}
        onPointerOver={() => {
          handleObjectHover("EN10602");
        }}
        onPointerOut={() => {
          handleObjectHover(null);
        }}
        onClick={() => {
          handleObjectSelect("EN10602");
        }}  
        position={[-2.896, 5.454, -3.076]} 
        rotation={[-Math.PI / 2, 0, 0]} 
        scale={0.3}
      >
        {renderModalDetail("EN10602")}
        <mesh name="B1_150_x_600_mm017" geometry={nodes.B1_150_x_600_mm017.geometry} material={materials['สีขาว 247.001']} />
        <mesh name="B1_150_x_600_mm017_1" geometry={nodes.B1_150_x_600_mm017_1.geometry} material={materials['Default Wall.001']} />
        <mesh name="B1_150_x_600_mm017_2" geometry={nodes.B1_150_x_600_mm017_2.geometry} material={materials['สีเทา 175.001']} />
        <mesh name="B1_150_x_600_mm017_3" geometry={nodes.B1_150_x_600_mm017_3.geometry} material={materials['Wood-dark']} />
        <mesh name="B1_150_x_600_mm017_4" geometry={nodes.B1_150_x_600_mm017_4.geometry} material={materials['Glass.001']} />
        <mesh name="B1_150_x_600_mm017_5" geometry={nodes.B1_150_x_600_mm017_5.geometry} material={materials['Aluminium.001']} />
        <mesh name="B1_150_x_600_mm017_6" geometry={nodes.B1_150_x_600_mm017_6.geometry} material={materials['Stainless steel Matt.001']} />
        <mesh name="B1_150_x_600_mm017_7" geometry={nodes.B1_150_x_600_mm017_7.geometry} material={materials['Default.001']} />
        <mesh name="B1_150_x_600_mm017_8" geometry={nodes.B1_150_x_600_mm017_8.geometry} material={materials['Aluminum.001']} />
        <mesh name="B1_150_x_600_mm017_9" geometry={nodes.B1_150_x_600_mm017_9.geometry} material={materials['Glass(1).001']} />
        <mesh name="B1_150_x_600_mm017_10" geometry={nodes.B1_150_x_600_mm017_10.geometry} material={materials['Wood.001']} />
      </Select>
      <group name="EN106RF" position={[-0.016, 7.641, -1.033]} rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
        <mesh name="ระดับขอบบนหลังคา002" geometry={nodes.ระดับขอบบนหลังคา002.geometry} material={materials['สีขาว 247.002']} />
        <mesh name="ระดับขอบบนหลังคา002_1" geometry={nodes.ระดับขอบบนหลังคา002_1.geometry} material={materials['Wisawa-ruamjai-Crimson-red']} />
        <mesh name="ระดับขอบบนหลังคา002_2" geometry={nodes.ระดับขอบบนหลังคา002_2.geometry} material={materials['Metal Stud Layer']} />
        <mesh name="ระดับขอบบนหลังคา002_3" geometry={nodes.ระดับขอบบนหลังคา002_3.geometry} material={materials['Wood.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/building/en106/en106.glb')
