/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/building/en124/en124-building.glb -t -k -E -R -f 
*/
"use client";

import * as THREE from "three";
import React, { useCallback, useEffect, useState } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useEN124Store } from "@/stores/use-building-store";
import { IFloorDetails } from "@/types/model";
import { getData } from "@/actions/actions";
import Link from "next/link";
import { Button } from "@/components/shadcn-ui/button";
import { ExternalLink } from "lucide-react";
import {
  Table,
  TableBody,
  TableCell,
  TableRow,
} from "@/components/shadcn-ui/table";
import { Select } from "@react-three/postprocessing";
import { configs } from "@/lib/configs";
import { getFloorActiveStatus } from "@/lib/utils";

type GLTFResult = GLTF & {
  nodes: {
    EB12401: THREE.Mesh;
    EB12401_1: THREE.Mesh;
    EB12401_2: THREE.Mesh;
    EB12401_3: THREE.Mesh;
    EB12401_4: THREE.Mesh;
    EB12401_5: THREE.Mesh;
    EB12401_6: THREE.Mesh;
    EB12401_7: THREE.Mesh;
    EB12401_8: THREE.Mesh;
    EB12401_9: THREE.Mesh;
    EB12401_10: THREE.Mesh;
    EB12401_11: THREE.Mesh;
    EB12401_12: THREE.Mesh;
    EB12401_13: THREE.Mesh;
    EB12401_14: THREE.Mesh;
    EB12401_15: THREE.Mesh;
    EB12401_16: THREE.Mesh;
    EB12401_17: THREE.Mesh;
    EB12401_18: THREE.Mesh;
    EB12401_19: THREE.Mesh;
    EB12401_20: THREE.Mesh;
    EB12401_21: THREE.Mesh;
    EB12401_22: THREE.Mesh;
    EB12401_23: THREE.Mesh;
    EB12401_24: THREE.Mesh;
    EB12401_25: THREE.Mesh;
    EB12401_26: THREE.Mesh;
    EB12401_27: THREE.Mesh;
    EB12401_28: THREE.Mesh;
    EB12401_29: THREE.Mesh;
    EB12401_30: THREE.Mesh;
    EB12401_31: THREE.Mesh;
    EN124M1_1: THREE.Mesh;
    EN124M1_2: THREE.Mesh;
    EN124M1_3: THREE.Mesh;
    EN124M1_4: THREE.Mesh;
    EN124M1_5: THREE.Mesh;
    EN124M1_6: THREE.Mesh;
    EN124M1_7: THREE.Mesh;
    EN124M1_8: THREE.Mesh;
    EN124M1_9: THREE.Mesh;
    EN124M1_10: THREE.Mesh;
    EN124M1_11: THREE.Mesh;
    EN124M1_12: THREE.Mesh;
    EN124M1_13: THREE.Mesh;
    EN124M1_14: THREE.Mesh;
    EN124M1_15: THREE.Mesh;
    EN124M1_16: THREE.Mesh;
    EN124M1_17: THREE.Mesh;
    EN124M1_18: THREE.Mesh;
    EN124M1_19: THREE.Mesh;
    EN124M1_20: THREE.Mesh;
    EN124M1_21: THREE.Mesh;
    EN124M1_22: THREE.Mesh;
    EN124M1_23: THREE.Mesh;
    EN124M1_24: THREE.Mesh;
    EN12402_1: THREE.Mesh;
    EN12402_2: THREE.Mesh;
    EN12402_3: THREE.Mesh;
    EN12402_4: THREE.Mesh;
    EN12402_5: THREE.Mesh;
    EN12402_6: THREE.Mesh;
    EN12402_7: THREE.Mesh;
    EN12402_8: THREE.Mesh;
    EN12402_9: THREE.Mesh;
    EN12402_10: THREE.Mesh;
    EN12402_11: THREE.Mesh;
    EN12402_12: THREE.Mesh;
    EN12402_13: THREE.Mesh;
    EN12402_14: THREE.Mesh;
    EN12402_15: THREE.Mesh;
    EN12402_16: THREE.Mesh;
    EN12402_17: THREE.Mesh;
    EN12402_18: THREE.Mesh;
    EN12402_19: THREE.Mesh;
    EN12402_20: THREE.Mesh;
    EN12402_21: THREE.Mesh;
    EN12402_22: THREE.Mesh;
    EN12402_23: THREE.Mesh;
    EN12402_24: THREE.Mesh;
    EN12402_25: THREE.Mesh;
    EN12402_26: THREE.Mesh;
    EN12402_27: THREE.Mesh;
    EN12402_28: THREE.Mesh;
    EN12402_29: THREE.Mesh;
    EN12403_1: THREE.Mesh;
    EN12403_2: THREE.Mesh;
    EN12403_3: THREE.Mesh;
    EN12403_4: THREE.Mesh;
    EN12403_5: THREE.Mesh;
    EN12403_6: THREE.Mesh;
    EN12403_7: THREE.Mesh;
    EN12403_8: THREE.Mesh;
    EN12403_9: THREE.Mesh;
    EN12403_10: THREE.Mesh;
    EN12403_11: THREE.Mesh;
    EN12403_12: THREE.Mesh;
    EN12403_13: THREE.Mesh;
    EN12403_14: THREE.Mesh;
    EN12403_15: THREE.Mesh;
    EN12403_16: THREE.Mesh;
    EN12403_17: THREE.Mesh;
    EN12403_18: THREE.Mesh;
    EN12403_19: THREE.Mesh;
    EN12403_20: THREE.Mesh;
    EN12403_21: THREE.Mesh;
    EN12403_22: THREE.Mesh;
    EN12403_23: THREE.Mesh;
    EN12403_24: THREE.Mesh;
    EN12403_25: THREE.Mesh;
    EN12403_26: THREE.Mesh;
    EN12403_27: THREE.Mesh;
    EN12403_28: THREE.Mesh;
    EN12404_1: THREE.Mesh;
    EN12404_2: THREE.Mesh;
    EN12404_3: THREE.Mesh;
    EN12404_4: THREE.Mesh;
    EN12404_5: THREE.Mesh;
    EN12404_6: THREE.Mesh;
    EN12404_7: THREE.Mesh;
    EN12404_8: THREE.Mesh;
    EN12404_9: THREE.Mesh;
    EN12404_10: THREE.Mesh;
    EN12404_11: THREE.Mesh;
    EN12404_12: THREE.Mesh;
    EN12404_13: THREE.Mesh;
    EN12404_14: THREE.Mesh;
    EN12404_15: THREE.Mesh;
    EN12404_16: THREE.Mesh;
    EN12404_17: THREE.Mesh;
    EN12404_18: THREE.Mesh;
    EN12404_19: THREE.Mesh;
    EN12404_20: THREE.Mesh;
    EN12404_21: THREE.Mesh;
    EN12404_22: THREE.Mesh;
    EN12404_23: THREE.Mesh;
    EN12404_24: THREE.Mesh;
    EN12404_25: THREE.Mesh;
    EN12404_26: THREE.Mesh;
    EN12404_27: THREE.Mesh;
    EN12405_1: THREE.Mesh;
    EN12405_2: THREE.Mesh;
    EN12405_3: THREE.Mesh;
    EN12405_4: THREE.Mesh;
    EN12405_5: THREE.Mesh;
    EN12405_6: THREE.Mesh;
    EN12405_7: THREE.Mesh;
    EN12405_8: THREE.Mesh;
    EN12405_9: THREE.Mesh;
    EN12405_10: THREE.Mesh;
    EN12405_11: THREE.Mesh;
    EN12405_12: THREE.Mesh;
    EN12405_13: THREE.Mesh;
    EN12405_14: THREE.Mesh;
    EN12405_15: THREE.Mesh;
    EN12405_16: THREE.Mesh;
    EN12405_17: THREE.Mesh;
    EN12405_18: THREE.Mesh;
    EN12405_19: THREE.Mesh;
    EN12405_20: THREE.Mesh;
    EN12405_21: THREE.Mesh;
    EN12405_22: THREE.Mesh;
    EN12405_23: THREE.Mesh;
    EN12405_24: THREE.Mesh;
    EN12405_25: THREE.Mesh;
    EN12405_26: THREE.Mesh;
    EN12405_27: THREE.Mesh;
    EN12406_1: THREE.Mesh;
    EN12406_2: THREE.Mesh;
    EN12406_3: THREE.Mesh;
    EN12406_4: THREE.Mesh;
    EN12406_5: THREE.Mesh;
    EN12406_6: THREE.Mesh;
    EN12406_7: THREE.Mesh;
    EN12406_8: THREE.Mesh;
    EN12406_9: THREE.Mesh;
    EN12406_10: THREE.Mesh;
    EN12406_11: THREE.Mesh;
    EN12406_12: THREE.Mesh;
    EN12406_13: THREE.Mesh;
    EN12406_14: THREE.Mesh;
    EN12406_15: THREE.Mesh;
    EN12406_16: THREE.Mesh;
    EN12406_17: THREE.Mesh;
    EN12406_18: THREE.Mesh;
    EN12406_19: THREE.Mesh;
    EN12406_20: THREE.Mesh;
    EN12406_21: THREE.Mesh;
    EN12406_22: THREE.Mesh;
    EN12406_23: THREE.Mesh;
    EN12406_24: THREE.Mesh;
    EN12406_25: THREE.Mesh;
    EN12407_1: THREE.Mesh;
    EN12407_2: THREE.Mesh;
    EN12407_3: THREE.Mesh;
    EN12407_4: THREE.Mesh;
    EN12407_5: THREE.Mesh;
    EN12407_6: THREE.Mesh;
    EN12407_7: THREE.Mesh;
    EN12407_8: THREE.Mesh;
    EN12407_9: THREE.Mesh;
    EN12407_10: THREE.Mesh;
    EN12407_11: THREE.Mesh;
    EN12407_12: THREE.Mesh;
    EN12407_13: THREE.Mesh;
    EN12407_14: THREE.Mesh;
    EN12407_15: THREE.Mesh;
    EN12407_16: THREE.Mesh;
    EN12407_17: THREE.Mesh;
    EN12407_18: THREE.Mesh;
    EN12407_19: THREE.Mesh;
    EN12407_20: THREE.Mesh;
    EN12407_21: THREE.Mesh;
    EN12407_22: THREE.Mesh;
    EN12407_23: THREE.Mesh;
    EN12407_24: THREE.Mesh;
    EN12407_25: THREE.Mesh;
    EN12407_26: THREE.Mesh;
    EN12408_1: THREE.Mesh;
    EN12408_2: THREE.Mesh;
    EN12408_3: THREE.Mesh;
    EN12408_4: THREE.Mesh;
    EN12408_5: THREE.Mesh;
    EN12408_6: THREE.Mesh;
    EN12408_7: THREE.Mesh;
    EN12408_8: THREE.Mesh;
    EN12408_9: THREE.Mesh;
    EN12408_10: THREE.Mesh;
    EN12408_11: THREE.Mesh;
    EN12408_12: THREE.Mesh;
    EN12408_13: THREE.Mesh;
    EN12408_14: THREE.Mesh;
    EN12408_15: THREE.Mesh;
    EN12408_16: THREE.Mesh;
    EN12408_17: THREE.Mesh;
    EN12408_18: THREE.Mesh;
    EN12408_19: THREE.Mesh;
    EN12408_20: THREE.Mesh;
    EN12408_21: THREE.Mesh;
    EN12408_22: THREE.Mesh;
    EN12408_23: THREE.Mesh;
    EN12408_24: THREE.Mesh;
    EN12408_25: THREE.Mesh;
    EN12408_26: THREE.Mesh;
    EN124RF_1: THREE.Mesh;
    EN124RF_2: THREE.Mesh;
    EN124RF_3: THREE.Mesh;
    EN124RF_4: THREE.Mesh;
    EN124RF_5: THREE.Mesh;
    EN124RF_6: THREE.Mesh;
    EN124RF_7: THREE.Mesh;
    EN124RF_8: THREE.Mesh;
    EN124RF_9: THREE.Mesh;
    EN124RF_10: THREE.Mesh;
    EN124RF_11: THREE.Mesh;
    EN124RF_12: THREE.Mesh;
    EN124RF_13: THREE.Mesh;
    EN124RF_14: THREE.Mesh;
    EN124RF_15: THREE.Mesh;
    EN124RF_16: THREE.Mesh;
    EN124RF_17: THREE.Mesh;
    EN124RF_18: THREE.Mesh;
    EN124RF_19: THREE.Mesh;
    EN124RF_20: THREE.Mesh;
    EN124RF_21: THREE.Mesh;
    Plane: THREE.Mesh;
  };
  materials: {
    ["ผิวคอนกรีต ขัดมัน.010"]: THREE.MeshStandardMaterial;
    ["ผนังทดลอง.010"]: THREE.MeshStandardMaterial;
    ["Default Wall.010"]: THREE.MeshStandardMaterial;
    ["ผนังก่ออิฐ ทาสี.010"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 2 หุน.010"]: THREE.MeshStandardMaterial;
    ["กระเบื้องห้องน้ำ.009"]: THREE.MeshStandardMaterial;
    ["พื้นคอนกรีตขัดมัน ด้.007"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 1 1/2 หุน.009"]: THREE.MeshStandardMaterial;
    ["กรอบประตูหน้าต่าง ตา.008"]: THREE.MeshStandardMaterial;
    ["เหล็ก บานม้วนทาสีน้ำ"]: THREE.MeshStandardMaterial;
    ["Aluminum.010"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.027"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.028"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยางทาสี.009"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2" x 4" ทาสี.009']: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.029"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยาง ทาสี.009"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2"x4" ทาสี.009']: THREE.MeshStandardMaterial;
    ["Render Material 128-128-128.009"]: THREE.MeshStandardMaterial;
    ["Plastic - Nystrom - Black.001"]: THREE.MeshStandardMaterial;
    ["Metal - Nystrom - Stainless Steel.001"]: THREE.MeshStandardMaterial;
    ["Polyester - Nystrom - Glossy Red Coated.001"]: THREE.MeshStandardMaterial;
    ["AB_Fire Glass.009"]: THREE.MeshStandardMaterial;
    ["AB_RAL9011_Graphite black.009"]: THREE.MeshStandardMaterial;
    ["AB_RAL3000_Red.009"]: THREE.MeshStandardMaterial;
    ["AB_Steel.009"]: THREE.MeshStandardMaterial;
    ["AB_Hose White.009"]: THREE.MeshStandardMaterial;
    ["Default.007"]: THREE.MeshStandardMaterial;
    ["Assa Abloy - Silver Anodized.001"]: THREE.MeshStandardMaterial;
    ["Assa Abloy Plastic.001"]: THREE.MeshStandardMaterial;
    ["Silver Anodized.001"]: THREE.MeshStandardMaterial;
    ["Glass.009"]: THREE.MeshStandardMaterial;
    ["ผิวคอนกรีต ขัดมัน.011"]: THREE.MeshStandardMaterial;
    ["ผนังก่ออิฐ ทาสี.011"]: THREE.MeshStandardMaterial;
    ["ผนังทดลอง.011"]: THREE.MeshStandardMaterial;
    ["Default Wall.011"]: THREE.MeshStandardMaterial;
    ["กระเบื้องห้องน้ำ.010"]: THREE.MeshStandardMaterial;
    ["Glass.010"]: THREE.MeshStandardMaterial;
    ["Laminate, Ivory, Matte.005"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 1 1/2 หุน.010"]: THREE.MeshStandardMaterial;
    ["กรอบประตูหน้าต่าง ตา.009"]: THREE.MeshStandardMaterial;
    ["Default.008"]: THREE.MeshStandardMaterial;
    ["Aluminum.011"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 2 หุน.011"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.030"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.031"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยางทาสี.010"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2" x 4" ทาสี.010']: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.032"]: THREE.MeshStandardMaterial;
    ["อลูมิเนียมสีเงินขนา.007"]: THREE.MeshStandardMaterial;
    ["Default New Material.009"]: THREE.MeshStandardMaterial;
    ["Metal - Steel 43-275.001"]: THREE.MeshStandardMaterial;
    ["หลังคาโครงเหล็ก.002"]: THREE.MeshStandardMaterial;
    ["Metal - Steel - 345 MPa.002"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยาง ทาสี.010"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2"x4" ทาสี.010']: THREE.MeshStandardMaterial;
    ["ผิวคอนกรีต ขัดมัน.012"]: THREE.MeshStandardMaterial;
    ["ผนังก่ออิฐ ทาสี.012"]: THREE.MeshStandardMaterial;
    ["ผนังทดลอง.012"]: THREE.MeshStandardMaterial;
    ["Default Wall.012"]: THREE.MeshStandardMaterial;
    ["กระเบื้องห้องน้ำ.011"]: THREE.MeshStandardMaterial;
    ["พื้นคอนกรีตขัดมัน ด้.008"]: THREE.MeshStandardMaterial;
    ["Glass.011"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 1 1/2 หุน.011"]: THREE.MeshStandardMaterial;
    ["กรอบประตูหน้าต่าง ตา.010"]: THREE.MeshStandardMaterial;
    ["Laminate, Ivory, Matte.006"]: THREE.MeshStandardMaterial;
    ["Aluminum.012"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 2 หุน.012"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.033"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.034"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยางทาสี.011"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2" x 4" ทาสี.011']: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.035"]: THREE.MeshStandardMaterial;
    ["อลูมิเนียมสีเงินขนา.008"]: THREE.MeshStandardMaterial;
    ["Default New Material.010"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยาง ทาสี.011"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2"x4" ทาสี.011']: THREE.MeshStandardMaterial;
    ["Render Material 128-128-128.010"]: THREE.MeshStandardMaterial;
    ["Colour RGB-255 255 255.002"]: THREE.MeshStandardMaterial;
    ["Colour RGB-250 000 000.002"]: THREE.MeshStandardMaterial;
    ["AB_Fire Glass.010"]: THREE.MeshStandardMaterial;
    ["AB_RAL9011_Graphite black.010"]: THREE.MeshStandardMaterial;
    ["AB_RAL3000_Red.010"]: THREE.MeshStandardMaterial;
    ["AB_Steel.010"]: THREE.MeshStandardMaterial;
    ["AB_Hose White.010"]: THREE.MeshStandardMaterial;
    ["ผิวคอนกรีต ขัดมัน.013"]: THREE.MeshStandardMaterial;
    ["ผนังก่ออิฐ ทาสี.013"]: THREE.MeshStandardMaterial;
    ["ผนังทดลอง.013"]: THREE.MeshStandardMaterial;
    ["Default Wall.013"]: THREE.MeshStandardMaterial;
    ["กระเบื้องห้องน้ำ.012"]: THREE.MeshStandardMaterial;
    ["พื้นคอนกรีตขัดมัน ด้.009"]: THREE.MeshStandardMaterial;
    ["Glass.012"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 1 1/2 หุน.012"]: THREE.MeshStandardMaterial;
    ["กรอบประตูหน้าต่าง ตา.011"]: THREE.MeshStandardMaterial;
    ["Laminate, Ivory, Matte.007"]: THREE.MeshStandardMaterial;
    ["Aluminum.013"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 2 หุน.013"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.036"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.037"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยางทาสี.012"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2" x 4" ทาสี.012']: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.038"]: THREE.MeshStandardMaterial;
    ["อลูมิเนียมสีเงินขนา.009"]: THREE.MeshStandardMaterial;
    ["Default New Material.011"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยาง ทาสี.012"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2"x4" ทาสี.012']: THREE.MeshStandardMaterial;
    ["AB_Fire Glass.011"]: THREE.MeshStandardMaterial;
    ["AB_RAL9011_Graphite black.011"]: THREE.MeshStandardMaterial;
    ["AB_RAL3000_Red.011"]: THREE.MeshStandardMaterial;
    ["AB_Steel.011"]: THREE.MeshStandardMaterial;
    ["AB_Hose White.011"]: THREE.MeshStandardMaterial;
    ["Colour RGB-255 255 255.003"]: THREE.MeshStandardMaterial;
    ["Colour RGB-250 000 000.003"]: THREE.MeshStandardMaterial;
    ["ผิวคอนกรีต ขัดมัน.014"]: THREE.MeshStandardMaterial;
    ["ผนังก่ออิฐ ทาสี.014"]: THREE.MeshStandardMaterial;
    ["ผนังทดลอง.014"]: THREE.MeshStandardMaterial;
    ["Default Wall.014"]: THREE.MeshStandardMaterial;
    ["พื้นคอนกรีตขัดมัน ด้.010"]: THREE.MeshStandardMaterial;
    ["กระเบื้องห้องน้ำ.013"]: THREE.MeshStandardMaterial;
    ["Glass.013"]: THREE.MeshStandardMaterial;
    ["Laminate, Ivory, Matte.008"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 1 1/2 หุน.013"]: THREE.MeshStandardMaterial;
    ["กรอบประตูหน้าต่าง ตา.012"]: THREE.MeshStandardMaterial;
    ["Aluminum.014"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 2 หุน.014"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.039"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.040"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยางทาสี.013"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2" x 4" ทาสี.013']: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.041"]: THREE.MeshStandardMaterial;
    ["อลูมิเนียมสีเงินขนา.010"]: THREE.MeshStandardMaterial;
    ["Default.009"]: THREE.MeshStandardMaterial;
    ["Default New Material.012"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยาง ทาสี.013"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2"x4" ทาสี.013']: THREE.MeshStandardMaterial;
    ["AB_Fire Glass.012"]: THREE.MeshStandardMaterial;
    ["AB_RAL9011_Graphite black.012"]: THREE.MeshStandardMaterial;
    ["AB_RAL3000_Red.012"]: THREE.MeshStandardMaterial;
    ["AB_Steel.012"]: THREE.MeshStandardMaterial;
    ["AB_Hose White.012"]: THREE.MeshStandardMaterial;
    ["ผิวคอนกรีต ขัดมัน.015"]: THREE.MeshStandardMaterial;
    ["ผนังก่ออิฐ ทาสี.015"]: THREE.MeshStandardMaterial;
    ["ผนังทดลอง.015"]: THREE.MeshStandardMaterial;
    ["Default Wall.015"]: THREE.MeshStandardMaterial;
    ["กระเบื้องห้องน้ำ.014"]: THREE.MeshStandardMaterial;
    ["พื้นคอนกรีตขัดมัน ด้.011"]: THREE.MeshStandardMaterial;
    ["Glass.014"]: THREE.MeshStandardMaterial;
    ["Laminate, Ivory, Matte.009"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 1 1/2 หุน.014"]: THREE.MeshStandardMaterial;
    ["กรอบประตูหน้าต่าง ตา.013"]: THREE.MeshStandardMaterial;
    ["Aluminum.015"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 2 หุน.015"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.042"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.043"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยางทาสี.014"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2" x 4" ทาสี.014']: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.044"]: THREE.MeshStandardMaterial;
    ["Default.010"]: THREE.MeshStandardMaterial;
    ["อลูมิเนียมสีเงินขนา.011"]: THREE.MeshStandardMaterial;
    ["Default New Material.013"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยาง ทาสี.014"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2"x4" ทาสี.014']: THREE.MeshStandardMaterial;
    ["AB_Fire Glass.013"]: THREE.MeshStandardMaterial;
    ["AB_RAL9011_Graphite black.013"]: THREE.MeshStandardMaterial;
    ["AB_RAL3000_Red.013"]: THREE.MeshStandardMaterial;
    ["AB_Steel.013"]: THREE.MeshStandardMaterial;
    ["AB_Hose White.013"]: THREE.MeshStandardMaterial;
    ["ผิวคอนกรีต ขัดมัน.016"]: THREE.MeshStandardMaterial;
    ["ผนังก่ออิฐ ทาสี.016"]: THREE.MeshStandardMaterial;
    ["ผนังทดลอง.016"]: THREE.MeshStandardMaterial;
    ["Default Wall.016"]: THREE.MeshStandardMaterial;
    ["กระเบื้องห้องน้ำ.015"]: THREE.MeshStandardMaterial;
    ["พื้นคอนกรีตขัดมัน ด้.012"]: THREE.MeshStandardMaterial;
    ["Glass.015"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 1 1/2 หุน.015"]: THREE.MeshStandardMaterial;
    ["กรอบประตูหน้าต่าง ตา.014"]: THREE.MeshStandardMaterial;
    ["Aluminum.016"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 2 หุน.016"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.045"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.046"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยางทาสี.015"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2" x 4" ทาสี.015']: THREE.MeshStandardMaterial;
    ["อลูมิเนียมสีเงินขนา.012"]: THREE.MeshStandardMaterial;
    ["Default.011"]: THREE.MeshStandardMaterial;
    ["Default New Material.014"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยาง ทาสี.015"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2"x4" ทาสี.015']: THREE.MeshStandardMaterial;
    ["AB_Fire Glass.014"]: THREE.MeshStandardMaterial;
    ["AB_RAL9011_Graphite black.014"]: THREE.MeshStandardMaterial;
    ["AB_RAL3000_Red.014"]: THREE.MeshStandardMaterial;
    ["AB_Steel.014"]: THREE.MeshStandardMaterial;
    ["AB_Hose White.014"]: THREE.MeshStandardMaterial;
    ["ผิวคอนกรีต ขัดมัน.017"]: THREE.MeshStandardMaterial;
    ["ผนังก่ออิฐ ทาสี.017"]: THREE.MeshStandardMaterial;
    ["ผนังทดลอง.017"]: THREE.MeshStandardMaterial;
    ["Default Wall.017"]: THREE.MeshStandardMaterial;
    ["กระเบื้องห้องน้ำ.016"]: THREE.MeshStandardMaterial;
    ["พื้นคอนกรีตขัดมัน ด้.013"]: THREE.MeshStandardMaterial;
    ["Glass.016"]: THREE.MeshStandardMaterial;
    ["กรอบประตูหน้าต่าง ตา.015"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 1 1/2 หุน.016"]: THREE.MeshStandardMaterial;
    ["Aluminum.017"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 2 หุน.017"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.047"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.048"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยางทาสี.016"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2" x 4" ทาสี.016']: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.049"]: THREE.MeshStandardMaterial;
    ["อลูมิเนียมสีเงินขนา.013"]: THREE.MeshStandardMaterial;
    ["Default.012"]: THREE.MeshStandardMaterial;
    ["Default New Material.015"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยาง ทาสี.016"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2"x4" ทาสี.016']: THREE.MeshStandardMaterial;
    ["AB_Fire Glass.015"]: THREE.MeshStandardMaterial;
    ["AB_RAL9011_Graphite black.015"]: THREE.MeshStandardMaterial;
    ["AB_RAL3000_Red.015"]: THREE.MeshStandardMaterial;
    ["AB_Steel.015"]: THREE.MeshStandardMaterial;
    ["AB_Hose White.015"]: THREE.MeshStandardMaterial;
    ["ผิวคอนกรีต ขัดมัน.018"]: THREE.MeshStandardMaterial;
    ["ผนังก่ออิฐ ทาสี.018"]: THREE.MeshStandardMaterial;
    ["ผนังทดลอง.018"]: THREE.MeshStandardMaterial;
    ["Default Wall.018"]: THREE.MeshStandardMaterial;
    ["กระเบื้องห้องน้ำ.017"]: THREE.MeshStandardMaterial;
    ["พื้นคอนกรีตขัดมัน ด้.014"]: THREE.MeshStandardMaterial;
    ["Glass.017"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 1 1/2 หุน.017"]: THREE.MeshStandardMaterial;
    ["กรอบประตูหน้าต่าง ตา.016"]: THREE.MeshStandardMaterial;
    ["Aluminum.018"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 2 หุน.018"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.050"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.051"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยางทาสี.017"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2" x 4" ทาสี.017']: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.052"]: THREE.MeshStandardMaterial;
    ["อลูมิเนียมสีเงินขนา.014"]: THREE.MeshStandardMaterial;
    ["Default.013"]: THREE.MeshStandardMaterial;
    ["Default New Material.016"]: THREE.MeshStandardMaterial;
    ["ไม้อัดยาง ทาสี.017"]: THREE.MeshStandardMaterial;
    ['ไม้เนื้อแข็ง 2"x4" ทาสี.017']: THREE.MeshStandardMaterial;
    ["AB_Fire Glass.016"]: THREE.MeshStandardMaterial;
    ["AB_RAL9011_Graphite black.016"]: THREE.MeshStandardMaterial;
    ["AB_RAL3000_Red.016"]: THREE.MeshStandardMaterial;
    ["AB_Steel.016"]: THREE.MeshStandardMaterial;
    ["AB_Hose White.016"]: THREE.MeshStandardMaterial;
    ["ผนังก่ออิฐ ทาสี.019"]: THREE.MeshStandardMaterial;
    ["ผนังทดลอง.019"]: THREE.MeshStandardMaterial;
    ["Default Wall.019"]: THREE.MeshStandardMaterial;
    ["ผิวคอนกรีต ขัดมัน.019"]: THREE.MeshStandardMaterial;
    ["ผิวคอนกรีตหลังคา.001"]: THREE.MeshStandardMaterial;
    ["Default New Material.017"]: THREE.MeshStandardMaterial;
    ["หลังคาโครงเหล็ก.003"]: THREE.MeshStandardMaterial;
    ["Metal - Steel - 345 MPa.003"]: THREE.MeshStandardMaterial;
    ["กระจกใสหนา 2 หุน.019"]: THREE.MeshStandardMaterial;
    ["AB_Fire Glass.017"]: THREE.MeshStandardMaterial;
    ["AB_RAL9011_Graphite black.017"]: THREE.MeshStandardMaterial;
    ["AB_RAL3000_Red.017"]: THREE.MeshStandardMaterial;
    ["AB_Steel.017"]: THREE.MeshStandardMaterial;
    ["AB_Hose White.017"]: THREE.MeshStandardMaterial;
    ["Metal Stud Layer.001"]: THREE.MeshStandardMaterial;
    ["Gypsum Wall Board.001"]: THREE.MeshStandardMaterial;
    ["Aluminum.019"]: THREE.MeshStandardMaterial;
    ["White.001"]: THREE.MeshStandardMaterial;
    ["Plastic.001"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.053"]: THREE.MeshStandardMaterial;
    ["เหล็ก ตามมาตราฐาน Decoradoo.054"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

export const en124Floors = [
  "EN12401",
  "EN124M1",
  "EN12402",
  "EN12403",
  "EN12404",
  "EN12405",
  "EN12406",
  "EN12407",
  "EN12408",
] as const;

export type EN124Floor = (typeof en124Floors)[number];

type Props = JSX.IntrinsicElements["group"] & {
  isManage: boolean;
};

export default function EN124Building(props: Props) {
  const { nodes, materials } = useGLTF(
    "/models/building/en124/en124-building.glb"
  ) as GLTFResult;
  const [hover, setHover] = useState<EN124Floor | null>(null);
  const { select, setSelect } = useEN124Store((state) => state);
  const [floorDetail, setFloorDetail] = useState<IFloorDetails | null>(null);

  const handleObjectHover = useCallback((object: EN124Floor | any) => {
    setHover(object);
  }, []);

  const handleObjectSelect = useCallback(
    (object: EN124Floor | any) => {
      setSelect(object);
    },
    [setSelect]
  );

  useEffect(() => {
    const fetchFloorDetail = async () => {
      const data = await getData(
        `buildingFloorDetail/${select?.toUpperCase()}`, true
      );
      setFloorDetail(data);
    };

    fetchFloorDetail();
  }, [select]);

  const renderModalDetail = (floorCode: string) => {
    const isFloorActive = getFloorActiveStatus(
      select?.substring(0, 5),
      select as string
    );
    if (select === floorCode && !props.isManage) {
      return (
        <Html distanceFactor={80}>
          <div className="pt-[10px] transform translate-x-[80%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ชั้น ${floorCode.substring(5, 7)} - ${floorCode}`}
              </label>
              {isFloorActive && (
                <Link
                  href={`/floor/${floorCode.toUpperCase()}`}
                  target="_blank"
                >
                  <Button variant={"ghost"} size={"icon"}>
                    <ExternalLink className="size-5" />
                  </Button>
                </Link>
              )}
            </div>
            <Table className="border rounded-md">
              <TableBody>
                <TableRow>
                  <TableCell className="p-2">Building Code</TableCell>
                  <TableCell className="p-2">
                    {floorDetail?.buildingCode || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Floor</TableCell>
                  <TableCell className="p-2">
                    {floorDetail?.floorNumber || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Energy</TableCell>
                  <TableCell className="p-2">
                    {floorDetail?.floorMeter || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Power</TableCell>
                  <TableCell className="p-2">
                    {floorDetail?.floorPower || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average PM 2.5</TableCell>
                  <TableCell className="p-2">
                    {floorDetail?.averagefloorPM25 || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Temperature</TableCell>
                  <TableCell className="p-2">
                    {floorDetail?.averagefloorTemp || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Humidity</TableCell>
                  <TableCell className="p-2">
                    {floorDetail?.averagefloorHumidity || "-"}
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </Html>
      );
    }
  };

  return (
    <group {...props} dispose={null}>
      <Select
        name="EN12401"
        enabled={hover === "EN12401" || select === "EN12401"}
        onPointerOver={(e) => {
          e.stopPropagation();
          handleObjectHover("EN12401");
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          handleObjectHover(null);
        }}
        onClick={(e) => {
          e.stopPropagation();
          handleObjectSelect("EN12401");
        }}
        position={[-5.724, 0.349, 0.378]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.2}
      >
        {renderModalDetail("EN12401")}
        <mesh
          name="EB12401"
          geometry={nodes.EB12401.geometry}
          material={materials["ผิวคอนกรีต ขัดมัน.010"]}
        />
        <mesh
          name="EB12401_1"
          geometry={nodes.EB12401_1.geometry}
          material={materials["ผนังทดลอง.010"]}
        />
        <mesh
          name="EB12401_2"
          geometry={nodes.EB12401_2.geometry}
          material={materials["Default Wall.010"]}
        />
        <mesh
          name="EB12401_3"
          geometry={nodes.EB12401_3.geometry}
          material={materials["ผนังก่ออิฐ ทาสี.010"]}
        />
        <mesh
          name="EB12401_4"
          geometry={nodes.EB12401_4.geometry}
          material={materials["กระจกใสหนา 2 หุน.010"]}
        />
        <mesh
          name="EB12401_5"
          geometry={nodes.EB12401_5.geometry}
          material={materials["กระเบื้องห้องน้ำ.009"]}
        />
        <mesh
          name="EB12401_6"
          geometry={nodes.EB12401_6.geometry}
          material={materials["พื้นคอนกรีตขัดมัน ด้.007"]}
        />
        <mesh
          name="EB12401_7"
          geometry={nodes.EB12401_7.geometry}
          material={materials["กระจกใสหนา 1 1/2 หุน.009"]}
        />
        <mesh
          name="EB12401_8"
          geometry={nodes.EB12401_8.geometry}
          material={materials["กรอบประตูหน้าต่าง ตา.008"]}
        />
        <mesh
          name="EB12401_9"
          geometry={nodes.EB12401_9.geometry}
          material={materials["เหล็ก บานม้วนทาสีน้ำ"]}
        />
        <mesh
          name="EB12401_10"
          geometry={nodes.EB12401_10.geometry}
          material={materials["Aluminum.010"]}
        />
        <mesh
          name="EB12401_11"
          geometry={nodes.EB12401_11.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.027"]}
        />
        <mesh
          name="EB12401_12"
          geometry={nodes.EB12401_12.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.028"]}
        />
        <mesh
          name="EB12401_13"
          geometry={nodes.EB12401_13.geometry}
          material={materials["ไม้อัดยางทาสี.009"]}
        />
        <mesh
          name="EB12401_14"
          geometry={nodes.EB12401_14.geometry}
          material={materials['ไม้เนื้อแข็ง 2" x 4" ทาสี.009']}
        />
        <mesh
          name="EB12401_15"
          geometry={nodes.EB12401_15.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.029"]}
        />
        <mesh
          name="EB12401_16"
          geometry={nodes.EB12401_16.geometry}
          material={materials["ไม้อัดยาง ทาสี.009"]}
        />
        <mesh
          name="EB12401_17"
          geometry={nodes.EB12401_17.geometry}
          material={materials['ไม้เนื้อแข็ง 2"x4" ทาสี.009']}
        />
        <mesh
          name="EB12401_18"
          geometry={nodes.EB12401_18.geometry}
          material={materials["Render Material 128-128-128.009"]}
        />
        <mesh
          name="EB12401_19"
          geometry={nodes.EB12401_19.geometry}
          material={materials["Plastic - Nystrom - Black.001"]}
        />
        <mesh
          name="EB12401_20"
          geometry={nodes.EB12401_20.geometry}
          material={materials["Metal - Nystrom - Stainless Steel.001"]}
        />
        <mesh
          name="EB12401_21"
          geometry={nodes.EB12401_21.geometry}
          material={materials["Polyester - Nystrom - Glossy Red Coated.001"]}
        />
        <mesh
          name="EB12401_22"
          geometry={nodes.EB12401_22.geometry}
          material={materials["AB_Fire Glass.009"]}
        />
        <mesh
          name="EB12401_23"
          geometry={nodes.EB12401_23.geometry}
          material={materials["AB_RAL9011_Graphite black.009"]}
        />
        <mesh
          name="EB12401_24"
          geometry={nodes.EB12401_24.geometry}
          material={materials["AB_RAL3000_Red.009"]}
        />
        <mesh
          name="EB12401_25"
          geometry={nodes.EB12401_25.geometry}
          material={materials["AB_Steel.009"]}
        />
        <mesh
          name="EB12401_26"
          geometry={nodes.EB12401_26.geometry}
          material={materials["AB_Hose White.009"]}
        />
        <mesh
          name="EB12401_27"
          geometry={nodes.EB12401_27.geometry}
          material={materials["Default.007"]}
        />
        <mesh
          name="EB12401_28"
          geometry={nodes.EB12401_28.geometry}
          material={materials["Assa Abloy - Silver Anodized.001"]}
        />
        <mesh
          name="EB12401_29"
          geometry={nodes.EB12401_29.geometry}
          material={materials["Assa Abloy Plastic.001"]}
        />
        <mesh
          name="EB12401_30"
          geometry={nodes.EB12401_30.geometry}
          material={materials["Silver Anodized.001"]}
        />
        <mesh
          name="EB12401_31"
          geometry={nodes.EB12401_31.geometry}
          material={materials["Glass.009"]}
        />
      </Select>
      <Select
        name="EN124M1"
        enabled={hover === "EN124M1" || select === "EN124M1"}
        onPointerOver={(e) => {
          e.stopPropagation();
          handleObjectHover("EN124M1");
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          handleObjectHover(null);
        }}
        onClick={(e) => {
          e.stopPropagation();
          handleObjectSelect("EN124M1");
        }}
        position={[-2.049, 2.825, 7.381]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.2}
      >
        {renderModalDetail("EN124M1")}
        <mesh
          name="EN124M1_1"
          geometry={nodes.EN124M1_1.geometry}
          material={materials["ผิวคอนกรีต ขัดมัน.011"]}
        />
        <mesh
          name="EN124M1_2"
          geometry={nodes.EN124M1_2.geometry}
          material={materials["ผนังก่ออิฐ ทาสี.011"]}
        />
        <mesh
          name="EN124M1_3"
          geometry={nodes.EN124M1_3.geometry}
          material={materials["ผนังทดลอง.011"]}
        />
        <mesh
          name="EN124M1_4"
          geometry={nodes.EN124M1_4.geometry}
          material={materials["Default Wall.011"]}
        />
        <mesh
          name="EN124M1_5"
          geometry={nodes.EN124M1_5.geometry}
          material={materials["กระเบื้องห้องน้ำ.010"]}
        />
        <mesh
          name="EN124M1_6"
          geometry={nodes.EN124M1_6.geometry}
          material={materials["Glass.010"]}
        />
        <mesh
          name="EN124M1_7"
          geometry={nodes.EN124M1_7.geometry}
          material={materials["Laminate, Ivory, Matte.005"]}
        />
        <mesh
          name="EN124M1_8"
          geometry={nodes.EN124M1_8.geometry}
          material={materials["กระจกใสหนา 1 1/2 หุน.010"]}
        />
        <mesh
          name="EN124M1_9"
          geometry={nodes.EN124M1_9.geometry}
          material={materials["กรอบประตูหน้าต่าง ตา.009"]}
        />
        <mesh
          name="EN124M1_10"
          geometry={nodes.EN124M1_10.geometry}
          material={materials["Default.008"]}
        />
        <mesh
          name="EN124M1_11"
          geometry={nodes.EN124M1_11.geometry}
          material={materials["Aluminum.011"]}
        />
        <mesh
          name="EN124M1_12"
          geometry={nodes.EN124M1_12.geometry}
          material={materials["กระจกใสหนา 2 หุน.011"]}
        />
        <mesh
          name="EN124M1_13"
          geometry={nodes.EN124M1_13.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.030"]}
        />
        <mesh
          name="EN124M1_14"
          geometry={nodes.EN124M1_14.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.031"]}
        />
        <mesh
          name="EN124M1_15"
          geometry={nodes.EN124M1_15.geometry}
          material={materials["ไม้อัดยางทาสี.010"]}
        />
        <mesh
          name="EN124M1_16"
          geometry={nodes.EN124M1_16.geometry}
          material={materials['ไม้เนื้อแข็ง 2" x 4" ทาสี.010']}
        />
        <mesh
          name="EN124M1_17"
          geometry={nodes.EN124M1_17.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.032"]}
        />
        <mesh
          name="EN124M1_18"
          geometry={nodes.EN124M1_18.geometry}
          material={materials["อลูมิเนียมสีเงินขนา.007"]}
        />
        <mesh
          name="EN124M1_19"
          geometry={nodes.EN124M1_19.geometry}
          material={materials["Default New Material.009"]}
        />
        <mesh
          name="EN124M1_20"
          geometry={nodes.EN124M1_20.geometry}
          material={materials["Metal - Steel 43-275.001"]}
        />
        <mesh
          name="EN124M1_21"
          geometry={nodes.EN124M1_21.geometry}
          material={materials["หลังคาโครงเหล็ก.002"]}
        />
        <mesh
          name="EN124M1_22"
          geometry={nodes.EN124M1_22.geometry}
          material={materials["Metal - Steel - 345 MPa.002"]}
        />
        <mesh
          name="EN124M1_23"
          geometry={nodes.EN124M1_23.geometry}
          material={materials["ไม้อัดยาง ทาสี.010"]}
        />
        <mesh
          name="EN124M1_24"
          geometry={nodes.EN124M1_24.geometry}
          material={materials['ไม้เนื้อแข็ง 2"x4" ทาสี.010']}
        />
      </Select>
      <Select
        name="EN12402"
        enabled={hover === "EN12402" || select === "EN12402"}
        onPointerOver={(e) => {
          e.stopPropagation();
          handleObjectHover("EN12402");
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          handleObjectHover(null);
        }}
        onClick={(e) => {
          e.stopPropagation();
          handleObjectSelect("EN12402");
        }}
        position={[-0.45, 5.347, -2.803]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.2}
      >
        {renderModalDetail("EN12402")}
        <mesh
          name="EN12402_1"
          geometry={nodes.EN12402_1.geometry}
          material={materials["ผิวคอนกรีต ขัดมัน.012"]}
        />
        <mesh
          name="EN12402_2"
          geometry={nodes.EN12402_2.geometry}
          material={materials["ผนังก่ออิฐ ทาสี.012"]}
        />
        <mesh
          name="EN12402_3"
          geometry={nodes.EN12402_3.geometry}
          material={materials["ผนังทดลอง.012"]}
        />
        <mesh
          name="EN12402_4"
          geometry={nodes.EN12402_4.geometry}
          material={materials["Default Wall.012"]}
        />
        <mesh
          name="EN12402_5"
          geometry={nodes.EN12402_5.geometry}
          material={materials["กระเบื้องห้องน้ำ.011"]}
        />
        <mesh
          name="EN12402_6"
          geometry={nodes.EN12402_6.geometry}
          material={materials["พื้นคอนกรีตขัดมัน ด้.008"]}
        />
        <mesh
          name="EN12402_7"
          geometry={nodes.EN12402_7.geometry}
          material={materials["Glass.011"]}
        />
        <mesh
          name="EN12402_8"
          geometry={nodes.EN12402_8.geometry}
          material={materials["กระจกใสหนา 1 1/2 หุน.011"]}
        />
        <mesh
          name="EN12402_9"
          geometry={nodes.EN12402_9.geometry}
          material={materials["กรอบประตูหน้าต่าง ตา.010"]}
        />
        <mesh
          name="EN12402_10"
          geometry={nodes.EN12402_10.geometry}
          material={materials["Laminate, Ivory, Matte.006"]}
        />
        <mesh
          name="EN12402_11"
          geometry={nodes.EN12402_11.geometry}
          material={materials["Aluminum.012"]}
        />
        <mesh
          name="EN12402_12"
          geometry={nodes.EN12402_12.geometry}
          material={materials["กระจกใสหนา 2 หุน.012"]}
        />
        <mesh
          name="EN12402_13"
          geometry={nodes.EN12402_13.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.033"]}
        />
        <mesh
          name="EN12402_14"
          geometry={nodes.EN12402_14.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.034"]}
        />
        <mesh
          name="EN12402_15"
          geometry={nodes.EN12402_15.geometry}
          material={materials["ไม้อัดยางทาสี.011"]}
        />
        <mesh
          name="EN12402_16"
          geometry={nodes.EN12402_16.geometry}
          material={materials['ไม้เนื้อแข็ง 2" x 4" ทาสี.011']}
        />
        <mesh
          name="EN12402_17"
          geometry={nodes.EN12402_17.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.035"]}
        />
        <mesh
          name="EN12402_18"
          geometry={nodes.EN12402_18.geometry}
          material={materials["อลูมิเนียมสีเงินขนา.008"]}
        />
        <mesh
          name="EN12402_19"
          geometry={nodes.EN12402_19.geometry}
          material={materials["Default New Material.010"]}
        />
        <mesh
          name="EN12402_20"
          geometry={nodes.EN12402_20.geometry}
          material={materials["ไม้อัดยาง ทาสี.011"]}
        />
        <mesh
          name="EN12402_21"
          geometry={nodes.EN12402_21.geometry}
          material={materials['ไม้เนื้อแข็ง 2"x4" ทาสี.011']}
        />
        <mesh
          name="EN12402_22"
          geometry={nodes.EN12402_22.geometry}
          material={materials["Render Material 128-128-128.010"]}
        />
        <mesh
          name="EN12402_23"
          geometry={nodes.EN12402_23.geometry}
          material={materials["Colour RGB-255 255 255.002"]}
        />
        <mesh
          name="EN12402_24"
          geometry={nodes.EN12402_24.geometry}
          material={materials["Colour RGB-250 000 000.002"]}
        />
        <mesh
          name="EN12402_25"
          geometry={nodes.EN12402_25.geometry}
          material={materials["AB_Fire Glass.010"]}
        />
        <mesh
          name="EN12402_26"
          geometry={nodes.EN12402_26.geometry}
          material={materials["AB_RAL9011_Graphite black.010"]}
        />
        <mesh
          name="EN12402_27"
          geometry={nodes.EN12402_27.geometry}
          material={materials["AB_RAL3000_Red.010"]}
        />
        <mesh
          name="EN12402_28"
          geometry={nodes.EN12402_28.geometry}
          material={materials["AB_Steel.010"]}
        />
        <mesh
          name="EN12402_29"
          geometry={nodes.EN12402_29.geometry}
          material={materials["AB_Hose White.010"]}
        />
      </Select>
      <Select
        name="EN12403"
        enabled={hover === "EN12403" || select === "EN12403"}
        onPointerOver={(e) => {
          e.stopPropagation();
          handleObjectHover("EN12403");
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          handleObjectHover(null);
        }}
        onClick={(e) => {
          e.stopPropagation();
          handleObjectSelect("EN12403");
        }}
        position={[-2.788, 8.072, -3.923]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.2}
      >
        {renderModalDetail("EN12403")}
        <mesh
          name="EN12403_1"
          geometry={nodes.EN12403_1.geometry}
          material={materials["ผิวคอนกรีต ขัดมัน.013"]}
        />
        <mesh
          name="EN12403_2"
          geometry={nodes.EN12403_2.geometry}
          material={materials["ผนังก่ออิฐ ทาสี.013"]}
        />
        <mesh
          name="EN12403_3"
          geometry={nodes.EN12403_3.geometry}
          material={materials["ผนังทดลอง.013"]}
        />
        <mesh
          name="EN12403_4"
          geometry={nodes.EN12403_4.geometry}
          material={materials["Default Wall.013"]}
        />
        <mesh
          name="EN12403_5"
          geometry={nodes.EN12403_5.geometry}
          material={materials["กระเบื้องห้องน้ำ.012"]}
        />
        <mesh
          name="EN12403_6"
          geometry={nodes.EN12403_6.geometry}
          material={materials["พื้นคอนกรีตขัดมัน ด้.009"]}
        />
        <mesh
          name="EN12403_7"
          geometry={nodes.EN12403_7.geometry}
          material={materials["Glass.012"]}
        />
        <mesh
          name="EN12403_8"
          geometry={nodes.EN12403_8.geometry}
          material={materials["กระจกใสหนา 1 1/2 หุน.012"]}
        />
        <mesh
          name="EN12403_9"
          geometry={nodes.EN12403_9.geometry}
          material={materials["กรอบประตูหน้าต่าง ตา.011"]}
        />
        <mesh
          name="EN12403_10"
          geometry={nodes.EN12403_10.geometry}
          material={materials["Laminate, Ivory, Matte.007"]}
        />
        <mesh
          name="EN12403_11"
          geometry={nodes.EN12403_11.geometry}
          material={materials["Aluminum.013"]}
        />
        <mesh
          name="EN12403_12"
          geometry={nodes.EN12403_12.geometry}
          material={materials["กระจกใสหนา 2 หุน.013"]}
        />
        <mesh
          name="EN12403_13"
          geometry={nodes.EN12403_13.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.036"]}
        />
        <mesh
          name="EN12403_14"
          geometry={nodes.EN12403_14.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.037"]}
        />
        <mesh
          name="EN12403_15"
          geometry={nodes.EN12403_15.geometry}
          material={materials["ไม้อัดยางทาสี.012"]}
        />
        <mesh
          name="EN12403_16"
          geometry={nodes.EN12403_16.geometry}
          material={materials['ไม้เนื้อแข็ง 2" x 4" ทาสี.012']}
        />
        <mesh
          name="EN12403_17"
          geometry={nodes.EN12403_17.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.038"]}
        />
        <mesh
          name="EN12403_18"
          geometry={nodes.EN12403_18.geometry}
          material={materials["อลูมิเนียมสีเงินขนา.009"]}
        />
        <mesh
          name="EN12403_19"
          geometry={nodes.EN12403_19.geometry}
          material={materials["Default New Material.011"]}
        />
        <mesh
          name="EN12403_20"
          geometry={nodes.EN12403_20.geometry}
          material={materials["ไม้อัดยาง ทาสี.012"]}
        />
        <mesh
          name="EN12403_21"
          geometry={nodes.EN12403_21.geometry}
          material={materials['ไม้เนื้อแข็ง 2"x4" ทาสี.012']}
        />
        <mesh
          name="EN12403_22"
          geometry={nodes.EN12403_22.geometry}
          material={materials["AB_Fire Glass.011"]}
        />
        <mesh
          name="EN12403_23"
          geometry={nodes.EN12403_23.geometry}
          material={materials["AB_RAL9011_Graphite black.011"]}
        />
        <mesh
          name="EN12403_24"
          geometry={nodes.EN12403_24.geometry}
          material={materials["AB_RAL3000_Red.011"]}
        />
        <mesh
          name="EN12403_25"
          geometry={nodes.EN12403_25.geometry}
          material={materials["AB_Steel.011"]}
        />
        <mesh
          name="EN12403_26"
          geometry={nodes.EN12403_26.geometry}
          material={materials["AB_Hose White.011"]}
        />
        <mesh
          name="EN12403_27"
          geometry={nodes.EN12403_27.geometry}
          material={materials["Colour RGB-255 255 255.003"]}
        />
        <mesh
          name="EN12403_28"
          geometry={nodes.EN12403_28.geometry}
          material={materials["Colour RGB-250 000 000.003"]}
        />
      </Select>
      <Select
        name="EN12404"
        enabled={hover === "EN12404" || select === "EN12404"}
        onPointerOver={(e) => {
          e.stopPropagation();
          handleObjectHover("EN12404");
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          handleObjectHover(null);
        }}
        onClick={(e) => {
          e.stopPropagation();
          handleObjectSelect("EN12404");
        }}
        position={[-1.664, 10.7, -0.874]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.2}
      >
        {renderModalDetail("EN12404")}
        <mesh
          name="EN12404_1"
          geometry={nodes.EN12404_1.geometry}
          material={materials["ผิวคอนกรีต ขัดมัน.014"]}
        />
        <mesh
          name="EN12404_2"
          geometry={nodes.EN12404_2.geometry}
          material={materials["ผนังก่ออิฐ ทาสี.014"]}
        />
        <mesh
          name="EN12404_3"
          geometry={nodes.EN12404_3.geometry}
          material={materials["ผนังทดลอง.014"]}
        />
        <mesh
          name="EN12404_4"
          geometry={nodes.EN12404_4.geometry}
          material={materials["Default Wall.014"]}
        />
        <mesh
          name="EN12404_5"
          geometry={nodes.EN12404_5.geometry}
          material={materials["พื้นคอนกรีตขัดมัน ด้.010"]}
        />
        <mesh
          name="EN12404_6"
          geometry={nodes.EN12404_6.geometry}
          material={materials["กระเบื้องห้องน้ำ.013"]}
        />
        <mesh
          name="EN12404_7"
          geometry={nodes.EN12404_7.geometry}
          material={materials["Glass.013"]}
        />
        <mesh
          name="EN12404_8"
          geometry={nodes.EN12404_8.geometry}
          material={materials["Laminate, Ivory, Matte.008"]}
        />
        <mesh
          name="EN12404_9"
          geometry={nodes.EN12404_9.geometry}
          material={materials["กระจกใสหนา 1 1/2 หุน.013"]}
        />
        <mesh
          name="EN12404_10"
          geometry={nodes.EN12404_10.geometry}
          material={materials["กรอบประตูหน้าต่าง ตา.012"]}
        />
        <mesh
          name="EN12404_11"
          geometry={nodes.EN12404_11.geometry}
          material={materials["Aluminum.014"]}
        />
        <mesh
          name="EN12404_12"
          geometry={nodes.EN12404_12.geometry}
          material={materials["กระจกใสหนา 2 หุน.014"]}
        />
        <mesh
          name="EN12404_13"
          geometry={nodes.EN12404_13.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.039"]}
        />
        <mesh
          name="EN12404_14"
          geometry={nodes.EN12404_14.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.040"]}
        />
        <mesh
          name="EN12404_15"
          geometry={nodes.EN12404_15.geometry}
          material={materials["ไม้อัดยางทาสี.013"]}
        />
        <mesh
          name="EN12404_16"
          geometry={nodes.EN12404_16.geometry}
          material={materials['ไม้เนื้อแข็ง 2" x 4" ทาสี.013']}
        />
        <mesh
          name="EN12404_17"
          geometry={nodes.EN12404_17.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.041"]}
        />
        <mesh
          name="EN12404_18"
          geometry={nodes.EN12404_18.geometry}
          material={materials["อลูมิเนียมสีเงินขนา.010"]}
        />
        <mesh
          name="EN12404_19"
          geometry={nodes.EN12404_19.geometry}
          material={materials["Default.009"]}
        />
        <mesh
          name="EN12404_20"
          geometry={nodes.EN12404_20.geometry}
          material={materials["Default New Material.012"]}
        />
        <mesh
          name="EN12404_21"
          geometry={nodes.EN12404_21.geometry}
          material={materials["ไม้อัดยาง ทาสี.013"]}
        />
        <mesh
          name="EN12404_22"
          geometry={nodes.EN12404_22.geometry}
          material={materials['ไม้เนื้อแข็ง 2"x4" ทาสี.013']}
        />
        <mesh
          name="EN12404_23"
          geometry={nodes.EN12404_23.geometry}
          material={materials["AB_Fire Glass.012"]}
        />
        <mesh
          name="EN12404_24"
          geometry={nodes.EN12404_24.geometry}
          material={materials["AB_RAL9011_Graphite black.012"]}
        />
        <mesh
          name="EN12404_25"
          geometry={nodes.EN12404_25.geometry}
          material={materials["AB_RAL3000_Red.012"]}
        />
        <mesh
          name="EN12404_26"
          geometry={nodes.EN12404_26.geometry}
          material={materials["AB_Steel.012"]}
        />
        <mesh
          name="EN12404_27"
          geometry={nodes.EN12404_27.geometry}
          material={materials["AB_Hose White.012"]}
        />
      </Select>
      <Select
        name="EN12405"
        enabled={hover === "EN12405" || select === "EN12405"}
        onPointerOver={(e) => {
          e.stopPropagation();
          handleObjectHover("EN12405");
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          handleObjectHover(null);
        }}
        onClick={(e) => {
          e.stopPropagation();
          handleObjectSelect("EN12405");
        }}
        position={[-1.963, 13.266, -1.563]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.2}
      >
        {renderModalDetail("EN12405")}
        <mesh
          name="EN12405_1"
          geometry={nodes.EN12405_1.geometry}
          material={materials["ผิวคอนกรีต ขัดมัน.015"]}
        />
        <mesh
          name="EN12405_2"
          geometry={nodes.EN12405_2.geometry}
          material={materials["ผนังก่ออิฐ ทาสี.015"]}
        />
        <mesh
          name="EN12405_3"
          geometry={nodes.EN12405_3.geometry}
          material={materials["ผนังทดลอง.015"]}
        />
        <mesh
          name="EN12405_4"
          geometry={nodes.EN12405_4.geometry}
          material={materials["Default Wall.015"]}
        />
        <mesh
          name="EN12405_5"
          geometry={nodes.EN12405_5.geometry}
          material={materials["กระเบื้องห้องน้ำ.014"]}
        />
        <mesh
          name="EN12405_6"
          geometry={nodes.EN12405_6.geometry}
          material={materials["พื้นคอนกรีตขัดมัน ด้.011"]}
        />
        <mesh
          name="EN12405_7"
          geometry={nodes.EN12405_7.geometry}
          material={materials["Glass.014"]}
        />
        <mesh
          name="EN12405_8"
          geometry={nodes.EN12405_8.geometry}
          material={materials["Laminate, Ivory, Matte.009"]}
        />
        <mesh
          name="EN12405_9"
          geometry={nodes.EN12405_9.geometry}
          material={materials["กระจกใสหนา 1 1/2 หุน.014"]}
        />
        <mesh
          name="EN12405_10"
          geometry={nodes.EN12405_10.geometry}
          material={materials["กรอบประตูหน้าต่าง ตา.013"]}
        />
        <mesh
          name="EN12405_11"
          geometry={nodes.EN12405_11.geometry}
          material={materials["Aluminum.015"]}
        />
        <mesh
          name="EN12405_12"
          geometry={nodes.EN12405_12.geometry}
          material={materials["กระจกใสหนา 2 หุน.015"]}
        />
        <mesh
          name="EN12405_13"
          geometry={nodes.EN12405_13.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.042"]}
        />
        <mesh
          name="EN12405_14"
          geometry={nodes.EN12405_14.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.043"]}
        />
        <mesh
          name="EN12405_15"
          geometry={nodes.EN12405_15.geometry}
          material={materials["ไม้อัดยางทาสี.014"]}
        />
        <mesh
          name="EN12405_16"
          geometry={nodes.EN12405_16.geometry}
          material={materials['ไม้เนื้อแข็ง 2" x 4" ทาสี.014']}
        />
        <mesh
          name="EN12405_17"
          geometry={nodes.EN12405_17.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.044"]}
        />
        <mesh
          name="EN12405_18"
          geometry={nodes.EN12405_18.geometry}
          material={materials["Default.010"]}
        />
        <mesh
          name="EN12405_19"
          geometry={nodes.EN12405_19.geometry}
          material={materials["อลูมิเนียมสีเงินขนา.011"]}
        />
        <mesh
          name="EN12405_20"
          geometry={nodes.EN12405_20.geometry}
          material={materials["Default New Material.013"]}
        />
        <mesh
          name="EN12405_21"
          geometry={nodes.EN12405_21.geometry}
          material={materials["ไม้อัดยาง ทาสี.014"]}
        />
        <mesh
          name="EN12405_22"
          geometry={nodes.EN12405_22.geometry}
          material={materials['ไม้เนื้อแข็ง 2"x4" ทาสี.014']}
        />
        <mesh
          name="EN12405_23"
          geometry={nodes.EN12405_23.geometry}
          material={materials["AB_Fire Glass.013"]}
        />
        <mesh
          name="EN12405_24"
          geometry={nodes.EN12405_24.geometry}
          material={materials["AB_RAL9011_Graphite black.013"]}
        />
        <mesh
          name="EN12405_25"
          geometry={nodes.EN12405_25.geometry}
          material={materials["AB_RAL3000_Red.013"]}
        />
        <mesh
          name="EN12405_26"
          geometry={nodes.EN12405_26.geometry}
          material={materials["AB_Steel.013"]}
        />
        <mesh
          name="EN12405_27"
          geometry={nodes.EN12405_27.geometry}
          material={materials["AB_Hose White.013"]}
        />
      </Select>
      <Select
        name="EN12406"
        enabled={hover === "EN12406" || select === "EN12406"}
        onPointerOver={(e) => {
          e.stopPropagation();
          handleObjectHover("EN12406");
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          handleObjectHover(null);
        }}
        onClick={(e) => {
          e.stopPropagation();
          handleObjectSelect("EN12406");
        }}
        position={[-1.566, 15.918, -1.541]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.2}
      >
        {renderModalDetail("EN12406")}
        <mesh
          name="EN12406_1"
          geometry={nodes.EN12406_1.geometry}
          material={materials["ผิวคอนกรีต ขัดมัน.016"]}
        />
        <mesh
          name="EN12406_2"
          geometry={nodes.EN12406_2.geometry}
          material={materials["ผนังก่ออิฐ ทาสี.016"]}
        />
        <mesh
          name="EN12406_3"
          geometry={nodes.EN12406_3.geometry}
          material={materials["ผนังทดลอง.016"]}
        />
        <mesh
          name="EN12406_4"
          geometry={nodes.EN12406_4.geometry}
          material={materials["Default Wall.016"]}
        />
        <mesh
          name="EN12406_5"
          geometry={nodes.EN12406_5.geometry}
          material={materials["กระเบื้องห้องน้ำ.015"]}
        />
        <mesh
          name="EN12406_6"
          geometry={nodes.EN12406_6.geometry}
          material={materials["พื้นคอนกรีตขัดมัน ด้.012"]}
        />
        <mesh
          name="EN12406_7"
          geometry={nodes.EN12406_7.geometry}
          material={materials["Glass.015"]}
        />
        <mesh
          name="EN12406_8"
          geometry={nodes.EN12406_8.geometry}
          material={materials["กระจกใสหนา 1 1/2 หุน.015"]}
        />
        <mesh
          name="EN12406_9"
          geometry={nodes.EN12406_9.geometry}
          material={materials["กรอบประตูหน้าต่าง ตา.014"]}
        />
        <mesh
          name="EN12406_10"
          geometry={nodes.EN12406_10.geometry}
          material={materials["Aluminum.016"]}
        />
        <mesh
          name="EN12406_11"
          geometry={nodes.EN12406_11.geometry}
          material={materials["กระจกใสหนา 2 หุน.016"]}
        />
        <mesh
          name="EN12406_12"
          geometry={nodes.EN12406_12.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.045"]}
        />
        <mesh
          name="EN12406_13"
          geometry={nodes.EN12406_13.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.046"]}
        />
        <mesh
          name="EN12406_14"
          geometry={nodes.EN12406_14.geometry}
          material={materials["ไม้อัดยางทาสี.015"]}
        />
        <mesh
          name="EN12406_15"
          geometry={nodes.EN12406_15.geometry}
          material={materials['ไม้เนื้อแข็ง 2" x 4" ทาสี.015']}
        />
        <mesh
          name="EN12406_16"
          geometry={nodes.EN12406_16.geometry}
          material={materials["อลูมิเนียมสีเงินขนา.012"]}
        />
        <mesh
          name="EN12406_17"
          geometry={nodes.EN12406_17.geometry}
          material={materials["Default.011"]}
        />
        <mesh
          name="EN12406_18"
          geometry={nodes.EN12406_18.geometry}
          material={materials["Default New Material.014"]}
        />
        <mesh
          name="EN12406_19"
          geometry={nodes.EN12406_19.geometry}
          material={materials["ไม้อัดยาง ทาสี.015"]}
        />
        <mesh
          name="EN12406_20"
          geometry={nodes.EN12406_20.geometry}
          material={materials['ไม้เนื้อแข็ง 2"x4" ทาสี.015']}
        />
        <mesh
          name="EN12406_21"
          geometry={nodes.EN12406_21.geometry}
          material={materials["AB_Fire Glass.014"]}
        />
        <mesh
          name="EN12406_22"
          geometry={nodes.EN12406_22.geometry}
          material={materials["AB_RAL9011_Graphite black.014"]}
        />
        <mesh
          name="EN12406_23"
          geometry={nodes.EN12406_23.geometry}
          material={materials["AB_RAL3000_Red.014"]}
        />
        <mesh
          name="EN12406_24"
          geometry={nodes.EN12406_24.geometry}
          material={materials["AB_Steel.014"]}
        />
        <mesh
          name="EN12406_25"
          geometry={nodes.EN12406_25.geometry}
          material={materials["AB_Hose White.014"]}
        />
      </Select>
      <Select
        name="EN12407"
        enabled={hover === "EN12407" || select === "EN12407"}
        onPointerOver={(e) => {
          e.stopPropagation();
          handleObjectHover("EN12407");
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          handleObjectHover(null);
        }}
        onClick={(e) => {
          e.stopPropagation();
          handleObjectSelect("EN12407");
        }}
        position={[-1.684, 18.552, -1.757]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.2}
      >
        {renderModalDetail("EN12407")}
        <mesh
          name="EN12407_1"
          geometry={nodes.EN12407_1.geometry}
          material={materials["ผิวคอนกรีต ขัดมัน.017"]}
        />
        <mesh
          name="EN12407_2"
          geometry={nodes.EN12407_2.geometry}
          material={materials["ผนังก่ออิฐ ทาสี.017"]}
        />
        <mesh
          name="EN12407_3"
          geometry={nodes.EN12407_3.geometry}
          material={materials["ผนังทดลอง.017"]}
        />
        <mesh
          name="EN12407_4"
          geometry={nodes.EN12407_4.geometry}
          material={materials["Default Wall.017"]}
        />
        <mesh
          name="EN12407_5"
          geometry={nodes.EN12407_5.geometry}
          material={materials["กระเบื้องห้องน้ำ.016"]}
        />
        <mesh
          name="EN12407_6"
          geometry={nodes.EN12407_6.geometry}
          material={materials["พื้นคอนกรีตขัดมัน ด้.013"]}
        />
        <mesh
          name="EN12407_7"
          geometry={nodes.EN12407_7.geometry}
          material={materials["Glass.016"]}
        />
        <mesh
          name="EN12407_8"
          geometry={nodes.EN12407_8.geometry}
          material={materials["กรอบประตูหน้าต่าง ตา.015"]}
        />
        <mesh
          name="EN12407_9"
          geometry={nodes.EN12407_9.geometry}
          material={materials["กระจกใสหนา 1 1/2 หุน.016"]}
        />
        <mesh
          name="EN12407_10"
          geometry={nodes.EN12407_10.geometry}
          material={materials["Aluminum.017"]}
        />
        <mesh
          name="EN12407_11"
          geometry={nodes.EN12407_11.geometry}
          material={materials["กระจกใสหนา 2 หุน.017"]}
        />
        <mesh
          name="EN12407_12"
          geometry={nodes.EN12407_12.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.047"]}
        />
        <mesh
          name="EN12407_13"
          geometry={nodes.EN12407_13.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.048"]}
        />
        <mesh
          name="EN12407_14"
          geometry={nodes.EN12407_14.geometry}
          material={materials["ไม้อัดยางทาสี.016"]}
        />
        <mesh
          name="EN12407_15"
          geometry={nodes.EN12407_15.geometry}
          material={materials['ไม้เนื้อแข็ง 2" x 4" ทาสี.016']}
        />
        <mesh
          name="EN12407_16"
          geometry={nodes.EN12407_16.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.049"]}
        />
        <mesh
          name="EN12407_17"
          geometry={nodes.EN12407_17.geometry}
          material={materials["อลูมิเนียมสีเงินขนา.013"]}
        />
        <mesh
          name="EN12407_18"
          geometry={nodes.EN12407_18.geometry}
          material={materials["Default.012"]}
        />
        <mesh
          name="EN12407_19"
          geometry={nodes.EN12407_19.geometry}
          material={materials["Default New Material.015"]}
        />
        <mesh
          name="EN12407_20"
          geometry={nodes.EN12407_20.geometry}
          material={materials["ไม้อัดยาง ทาสี.016"]}
        />
        <mesh
          name="EN12407_21"
          geometry={nodes.EN12407_21.geometry}
          material={materials['ไม้เนื้อแข็ง 2"x4" ทาสี.016']}
        />
        <mesh
          name="EN12407_22"
          geometry={nodes.EN12407_22.geometry}
          material={materials["AB_Fire Glass.015"]}
        />
        <mesh
          name="EN12407_23"
          geometry={nodes.EN12407_23.geometry}
          material={materials["AB_RAL9011_Graphite black.015"]}
        />
        <mesh
          name="EN12407_24"
          geometry={nodes.EN12407_24.geometry}
          material={materials["AB_RAL3000_Red.015"]}
        />
        <mesh
          name="EN12407_25"
          geometry={nodes.EN12407_25.geometry}
          material={materials["AB_Steel.015"]}
        />
        <mesh
          name="EN12407_26"
          geometry={nodes.EN12407_26.geometry}
          material={materials["AB_Hose White.015"]}
        />
      </Select>
      <Select
        name="EN12408"
        enabled={hover === "EN12408" || select === "EN12408"}
        onPointerOver={(e) => {
          e.stopPropagation();
          handleObjectHover("EN12408");
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          handleObjectHover(null);
        }}
        onClick={(e) => {
          e.stopPropagation();
          handleObjectSelect("EN12408");
        }}
        position={[-1.67, 21.204, -1.531]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.2}
      >
        {renderModalDetail("EN12408")}
        <mesh
          name="EN12408_1"
          geometry={nodes.EN12408_1.geometry}
          material={materials["ผิวคอนกรีต ขัดมัน.018"]}
        />
        <mesh
          name="EN12408_2"
          geometry={nodes.EN12408_2.geometry}
          material={materials["ผนังก่ออิฐ ทาสี.018"]}
        />
        <mesh
          name="EN12408_3"
          geometry={nodes.EN12408_3.geometry}
          material={materials["ผนังทดลอง.018"]}
        />
        <mesh
          name="EN12408_4"
          geometry={nodes.EN12408_4.geometry}
          material={materials["Default Wall.018"]}
        />
        <mesh
          name="EN12408_5"
          geometry={nodes.EN12408_5.geometry}
          material={materials["กระเบื้องห้องน้ำ.017"]}
        />
        <mesh
          name="EN12408_6"
          geometry={nodes.EN12408_6.geometry}
          material={materials["พื้นคอนกรีตขัดมัน ด้.014"]}
        />
        <mesh
          name="EN12408_7"
          geometry={nodes.EN12408_7.geometry}
          material={materials["Glass.017"]}
        />
        <mesh
          name="EN12408_8"
          geometry={nodes.EN12408_8.geometry}
          material={materials["กระจกใสหนา 1 1/2 หุน.017"]}
        />
        <mesh
          name="EN12408_9"
          geometry={nodes.EN12408_9.geometry}
          material={materials["กรอบประตูหน้าต่าง ตา.016"]}
        />
        <mesh
          name="EN12408_10"
          geometry={nodes.EN12408_10.geometry}
          material={materials["Aluminum.018"]}
        />
        <mesh
          name="EN12408_11"
          geometry={nodes.EN12408_11.geometry}
          material={materials["กระจกใสหนา 2 หุน.018"]}
        />
        <mesh
          name="EN12408_12"
          geometry={nodes.EN12408_12.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.050"]}
        />
        <mesh
          name="EN12408_13"
          geometry={nodes.EN12408_13.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.051"]}
        />
        <mesh
          name="EN12408_14"
          geometry={nodes.EN12408_14.geometry}
          material={materials["ไม้อัดยางทาสี.017"]}
        />
        <mesh
          name="EN12408_15"
          geometry={nodes.EN12408_15.geometry}
          material={materials['ไม้เนื้อแข็ง 2" x 4" ทาสี.017']}
        />
        <mesh
          name="EN12408_16"
          geometry={nodes.EN12408_16.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.052"]}
        />
        <mesh
          name="EN12408_17"
          geometry={nodes.EN12408_17.geometry}
          material={materials["อลูมิเนียมสีเงินขนา.014"]}
        />
        <mesh
          name="EN12408_18"
          geometry={nodes.EN12408_18.geometry}
          material={materials["Default.013"]}
        />
        <mesh
          name="EN12408_19"
          geometry={nodes.EN12408_19.geometry}
          material={materials["Default New Material.016"]}
        />
        <mesh
          name="EN12408_20"
          geometry={nodes.EN12408_20.geometry}
          material={materials["ไม้อัดยาง ทาสี.017"]}
        />
        <mesh
          name="EN12408_21"
          geometry={nodes.EN12408_21.geometry}
          material={materials['ไม้เนื้อแข็ง 2"x4" ทาสี.017']}
        />
        <mesh
          name="EN12408_22"
          geometry={nodes.EN12408_22.geometry}
          material={materials["AB_Fire Glass.016"]}
        />
        <mesh
          name="EN12408_23"
          geometry={nodes.EN12408_23.geometry}
          material={materials["AB_RAL9011_Graphite black.016"]}
        />
        <mesh
          name="EN12408_24"
          geometry={nodes.EN12408_24.geometry}
          material={materials["AB_RAL3000_Red.016"]}
        />
        <mesh
          name="EN12408_25"
          geometry={nodes.EN12408_25.geometry}
          material={materials["AB_Steel.016"]}
        />
        <mesh
          name="EN12408_26"
          geometry={nodes.EN12408_26.geometry}
          material={materials["AB_Hose White.016"]}
        />
      </Select>
      <group
        name="EN124RF"
        position={[-2.021, 24.532, 4.526]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.2}
      >
        <mesh
          name="EN124RF_1"
          geometry={nodes.EN124RF_1.geometry}
          material={materials["ผนังก่ออิฐ ทาสี.019"]}
        />
        <mesh
          name="EN124RF_2"
          geometry={nodes.EN124RF_2.geometry}
          material={materials["ผนังทดลอง.019"]}
        />
        <mesh
          name="EN124RF_3"
          geometry={nodes.EN124RF_3.geometry}
          material={materials["Default Wall.019"]}
        />
        <mesh
          name="EN124RF_4"
          geometry={nodes.EN124RF_4.geometry}
          material={materials["ผิวคอนกรีต ขัดมัน.019"]}
        />
        <mesh
          name="EN124RF_5"
          geometry={nodes.EN124RF_5.geometry}
          material={materials["ผิวคอนกรีตหลังคา.001"]}
        />
        <mesh
          name="EN124RF_6"
          geometry={nodes.EN124RF_6.geometry}
          material={materials["Default New Material.017"]}
        />
        <mesh
          name="EN124RF_7"
          geometry={nodes.EN124RF_7.geometry}
          material={materials["หลังคาโครงเหล็ก.003"]}
        />
        <mesh
          name="EN124RF_8"
          geometry={nodes.EN124RF_8.geometry}
          material={materials["Metal - Steel - 345 MPa.003"]}
        />
        <mesh
          name="EN124RF_9"
          geometry={nodes.EN124RF_9.geometry}
          material={materials["กระจกใสหนา 2 หุน.019"]}
        />
        <mesh
          name="EN124RF_10"
          geometry={nodes.EN124RF_10.geometry}
          material={materials["AB_Fire Glass.017"]}
        />
        <mesh
          name="EN124RF_11"
          geometry={nodes.EN124RF_11.geometry}
          material={materials["AB_RAL9011_Graphite black.017"]}
        />
        <mesh
          name="EN124RF_12"
          geometry={nodes.EN124RF_12.geometry}
          material={materials["AB_RAL3000_Red.017"]}
        />
        <mesh
          name="EN124RF_13"
          geometry={nodes.EN124RF_13.geometry}
          material={materials["AB_Steel.017"]}
        />
        <mesh
          name="EN124RF_14"
          geometry={nodes.EN124RF_14.geometry}
          material={materials["AB_Hose White.017"]}
        />
        <mesh
          name="EN124RF_15"
          geometry={nodes.EN124RF_15.geometry}
          material={materials["Metal Stud Layer.001"]}
        />
        <mesh
          name="EN124RF_16"
          geometry={nodes.EN124RF_16.geometry}
          material={materials["Gypsum Wall Board.001"]}
        />
        <mesh
          name="EN124RF_17"
          geometry={nodes.EN124RF_17.geometry}
          material={materials["Aluminum.019"]}
        />
        <mesh
          name="EN124RF_18"
          geometry={nodes.EN124RF_18.geometry}
          material={materials["White.001"]}
        />
        <mesh
          name="EN124RF_19"
          geometry={nodes.EN124RF_19.geometry}
          material={materials["Plastic.001"]}
        />
        <mesh
          name="EN124RF_20"
          geometry={nodes.EN124RF_20.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.053"]}
        />
        <mesh
          name="EN124RF_21"
          geometry={nodes.EN124RF_21.geometry}
          material={materials["เหล็ก ตามมาตราฐาน Decoradoo.054"]}
        />
      </group>
      <mesh
        name="Plane"
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
        position={[-101.67, -0.225, -1.64]}
        scale={[622.703, 0.655, 622.703]}
      />
    </group>
  );
}

useGLTF.preload("/models/building/en124/en124-building.glb");
