/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/building/en107/en107.glb -t -k -E -R -f 
*/

"use client";

import * as THREE from "three";
import React, { useCallback, useEffect, useRef, useState } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useEN107Store } from "@/stores/use-building-store";
import { IFloorDetails } from "@/types/model";
import { getData } from "@/actions/actions";
import Link from "next/link";
import { Button } from "@/components/shadcn-ui/button";
import { ExternalLink } from "lucide-react";
import {
  Table,
  TableBody,
  TableCell,
  TableRow,
} from "@/components/shadcn-ui/table";
import { Select } from "@react-three/postprocessing";
import { getFloorActiveStatus } from "@/lib/utils";

type GLTFResult = GLTF & {
  nodes: {
    ['หน้าต่าง-1500x2900002']: THREE.Mesh
    ['หน้าต่าง-1500x2900002_1']: THREE.Mesh
    ['หน้าต่าง-1500x2900002_2']: THREE.Mesh
    ['หน้าต่าง-1500x2900002_3']: THREE.Mesh
    ['หน้าต่าง-1500x2900002_4']: THREE.Mesh
    ['หน้าต่าง-1500x2900002_5']: THREE.Mesh
    ['หน้าต่าง-1500x2900002_6']: THREE.Mesh
    ['หน้าต่าง-1500x2900002_7']: THREE.Mesh
    ['หน้าต่าง-1500x2900002_8']: THREE.Mesh
    ['หน้าต่าง-1500x2900002_9']: THREE.Mesh
    ['หน้าต่าง-1500x2900002_10']: THREE.Mesh
    ['หน้าต่าง-1500x2900002_11']: THREE.Mesh
    ระดับหัวเสารับ_Truss001: THREE.Mesh
    ระดับหัวเสารับ_Truss001_1: THREE.Mesh
    ระดับหัวเสารับ_Truss001_2: THREE.Mesh
    ระดับหัวเสารับ_Truss001_3: THREE.Mesh
    ระดับหัวเสารับ_Truss001_4: THREE.Mesh
    ระดับหัวเสารับ_Truss001_5: THREE.Mesh
    ระดับหัวเสารับ_Truss001_6: THREE.Mesh
    ระดับหัวเสารับ_Truss001_7: THREE.Mesh
    ระดับหัวเสารับ_Truss001_8: THREE.Mesh
    ระดับหัวเสารับ_Truss001_9: THREE.Mesh
    C3_025_x_050_m_steel_plate022: THREE.Mesh
    C3_025_x_050_m_steel_plate022_1: THREE.Mesh
    C3_025_x_050_m_steel_plate022_2: THREE.Mesh
    C3_025_x_050_m_steel_plate022_3: THREE.Mesh
    C3_025_x_050_m_steel_plate022_4: THREE.Mesh
    C3_025_x_050_m_steel_plate022_5: THREE.Mesh
    C3_025_x_050_m_steel_plate022_6: THREE.Mesh
  }
  materials: {
    Glass: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray']: THREE.MeshStandardMaterial
    ['Wall-very-ligth-blue']: THREE.MeshStandardMaterial
    ['Default white']: THREE.MeshStandardMaterial
    ['Default Wall']: THREE.MeshStandardMaterial
    Aluminum: THREE.MeshStandardMaterial
    ['Door-wood-01']: THREE.MeshStandardMaterial
    ['Metal - Stainless Steel']: THREE.MeshStandardMaterial
    ['Brick, Common']: THREE.MeshStandardMaterial
    ['Steel, Paint Finish, Ivory, Matte']: THREE.MeshStandardMaterial
    ['Stainless steel Matt']: THREE.MeshStandardMaterial
    ['Steel-CaptiveAire']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.001']: THREE.MeshStandardMaterial
    ['Default white.001']: THREE.MeshStandardMaterial
    ['Wall-very-ligth-blue.001']: THREE.MeshStandardMaterial
    ['Default Wall.001']: THREE.MeshStandardMaterial
    ['Brick, Common.001']: THREE.MeshStandardMaterial
    Steel: THREE.MeshStandardMaterial
    ['Glass.001']: THREE.MeshStandardMaterial
    ['Metal - Stainless Steel.001']: THREE.MeshStandardMaterial
    ['Door-wood-01.001']: THREE.MeshStandardMaterial
    ['Aluminum.001']: THREE.MeshStandardMaterial
    ['Steel.001']: THREE.MeshStandardMaterial
    ['Steel, 45-345']: THREE.MeshStandardMaterial
    ['Steel ASTM A992']: THREE.MeshStandardMaterial
    ['Default Roof']: THREE.MeshStandardMaterial
    ['Roofs(1)']: THREE.MeshStandardMaterial
    ['Steel ASTM A36']: THREE.MeshStandardMaterial
    ['Gypsum Wall Board(1)']: THREE.MeshStandardMaterial
  }
}

export const en107Floors = ["EN10701", "EN10702"] as const;

export type EN107Floor = (typeof en107Floors)[number];

type Props = JSX.IntrinsicElements["group"] & {
  isManage: boolean;
};

export default function EN107Building(props: Props) {
  const { nodes, materials } = useGLTF('/models/building/en107/en107.glb') as GLTFResult
  const groupRef = useRef<any>();
  const [hover, setHover] = useState<EN107Floor | null>(null);
  const { select, setSelect } = useEN107Store((state) => state);
  const [floorDetail, setFloorDetail] = useState<IFloorDetails | null>(null);

  const handleObjectHover = useCallback((object: EN107Floor | null) => {
    setHover(object);
  }, []);

  const handleObjectSelect = useCallback(
    (object: EN107Floor) => {
      setSelect(object);
    },
    [setSelect]
  );

  useEffect(() => {
    const fetchFloorDetail = async () => {
      const data = await getData(
        `buildingFloorDetail/${select?.toUpperCase()}`
      );
      setFloorDetail(data);
    };

    fetchFloorDetail();
  }, [select]);

  const renderModalDetail = (floorCode: string) => {
    const isFloorActive = getFloorActiveStatus(
      select?.substring(0, 5),
      select as string
    );
    if (select === floorCode && !props.isManage) {
      return (
        <Html distanceFactor={60}>
          <div className="pt-[10px] transform translate-x-[80%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ชั้น ${floorCode.substring(5, 7)} - ${floorCode}`}
              </label>
              {isFloorActive && (
                <Link href={`/floor/${floorCode.toUpperCase()}`} target="_blank">
                  <Button variant={"ghost"} size={"icon"}>
                    <ExternalLink className="size-5" />
                  </Button>
                </Link>
              )}
            </div>
            {renderFloorDetail()}
          </div>
        </Html>
      );
    }
  };

  const renderFloorDetail = () => {
    return (
      <Table className="border rounded-md">
        <TableBody>
          <TableRow>
            <TableCell className="p-2">Building Code</TableCell>
            <TableCell className="p-2">
              {floorDetail?.buildingCode || select?.substring(0, 5)}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Floor</TableCell>
            <TableCell className="p-2">
              {floorDetail?.floorNumber || select?.substring(5, 7)}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Meter Energy</TableCell>
            <TableCell className="p-2">
              {floorDetail?.floorMeter ? floorDetail?.floorMeter : "-"}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Meter Power</TableCell>
            <TableCell className="p-2">
              {floorDetail?.floorPower ? floorDetail?.floorPower : "-"}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Average PM 2.5</TableCell>
            <TableCell className="p-2">
              {floorDetail?.averagefloorPM25 ? floorDetail?.averagefloorPM25 : "-"}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Average Temperature</TableCell>
            <TableCell className="p-2">
              {floorDetail?.averagefloorTemp ? floorDetail?.averagefloorTemp : "-"}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Average Humidity</TableCell>
            <TableCell className="p-2">
              {floorDetail?.averagefloorHumidity ? floorDetail?.averagefloorHumidity : "-"}
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    );
  };

  return (
    <group 
      onPointerOver={(e) => {
        e.stopPropagation();
        handleObjectHover(e.object.parent?.name as any);
      }} 
      onPointerOut={(e) => {
        e.stopPropagation();
        handleObjectHover(null)
      }}
      onClick={(e) => {
        e.stopPropagation();
        handleObjectSelect(e.object.parent?.name as any)
      }}
      ref={groupRef} 
      {...props} 
      dispose={null}
    >
      <Select name="EN10701" enabled={hover === "EN10701" || select === "EN10701"} position={[-0.143, 2.322, -0.325]} rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
        {renderModalDetail("EN10701")}
        <mesh name="หน้าต่าง-1500x2900002" geometry={nodes['หน้าต่าง-1500x2900002'].geometry} material={materials.Glass} />
        <mesh name="หน้าต่าง-1500x2900002_1" geometry={nodes['หน้าต่าง-1500x2900002_1'].geometry} material={materials['Concrete, Cast-in-Place gray']} />
        <mesh name="หน้าต่าง-1500x2900002_2" geometry={nodes['หน้าต่าง-1500x2900002_2'].geometry} material={materials['Wall-very-ligth-blue']} />
        <mesh name="หน้าต่าง-1500x2900002_3" geometry={nodes['หน้าต่าง-1500x2900002_3'].geometry} material={materials['Default white']} />
        <mesh name="หน้าต่าง-1500x2900002_4" geometry={nodes['หน้าต่าง-1500x2900002_4'].geometry} material={materials['Default Wall']} />
        <mesh name="หน้าต่าง-1500x2900002_5" geometry={nodes['หน้าต่าง-1500x2900002_5'].geometry} material={materials.Aluminum} />
        <mesh name="หน้าต่าง-1500x2900002_6" geometry={nodes['หน้าต่าง-1500x2900002_6'].geometry} material={materials['Door-wood-01']} />
        <mesh name="หน้าต่าง-1500x2900002_7" geometry={nodes['หน้าต่าง-1500x2900002_7'].geometry} material={materials['Metal - Stainless Steel']} />
        <mesh name="หน้าต่าง-1500x2900002_8" geometry={nodes['หน้าต่าง-1500x2900002_8'].geometry} material={materials['Brick, Common']} />
        <mesh name="หน้าต่าง-1500x2900002_9" geometry={nodes['หน้าต่าง-1500x2900002_9'].geometry} material={materials['Steel, Paint Finish, Ivory, Matte']} />
        <mesh name="หน้าต่าง-1500x2900002_10" geometry={nodes['หน้าต่าง-1500x2900002_10'].geometry} material={materials['Stainless steel Matt']} />
        <mesh name="หน้าต่าง-1500x2900002_11" geometry={nodes['หน้าต่าง-1500x2900002_11'].geometry} material={materials['Steel-CaptiveAire']} />
      </Select>
      <Select name="EN10702" enabled={hover === "EN10702" || select === "EN10702"} position={[-5.842, 5.35, 0.394]} rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
        {renderModalDetail("EN10702")}
        <mesh name="ระดับหัวเสารับ_Truss001" geometry={nodes.ระดับหัวเสารับ_Truss001.geometry} material={materials['Concrete, Cast-in-Place gray.001']} />
        <mesh name="ระดับหัวเสารับ_Truss001_1" geometry={nodes.ระดับหัวเสารับ_Truss001_1.geometry} material={materials['Default white.001']} />
        <mesh name="ระดับหัวเสารับ_Truss001_2" geometry={nodes.ระดับหัวเสารับ_Truss001_2.geometry} material={materials['Wall-very-ligth-blue.001']} />
        <mesh name="ระดับหัวเสารับ_Truss001_3" geometry={nodes.ระดับหัวเสารับ_Truss001_3.geometry} material={materials['Default Wall.001']} />
        <mesh name="ระดับหัวเสารับ_Truss001_4" geometry={nodes.ระดับหัวเสารับ_Truss001_4.geometry} material={materials['Brick, Common.001']} />
        <mesh name="ระดับหัวเสารับ_Truss001_5" geometry={nodes.ระดับหัวเสารับ_Truss001_5.geometry} material={materials.Steel} />
        <mesh name="ระดับหัวเสารับ_Truss001_6" geometry={nodes.ระดับหัวเสารับ_Truss001_6.geometry} material={materials['Glass.001']} />
        <mesh name="ระดับหัวเสารับ_Truss001_7" geometry={nodes.ระดับหัวเสารับ_Truss001_7.geometry} material={materials['Metal - Stainless Steel.001']} />
        <mesh name="ระดับหัวเสารับ_Truss001_8" geometry={nodes.ระดับหัวเสารับ_Truss001_8.geometry} material={materials['Door-wood-01.001']} />
        <mesh name="ระดับหัวเสารับ_Truss001_9" geometry={nodes.ระดับหัวเสารับ_Truss001_9.geometry} material={materials['Aluminum.001']} />
      </Select>
      <group name="EN107RF" position={[-2.733, 8.27, 0.093]} rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
        <mesh name="C3_025_x_050_m_steel_plate022" geometry={nodes.C3_025_x_050_m_steel_plate022.geometry} material={materials['Steel.001']} />
        <mesh name="C3_025_x_050_m_steel_plate022_1" geometry={nodes.C3_025_x_050_m_steel_plate022_1.geometry} material={materials['Steel, 45-345']} />
        <mesh name="C3_025_x_050_m_steel_plate022_2" geometry={nodes.C3_025_x_050_m_steel_plate022_2.geometry} material={materials['Steel ASTM A992']} />
        <mesh name="C3_025_x_050_m_steel_plate022_3" geometry={nodes.C3_025_x_050_m_steel_plate022_3.geometry} material={materials['Default Roof']} />
        <mesh name="C3_025_x_050_m_steel_plate022_4" geometry={nodes.C3_025_x_050_m_steel_plate022_4.geometry} material={materials['Roofs(1)']} />
        <mesh name="C3_025_x_050_m_steel_plate022_5" geometry={nodes.C3_025_x_050_m_steel_plate022_5.geometry} material={materials['Steel ASTM A36']} />
        <mesh name="C3_025_x_050_m_steel_plate022_6" geometry={nodes.C3_025_x_050_m_steel_plate022_6.geometry} material={materials['Gypsum Wall Board(1)']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/building/en107/en107.glb')
