/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/building/en202/en202-building.glb -t -k -E -R -f 
*/
"use client";

import * as THREE from "three";
import React, { useCallback, useEffect, useState } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useEN202Store } from "@/stores/use-building-store";
import { IFloorDetails } from "@/types/model";
import { getData } from "@/actions/actions";
import Link from "next/link";
import { Button } from "@/components/shadcn-ui/button";
import { ExternalLink } from "lucide-react";
import {
  Table,
  TableBody,
  TableCell,
  TableRow,
} from "@/components/shadcn-ui/table";
import { Select } from "@react-three/postprocessing";
import { getFloorActiveStatus } from "@/lib/utils";

type GLTFResult = GLTF & {
  nodes: {
    EN202B1_1: THREE.Mesh;
    EN202B1_2: THREE.Mesh;
    EN202B1_3: THREE.Mesh;
    EN202B1_4: THREE.Mesh;
    EN202B1_5: THREE.Mesh;
    EN202B1_6: THREE.Mesh;
    EN202B1_7: THREE.Mesh;
    EN202B1_8: THREE.Mesh;
    EN202B1_9: THREE.Mesh;
    EN20201_1: THREE.Mesh;
    EN20201_2: THREE.Mesh;
    EN20201_3: THREE.Mesh;
    EN20201_4: THREE.Mesh;
    EN20201_5: THREE.Mesh;
    EN20201_6: THREE.Mesh;
    EN20201_7: THREE.Mesh;
    EN20201_8: THREE.Mesh;
    EN20201_9: THREE.Mesh;
    EN20201_10: THREE.Mesh;
    EN20201_11: THREE.Mesh;
    EN20201_12: THREE.Mesh;
    EN20201_13: THREE.Mesh;
    EN20201_14: THREE.Mesh;
    EN202RF_1: THREE.Mesh;
    EN202RF_2: THREE.Mesh;
    Plane: THREE.Mesh;
  };
  materials: {
    ["สีขาว 247 (White 247)"]: THREE.MeshStandardMaterial;
    ["สีเทา 128 (White 128)"]: THREE.MeshStandardMaterial;
    ["Concrete, Cast-in-Place gray"]: THREE.MeshStandardMaterial;
    Glass: THREE.MeshStandardMaterial;
    ["Concrete, Normal Weight - 5 ksi"]: THREE.MeshStandardMaterial;
    ["สีขาว 247"]: THREE.MeshStandardMaterial;
    ["Stainless steel Matt"]: THREE.MeshStandardMaterial;
    Aluminum: THREE.MeshStandardMaterial;
    Default: THREE.MeshStandardMaterial;
    ["Steel, 45-345.002"]: THREE.MeshStandardMaterial;
    ["Black.001"]: THREE.MeshStandardMaterial;
    ["White 10Y9/0.001"]: THREE.MeshStandardMaterial;
    ["สีเทา 128 (White 128).002"]: THREE.MeshStandardMaterial;
    ["สีขาว 247 (White 247).003"]: THREE.MeshStandardMaterial;
    ["สีทราย.001"]: THREE.MeshStandardMaterial;
    ["Glass.002"]: THREE.MeshStandardMaterial;
    ["Default(1).001"]: THREE.MeshStandardMaterial;
    ["สีเทา 180 (White 180).001"]: THREE.MeshStandardMaterial;
    ["Stainless steel Matt.002"]: THREE.MeshStandardMaterial;
    ["Default.002"]: THREE.MeshStandardMaterial;
    ["สีขาว 247.002"]: THREE.MeshStandardMaterial;
    ["สีอิฐแดง.001"]: THREE.MeshStandardMaterial;
    ["โชว์หิน.001"]: THREE.MeshStandardMaterial;
    ["สีขาว 247 (White 247).004"]: THREE.MeshStandardMaterial;
    ["Concrete White.001"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

export const en202Floors = ["EN202B1", "EN20201"] as const;

export type EN202Floor = (typeof en202Floors)[number];

type Props = JSX.IntrinsicElements["group"] & {
  isManage: boolean;
};

export default function EN202Building(props: Props) {
  const { nodes, materials } = useGLTF(
    "/models/building/en202/en202-building.glb"
  ) as GLTFResult;
  const [hover, setHover] = useState<EN202Floor | null>(null);
  const { select, setSelect } = useEN202Store((state) => state);
  const [floorDetail, setFloorDetail] = useState<IFloorDetails | null>(null);

  const handleObjectHover = useCallback((object: EN202Floor | null) => {
    setHover(object);
  }, []);

  const handleObjectSelect = useCallback(
    (object: EN202Floor) => {
      setSelect(object);
    },
    [setSelect]
  );

  useEffect(() => {
    const fetchFloorDetail = async () => {
      const data = await getData(
        `buildingFloorDetail/${select?.toUpperCase()}`
      );
      setFloorDetail(data);
    };

    fetchFloorDetail();
  }, [select]);

  const renderModalDetail = (floorCode: string) => {
    const isFloorActive = getFloorActiveStatus(
      select?.substring(0, 5),
      select as string
    );
    // console.log("🚀 ~ renderModalDetail ~ isFloorActive:", isFloorActive)
    if (select === floorCode && !props.isManage) {
      return (
        <Html distanceFactor={60}>
          <div className="pt-[10px] transform translate-x-[80%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ชั้น ${floorCode.substring(5, 7)} - ${floorCode}`}
              </label>
              {isFloorActive && (
                <Link
                  href={`/floor/${floorCode.toUpperCase()}`}
                  target="_blank"
                >
                  <Button variant={"ghost"} size={"icon"}>
                    <ExternalLink className="size-5" />
                  </Button>
                </Link>
              )}
            </div>
            {renderFloorDetail()}
          </div>
        </Html>
      );
    }
  };

  const renderFloorDetail = () => {
    if (floorDetail) {
      return (
        <Table className="border rounded-md">
          <TableBody>
            <TableRow>
              <TableCell className="p-2">Building Code</TableCell>
              <TableCell className="p-2">
                {floorDetail?.buildingCode || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Floor</TableCell>
              <TableCell className="p-2">
                {floorDetail?.floorNumber || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Meter Energy</TableCell>
              <TableCell className="p-2">
                {floorDetail?.floorMeter || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Meter Power</TableCell>
              <TableCell className="p-2">
                {floorDetail?.floorPower || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Average PM 2.5</TableCell>
              <TableCell className="p-2">
                {floorDetail?.averagefloorPM25 || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Average Temperature</TableCell>
              <TableCell className="p-2">
                {floorDetail?.averagefloorTemp || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Average Humidity</TableCell>
              <TableCell className="p-2">
                {floorDetail?.averagefloorHumidity || "-"}
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      );
    }
  };

  return (
    <group {...props} dispose={null}>
      <Select
        name="EN202B1"
        enabled={hover === "EN202B1" || select === "EN202B1"}
        onPointerOver={(e) => {
          e.stopPropagation();
          handleObjectHover("EN202B1");
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          handleObjectHover(null);
        }}
        onClick={(e) => {
          e.stopPropagation();
          handleObjectSelect("EN202B1");
        }}
        position={[5.244, 0.756, 0.762]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      >
        {renderModalDetail("EN202B1")}
        <mesh
          name="EN202B1_1"
          geometry={nodes.EN202B1_1.geometry}
          material={materials["สีขาว 247 (White 247)"]}
        />
        <mesh
          name="EN202B1_2"
          geometry={nodes.EN202B1_2.geometry}
          material={materials["สีเทา 128 (White 128)"]}
        />
        <mesh
          name="EN202B1_3"
          geometry={nodes.EN202B1_3.geometry}
          material={materials["Concrete, Cast-in-Place gray"]}
        />
        <mesh
          name="EN202B1_4"
          geometry={nodes.EN202B1_4.geometry}
          material={materials.Glass}
        />
        <mesh
          name="EN202B1_5"
          geometry={nodes.EN202B1_5.geometry}
          material={materials["Concrete, Normal Weight - 5 ksi"]}
        />
        <mesh
          name="EN202B1_6"
          geometry={nodes.EN202B1_6.geometry}
          material={materials["สีขาว 247"]}
        />
        <mesh
          name="EN202B1_7"
          geometry={nodes.EN202B1_7.geometry}
          material={materials["Stainless steel Matt"]}
        />
        <mesh
          name="EN202B1_8"
          geometry={nodes.EN202B1_8.geometry}
          material={materials.Aluminum}
        />
        <mesh
          name="EN202B1_9"
          geometry={nodes.EN202B1_9.geometry}
          material={materials.Default}
        />
      </Select>
      <Select
        name="EN20201"
        enabled={hover === "EN20201" || select === "EN20201"}
        onPointerOver={(e) => {
          e.stopPropagation();
          handleObjectHover("EN20201");
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          handleObjectHover(null);
        }}
        onClick={(e) => {
          e.stopPropagation();
          handleObjectSelect("EN20201");
        }}
        position={[1.58, 2.766, 0.597]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      >
        {renderModalDetail("EN20201")}
        <mesh
          name="EN20201_1"
          geometry={nodes.EN20201_1.geometry}
          material={materials["Steel, 45-345.002"]}
        />
        <mesh
          name="EN20201_2"
          geometry={nodes.EN20201_2.geometry}
          material={materials["Black.001"]}
        />
        <mesh
          name="EN20201_3"
          geometry={nodes.EN20201_3.geometry}
          material={materials["White 10Y9/0.001"]}
        />
        <mesh
          name="EN20201_4"
          geometry={nodes.EN20201_4.geometry}
          material={materials["สีเทา 128 (White 128).002"]}
        />
        <mesh
          name="EN20201_5"
          geometry={nodes.EN20201_5.geometry}
          material={materials["สีขาว 247 (White 247).003"]}
        />
        <mesh
          name="EN20201_6"
          geometry={nodes.EN20201_6.geometry}
          material={materials["สีทราย.001"]}
        />
        <mesh
          name="EN20201_7"
          geometry={nodes.EN20201_7.geometry}
          material={materials["Glass.002"]}
        />
        <mesh
          name="EN20201_8"
          geometry={nodes.EN20201_8.geometry}
          material={materials["Default(1).001"]}
        />
        <mesh
          name="EN20201_9"
          geometry={nodes.EN20201_9.geometry}
          material={materials["สีเทา 180 (White 180).001"]}
        />
        <mesh
          name="EN20201_10"
          geometry={nodes.EN20201_10.geometry}
          material={materials["Stainless steel Matt.002"]}
        />
        <mesh
          name="EN20201_11"
          geometry={nodes.EN20201_11.geometry}
          material={materials["Default.002"]}
        />
        <mesh
          name="EN20201_12"
          geometry={nodes.EN20201_12.geometry}
          material={materials["สีขาว 247.002"]}
        />
        <mesh
          name="EN20201_13"
          geometry={nodes.EN20201_13.geometry}
          material={materials["สีอิฐแดง.001"]}
        />
        <mesh
          name="EN20201_14"
          geometry={nodes.EN20201_14.geometry}
          material={materials["โชว์หิน.001"]}
        />
      </Select>
      <group
        name="EN202RF"
        position={[0.903, 4.982, 0.69]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      >
        <mesh
          name="EN202RF_1"
          geometry={nodes.EN202RF_1.geometry}
          material={materials["สีขาว 247 (White 247).004"]}
        />
        <mesh
          name="EN202RF_2"
          geometry={nodes.EN202RF_2.geometry}
          material={materials["Concrete White.001"]}
        />
      </group>
      <mesh
        name="Plane"
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
        position={[5.208, 0.036, -86.701]}
        scale={[624.434, 0.657, 624.434]}
      />
    </group>
  );
}

useGLTF.preload("/models/building/en202/en202-building.glb");
