/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/building/en202/en202.glb -t -k -E -R -f 
*/
"use client"

import * as THREE from 'three'
import React, { useCallback, useEffect, useState } from 'react'
import { Html, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { IFloorDetails } from '@/types/model'
import { useEN202Store } from '@/stores/use-building-store'
import { Table, TableBody, TableCell, TableRow } from '@/components/shadcn-ui/table'
import { getData } from '@/actions/actions'
import { EN104Floor } from '../../en104/building/en104-building'
import { Button } from '@/components/shadcn-ui/button'
import { Select } from '@react-three/postprocessing'
import Link from 'next/link'
import { ExternalLink } from 'lucide-react'

type GLTFResult = GLTF & {
  nodes: {
    ระดับวางฐานเสากิ่งรับ: THREE.Mesh
    ระดับวางฐานเสากิ่งรับ_1: THREE.Mesh
    ระดับวางฐานเสากิ่งรับ_2: THREE.Mesh
    ระดับวางฐานเสากิ่งรับ_3: THREE.Mesh
    ระดับวางฐานเสากิ่งรับ_4: THREE.Mesh
    ระดับวางฐานเสากิ่งรับ_5: THREE.Mesh
    ระดับวางฐานเสากิ่งรับ_6: THREE.Mesh
    ระดับวางฐานเสากิ่งรับ_7: THREE.Mesh
    ระดับวางฐานเสากิ่งรับ_8: THREE.Mesh
    ['12,300__BTUHR_FXHQ32MAVS']: THREE.Mesh
    ['12,300__BTUHR_FXHQ32MAVS_1']: THREE.Mesh
    ['12,300__BTUHR_FXHQ32MAVS_2']: THREE.Mesh
    ['12,300__BTUHR_FXHQ32MAVS_3']: THREE.Mesh
    ['12,300__BTUHR_FXHQ32MAVS_4']: THREE.Mesh
    ['12,300__BTUHR_FXHQ32MAVS_5']: THREE.Mesh
    ['12,300__BTUHR_FXHQ32MAVS_6']: THREE.Mesh
    ['12,300__BTUHR_FXHQ32MAVS_7']: THREE.Mesh
    ['12,300__BTUHR_FXHQ32MAVS_8']: THREE.Mesh
    ['12,300__BTUHR_FXHQ32MAVS_9']: THREE.Mesh
    ['12,300__BTUHR_FXHQ32MAVS_10']: THREE.Mesh
    ['12,300__BTUHR_FXHQ32MAVS_11']: THREE.Mesh
    ['12,300__BTUHR_FXHQ32MAVS_12']: THREE.Mesh
    ['12,300__BTUHR_FXHQ32MAVS_13']: THREE.Mesh
    ['200_x_450mm_สีขาว']: THREE.Mesh
    ['200_x_450mm_สีขาว_1']: THREE.Mesh
  }
  materials: {
    ['สีขาว 247 (White 247)']: THREE.MeshStandardMaterial
    ['สีเทา 128 (White 128)']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray']: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['Concrete, Normal Weight - 5 ksi']: THREE.MeshStandardMaterial
    ['สีขาว 247']: THREE.MeshStandardMaterial
    ['Stainless steel Matt']: THREE.MeshStandardMaterial
    Aluminum: THREE.MeshStandardMaterial
    Default: THREE.MeshStandardMaterial
    ['Steel, 45-345.002']: THREE.MeshStandardMaterial
    ['Black.001']: THREE.MeshStandardMaterial
    ['White 10Y9/0.001']: THREE.MeshStandardMaterial
    ['สีเทา 128 (White 128).002']: THREE.MeshStandardMaterial
    ['สีขาว 247 (White 247).003']: THREE.MeshStandardMaterial
    ['สีทราย.001']: THREE.MeshStandardMaterial
    ['Glass.002']: THREE.MeshStandardMaterial
    ['Default(1).001']: THREE.MeshStandardMaterial
    ['สีเทา 180 (White 180).001']: THREE.MeshStandardMaterial
    ['Stainless steel Matt.002']: THREE.MeshStandardMaterial
    ['Default.002']: THREE.MeshStandardMaterial
    ['สีขาว 247.002']: THREE.MeshStandardMaterial
    ['สีอิฐแดง.001']: THREE.MeshStandardMaterial
    ['โชว์หิน.001']: THREE.MeshStandardMaterial
    ['สีขาว 247 (White 247).004']: THREE.MeshStandardMaterial
    ['Concrete White.001']: THREE.MeshStandardMaterial
  }
}

export const en202Floors = [
  "EN202B1",
  "EN20201",
] as const;

export type EN202Floor = typeof en202Floors[number];

type Props = JSX.IntrinsicElements["group"] & {
  isManage: boolean;
};

export default function EN202Building(props: Props) {
  const { nodes, materials } = useGLTF('/models/building/en202/en202.glb') as GLTFResult
  const [hover, setHover] = useState<EN202Floor | null>(null);
  const { select, setSelect } = useEN202Store(state => (state));
  const [floorDetail, setFloorDetail] = useState<IFloorDetails | null>(null);

  const handleObjectHover = useCallback((object: EN202Floor | null) => {
    setHover(object);
  }, []);

  const handleObjectSelect = useCallback((object: EN202Floor) => {
    setSelect(object);
  }, [setSelect]);

  useEffect(() => {
    const fetchFloorDetail = async () => {
      const data = await getData(`buildingFloorDetail/${select?.toUpperCase()}`);
      setFloorDetail(data);
    }

    fetchFloorDetail();
  }, [select]);

  const renderModalDetail = (floorCode: string) => {
    if (select === floorCode && !props.isManage) {
      return (
        <Html distanceFactor={60}>
          <div className="pt-[10px] transform translate-x-[80%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ชั้น ${floorCode.substring(5, 7)} - ${floorCode}`}
              </label>
              <Link href={`/floor/${floorCode.toUpperCase()}`} target="_blank">
                <Button variant={"ghost"} size={"icon"}>
                  <ExternalLink className="size-5" />
                </Button>
              </Link>
            </div>
            {renderFloorDetail()}
          </div>
        </Html>
      )
    }
  }

  const renderFloorDetail = () => {
    if (floorDetail) {
      return (
        <Table className="border rounded-md">
          <TableBody>
            <TableRow>
              <TableCell className="p-2">Building Code</TableCell>
              <TableCell className="p-2">
                {floorDetail?.buildingCode || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Floor</TableCell>
              <TableCell className="p-2">
                {floorDetail?.floorNumber || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Meter Energy</TableCell>
              <TableCell className="p-2">
                {floorDetail?.floorMeter || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Meter Power</TableCell>
              <TableCell className="p-2">
                {floorDetail?.floorPower || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Average PM 2.5</TableCell>
              <TableCell className="p-2">
                {floorDetail?.averagefloorPM25 || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Average Temperature</TableCell>
              <TableCell className="p-2">
                {floorDetail?.averagefloorTemp || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Average Humidity</TableCell>
              <TableCell className="p-2">
                {floorDetail?.averagefloorHumidity || "-"}
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      )
    }
  }

  return (
    <group {...props} dispose={null}>
      <Select
        name="EN202B1"
        enabled={hover === "EN202B1" || select === "EN202B1"}
        onPointerOver={() => {
          handleObjectHover("EN202B1");
        }}
        onPointerOut={() => {
          handleObjectHover(null);
        }}
        onClick={() => {
          handleObjectSelect("EN202B1");
        }}
        position={[6.639, 1.294, 0.197]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.305}
      >
        {renderModalDetail("EN202B1")}
        <mesh name="ระดับวางฐานเสากิ่งรับ" geometry={nodes.ระดับวางฐานเสากิ่งรับ.geometry} material={materials['สีขาว 247 (White 247)']} />
        <mesh name="ระดับวางฐานเสากิ่งรับ_1" geometry={nodes.ระดับวางฐานเสากิ่งรับ_1.geometry} material={materials['สีเทา 128 (White 128)']} />
        <mesh name="ระดับวางฐานเสากิ่งรับ_2" geometry={nodes.ระดับวางฐานเสากิ่งรับ_2.geometry} material={materials['Concrete, Cast-in-Place gray']} />
        <mesh name="ระดับวางฐานเสากิ่งรับ_3" geometry={nodes.ระดับวางฐานเสากิ่งรับ_3.geometry} material={materials.Glass} />
        <mesh name="ระดับวางฐานเสากิ่งรับ_4" geometry={nodes.ระดับวางฐานเสากิ่งรับ_4.geometry} material={materials['Concrete, Normal Weight - 5 ksi']} />
        <mesh name="ระดับวางฐานเสากิ่งรับ_5" geometry={nodes.ระดับวางฐานเสากิ่งรับ_5.geometry} material={materials['สีขาว 247']} />
        <mesh name="ระดับวางฐานเสากิ่งรับ_6" geometry={nodes.ระดับวางฐานเสากิ่งรับ_6.geometry} material={materials['Stainless steel Matt']} />
        <mesh name="ระดับวางฐานเสากิ่งรับ_7" geometry={nodes.ระดับวางฐานเสากิ่งรับ_7.geometry} material={materials.Aluminum} />
        <mesh name="ระดับวางฐานเสากิ่งรับ_8" geometry={nodes.ระดับวางฐานเสากิ่งรับ_8.geometry} material={materials.Default} />
      </Select>
      <Select
        name="EN20201"
        enabled={hover === "EN20201" || select === "EN20201"}
        onPointerOver={() => {
          handleObjectHover("EN20201");
        }}
        onPointerOut={() => {
          handleObjectHover(null);
        }}
        onClick={() => {
          handleObjectSelect("EN20201");
        }}
        position={[1.065, 4.352, -0.055]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.305}
      >
        {renderModalDetail("EN20201")}
        <mesh name="12,300__BTUHR_FXHQ32MAVS" geometry={nodes['12,300__BTUHR_FXHQ32MAVS'].geometry} material={materials['Steel, 45-345.002']} />
        <mesh name="12,300__BTUHR_FXHQ32MAVS_1" geometry={nodes['12,300__BTUHR_FXHQ32MAVS_1'].geometry} material={materials['Black.001']} />
        <mesh name="12,300__BTUHR_FXHQ32MAVS_2" geometry={nodes['12,300__BTUHR_FXHQ32MAVS_2'].geometry} material={materials['White 10Y9/0.001']} />
        <mesh name="12,300__BTUHR_FXHQ32MAVS_3" geometry={nodes['12,300__BTUHR_FXHQ32MAVS_3'].geometry} material={materials['สีเทา 128 (White 128).002']} />
        <mesh name="12,300__BTUHR_FXHQ32MAVS_4" geometry={nodes['12,300__BTUHR_FXHQ32MAVS_4'].geometry} material={materials['สีขาว 247 (White 247).003']} />
        <mesh name="12,300__BTUHR_FXHQ32MAVS_5" geometry={nodes['12,300__BTUHR_FXHQ32MAVS_5'].geometry} material={materials['สีทราย.001']} />
        <mesh name="12,300__BTUHR_FXHQ32MAVS_6" geometry={nodes['12,300__BTUHR_FXHQ32MAVS_6'].geometry} material={materials['Glass.002']} />
        <mesh name="12,300__BTUHR_FXHQ32MAVS_7" geometry={nodes['12,300__BTUHR_FXHQ32MAVS_7'].geometry} material={materials['Default(1).001']} />
        <mesh name="12,300__BTUHR_FXHQ32MAVS_8" geometry={nodes['12,300__BTUHR_FXHQ32MAVS_8'].geometry} material={materials['สีเทา 180 (White 180).001']} />
        <mesh name="12,300__BTUHR_FXHQ32MAVS_9" geometry={nodes['12,300__BTUHR_FXHQ32MAVS_9'].geometry} material={materials['Stainless steel Matt.002']} />
        <mesh name="12,300__BTUHR_FXHQ32MAVS_10" geometry={nodes['12,300__BTUHR_FXHQ32MAVS_10'].geometry} material={materials['Default.002']} />
        <mesh name="12,300__BTUHR_FXHQ32MAVS_11" geometry={nodes['12,300__BTUHR_FXHQ32MAVS_11'].geometry} material={materials['สีขาว 247.002']} />
        <mesh name="12,300__BTUHR_FXHQ32MAVS_12" geometry={nodes['12,300__BTUHR_FXHQ32MAVS_12'].geometry} material={materials['สีอิฐแดง.001']} />
        <mesh name="12,300__BTUHR_FXHQ32MAVS_13" geometry={nodes['12,300__BTUHR_FXHQ32MAVS_13'].geometry} material={materials['โชว์หิน.001']} />
      </Select>
      <group name="EN202RF" position={[0.034, 7.718, 0.087]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        <mesh name="200_x_450mm_สีขาว" geometry={nodes['200_x_450mm_สีขาว'].geometry} material={materials['สีขาว 247 (White 247).004']} />
        <mesh name="200_x_450mm_สีขาว_1" geometry={nodes['200_x_450mm_สีขาว_1'].geometry} material={materials['Concrete White.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/building/en202/en202.glb')
