/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/building/en110/en110-building.glb -t -k -E -R -f 
*/

"use client";

import * as THREE from "three";
import React, { useCallback, useEffect, useRef, useState } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useEN110Store } from "@/stores/use-building-store";
import { IFloorDetails } from "@/types/model";
import { getData } from "@/actions/actions";
import Link from "next/link";
import { Button } from "@/components/shadcn-ui/button";
import { ExternalLink } from "lucide-react";
import {
  Table,
  TableBody,
  TableCell,
  TableRow,
} from "@/components/shadcn-ui/table";
import { Select } from "@react-three/postprocessing";
import { getFloorActiveStatus } from "@/lib/utils";

type GLTFResult = GLTF & {
  nodes: {
    ['1-Gang_Outlet_General_Usage_19183_(1)']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_1']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_2']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_3']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_4']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_5']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_6']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_7']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_8']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_9']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_10']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_11']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_12']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_13']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_14']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_15']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_16']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_17']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_18']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_19']: THREE.Mesh
    ['1-Gang_Outlet_General_Usage_19183_(1)_20']: THREE.Mesh
    ['203x203x46UC']: THREE.Mesh
    ['203x203x46UC_1']: THREE.Mesh
    ['203x203x46UC_2']: THREE.Mesh
    ['203x203x46UC_3']: THREE.Mesh
    ['203x203x46UC_4']: THREE.Mesh
    ['203x203x46UC_5']: THREE.Mesh
    ['203x203x46UC_6']: THREE.Mesh
    ['203x203x46UC_7']: THREE.Mesh
    ['203x203x46UC_8']: THREE.Mesh
    ['203x203x46UC_9']: THREE.Mesh
    ['203x203x46UC_10']: THREE.Mesh
    ['203x203x46UC_11']: THREE.Mesh
    ['203x203x46UC_12']: THREE.Mesh
    ['203x203x46UC_13']: THREE.Mesh
    ['203x203x46UC_14']: THREE.Mesh
    ['203x203x46UC_15']: THREE.Mesh
    ['203x203x46UC_16']: THREE.Mesh
    ['203x203x46UC_17']: THREE.Mesh
    ['203x203x46UC_18']: THREE.Mesh
    ['203x203x46UC_19']: THREE.Mesh
    ['ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095']: THREE.Mesh
    ['ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095_1']: THREE.Mesh
    ['ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095_2']: THREE.Mesh
    ['ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095_3']: THREE.Mesh
    ['ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095_4']: THREE.Mesh
    ['ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095_5']: THREE.Mesh
    Plane: THREE.Mesh
  }
  materials: {
    ['Default Wall']: THREE.MeshStandardMaterial
    PVC: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete ขาว']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place ขาว']: THREE.MeshStandardMaterial
    ['Default Floor']: THREE.MeshStandardMaterial
    ['Default Floor สีขาว']: THREE.MeshStandardMaterial
    ['Concrete, Sand/Cement Screed']: THREE.MeshStandardMaterial
    ['Masonry.Stone.Granite.Square.Stacked.Polished.Mauve-Grey(2)']: THREE.MeshStandardMaterial
    ['Concrete, Cast In Situ. Marble Blue gray']: THREE.MeshStandardMaterial
    ['Default Wall(3) ขาว']: THREE.MeshStandardMaterial
    Rock01: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['Stainless steel matt (316)']: THREE.MeshStandardMaterial
    ['Aluminium Bronze Matt']: THREE.MeshStandardMaterial
    Default: THREE.MeshStandardMaterial
    ['Steel ASTM A36 สีดำ']: THREE.MeshStandardMaterial
    ['Steel, 45-345 สีดำ']: THREE.MeshStandardMaterial
    ['Wall ASA colour ขาว']: THREE.MeshStandardMaterial
    ['แกรนิต พื้น เทาสว่าง']: THREE.MeshStandardMaterial
    ['Masonry.Stone.Granite.Square.Stacked.Polished.Mauve-Grey']: THREE.MeshStandardMaterial
    ['Steel ASTM A36 สีส้ม']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place ขาว.001']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.001']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete ขาว.001']: THREE.MeshStandardMaterial
    ['Glass(1) orange']: THREE.MeshStandardMaterial
    ['Default Floor.001']: THREE.MeshStandardMaterial
    ['Concrete, Sand/Cement Screed.001']: THREE.MeshStandardMaterial
    ['Masonry.Stone.Granite.Square.Stacked.Polished.Mauve-Grey(2).001']: THREE.MeshStandardMaterial
    ['Laminate, Light Gray, Matte']: THREE.MeshStandardMaterial
    ['Default Wall(3) ขาว.001']: THREE.MeshStandardMaterial
    ['Default Wall.001']: THREE.MeshStandardMaterial
    ['Aluminium Bronze Matt.001']: THREE.MeshStandardMaterial
    ['Glass.001']: THREE.MeshStandardMaterial
    ['Stainless steel matt (316).001']: THREE.MeshStandardMaterial
    ['Default.001']: THREE.MeshStandardMaterial
    ['Steel ASTM A36 สีดำ.001']: THREE.MeshStandardMaterial
    ['Steel, 45-345 สีดำ.001']: THREE.MeshStandardMaterial
    ['Default Wall(3) สีขาว']: THREE.MeshStandardMaterial
    ['Steel, 45-345 ดำ(1)']: THREE.MeshStandardMaterial
    ['Masonry.Stone.Granite.Square.Stacked.Polished.Mauve-Grey.001']: THREE.MeshStandardMaterial
    ['Default Wall(3) ขาว.002']: THREE.MeshStandardMaterial
    ['Default Wall.002']: THREE.MeshStandardMaterial
    ['Roofs 2 - fsded lite gray']: THREE.MeshStandardMaterial
    Wood01: THREE.MeshStandardMaterial
    ['Metal Stud Layer']: THREE.MeshStandardMaterial
    ['Gypsum Wall Board']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export const en110Floors = ["EN11001", "EN11002"] as const;

export type EN110Floor = (typeof en110Floors)[number];

type Props = JSX.IntrinsicElements["group"] & {
  isManage: boolean;
};

export default function EN110Building(props: Props) {
  const { nodes, materials } = useGLTF('/models/building/en110/en110-building.glb') as GLTFResult

  const groupRef = useRef<any>();
  const [hover, setHover] = useState<EN110Floor | null>(null);
  const { select, setSelect } = useEN110Store((state) => state);
  const [floorDetail, setFloorDetail] = useState<IFloorDetails | null>(null);

  const handleObjectHover = useCallback((object: EN110Floor | null) => {
    setHover(object);
  }, []);

  const handleObjectSelect = useCallback(
    (object: EN110Floor) => {
      setSelect(object);
    },
    [setSelect]
  );

  useEffect(() => {
    const fetchFloorDetail = async () => {
      const data = await getData(
        `buildingFloorDetail/${select?.toUpperCase()}`, true
      );
      setFloorDetail(data);
    };

    fetchFloorDetail();
  }, [select]);

  const renderModalDetail = (floorCode: string) => {
    const isFloorActive = getFloorActiveStatus(
      select?.substring(0, 5),
      select as string
    );
    if (select === floorCode && !props.isManage) {
      return (
        <Html distanceFactor={40}>
          <div className="pt-[10px] transform translate-x-[80%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ชั้น ${floorCode.substring(5, 7)} - ${floorCode}`}
              </label>
              {isFloorActive && (
                <Link href={`/floor/${floorCode.toUpperCase()}`} target="_blank">
                  <Button variant={"ghost"} size={"icon"}>
                    <ExternalLink className="size-5" />
                  </Button>
                </Link>
              )}
            </div>
            {renderFloorDetail()}
          </div>
        </Html>
      );
    }
  };

  const renderFloorDetail = () => {
    return (
      <Table className="border rounded-md">
        <TableBody>
          <TableRow>
            <TableCell className="p-2">Building Code</TableCell>
            <TableCell className="p-2">
              {floorDetail?.buildingCode || select?.substring(0, 5)}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Floor</TableCell>
            <TableCell className="p-2">
              {floorDetail?.floorNumber || select?.substring(5, 7)}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Meter Energy</TableCell>
            <TableCell className="p-2">
              {floorDetail?.floorMeter ? floorDetail?.floorMeter : "-"}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Meter Power</TableCell>
            <TableCell className="p-2">
              {floorDetail?.floorPower ? floorDetail?.floorPower : "-"}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Average PM 2.5</TableCell>
            <TableCell className="p-2">
              {floorDetail?.averagefloorPM25 ? floorDetail?.averagefloorPM25 : "-"}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Average Temperature</TableCell>
            <TableCell className="p-2">
              {floorDetail?.averagefloorTemp ? floorDetail?.averagefloorTemp : "-"}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Average Humidity</TableCell>
            <TableCell className="p-2">
              {floorDetail?.averagefloorHumidity ? floorDetail?.averagefloorHumidity : "-"}
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    );
  };

  return (
    <group 
      onPointerOver={(e) => {
        e.stopPropagation();
        handleObjectHover(e.object.parent?.name as any);
      }} 
      onPointerOut={(e) => {
        e.stopPropagation();
        handleObjectHover(null)
      }}
      onClick={(e) => {
        e.stopPropagation();
        handleObjectSelect(e.object.parent?.name as any)
      }}
      ref={groupRef} 
      {...props} 
      dispose={null}
      position={[0, 0.5, 0]}
    >
      <Select name="EN11001" enabled={hover === "EN11001" || select === "EN11001"} position={[0.282, 1.695, -0.01]} rotation={[-Math.PI / 2, 0, -3.116]} scale={0.305}>
        {renderModalDetail("EN11001")}
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)'].geometry} material={materials['Default Wall']} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_1" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_1'].geometry} material={materials.PVC} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_2" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_2'].geometry} material={materials['Concrete, Cast-in-Place gray']} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_3" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_3'].geometry} material={materials['Concrete - Cast-in-Place Concrete ขาว']} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_4" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_4'].geometry} material={materials['Concrete, Cast-in-Place ขาว']} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_5" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_5'].geometry} material={materials['Default Floor']} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_6" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_6'].geometry} material={materials['Default Floor สีขาว']} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_7" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_7'].geometry} material={materials['Concrete, Sand/Cement Screed']} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_8" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_8'].geometry} material={materials['Masonry.Stone.Granite.Square.Stacked.Polished.Mauve-Grey(2)']} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_9" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_9'].geometry} material={materials['Concrete, Cast In Situ. Marble Blue gray']} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_10" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_10'].geometry} material={materials['Default Wall(3) ขาว']} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_11" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_11'].geometry} material={materials.Rock01} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_12" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_12'].geometry} material={materials.Glass} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_13" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_13'].geometry} material={materials['Stainless steel matt (316)']} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_14" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_14'].geometry} material={materials['Aluminium Bronze Matt']} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_15" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_15'].geometry} material={materials.Default} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_16" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_16'].geometry} material={materials['Steel ASTM A36 สีดำ']} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_17" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_17'].geometry} material={materials['Steel, 45-345 สีดำ']} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_18" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_18'].geometry} material={materials['Wall ASA colour ขาว']} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_19" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_19'].geometry} material={materials['แกรนิต พื้น เทาสว่าง']} />
        <mesh name="1-Gang_Outlet_General_Usage_19183_(1)_20" geometry={nodes['1-Gang_Outlet_General_Usage_19183_(1)_20'].geometry} material={materials['Masonry.Stone.Granite.Square.Stacked.Polished.Mauve-Grey']} />
      </Select>
      <Select name="EN11002" enabled={hover === "EN11002" || select === "EN11002"} position={[0.068, 5.402, -0.08]} rotation={[-Math.PI / 2, 0, -3.116]} scale={0.305}>
        {renderModalDetail("EN11002")}
        <mesh name="203x203x46UC" geometry={nodes['203x203x46UC'].geometry} material={materials['Steel ASTM A36 สีส้ม']} />
        <mesh name="203x203x46UC_1" geometry={nodes['203x203x46UC_1'].geometry} material={materials['Concrete, Cast-in-Place ขาว.001']} />
        <mesh name="203x203x46UC_2" geometry={nodes['203x203x46UC_2'].geometry} material={materials['Concrete, Cast-in-Place gray.001']} />
        <mesh name="203x203x46UC_3" geometry={nodes['203x203x46UC_3'].geometry} material={materials['Concrete - Cast-in-Place Concrete ขาว.001']} />
        <mesh name="203x203x46UC_4" geometry={nodes['203x203x46UC_4'].geometry} material={materials['Glass(1) orange']} />
        <mesh name="203x203x46UC_5" geometry={nodes['203x203x46UC_5'].geometry} material={materials['Default Floor.001']} />
        <mesh name="203x203x46UC_6" geometry={nodes['203x203x46UC_6'].geometry} material={materials['Concrete, Sand/Cement Screed.001']} />
        <mesh name="203x203x46UC_7" geometry={nodes['203x203x46UC_7'].geometry} material={materials['Masonry.Stone.Granite.Square.Stacked.Polished.Mauve-Grey(2).001']} />
        <mesh name="203x203x46UC_8" geometry={nodes['203x203x46UC_8'].geometry} material={materials['Laminate, Light Gray, Matte']} />
        <mesh name="203x203x46UC_9" geometry={nodes['203x203x46UC_9'].geometry} material={materials['Default Wall(3) ขาว.001']} />
        <mesh name="203x203x46UC_10" geometry={nodes['203x203x46UC_10'].geometry} material={materials['Default Wall.001']} />
        <mesh name="203x203x46UC_11" geometry={nodes['203x203x46UC_11'].geometry} material={materials['Aluminium Bronze Matt.001']} />
        <mesh name="203x203x46UC_12" geometry={nodes['203x203x46UC_12'].geometry} material={materials['Glass.001']} />
        <mesh name="203x203x46UC_13" geometry={nodes['203x203x46UC_13'].geometry} material={materials['Stainless steel matt (316).001']} />
        <mesh name="203x203x46UC_14" geometry={nodes['203x203x46UC_14'].geometry} material={materials['Default.001']} />
        <mesh name="203x203x46UC_15" geometry={nodes['203x203x46UC_15'].geometry} material={materials['Steel ASTM A36 สีดำ.001']} />
        <mesh name="203x203x46UC_16" geometry={nodes['203x203x46UC_16'].geometry} material={materials['Steel, 45-345 สีดำ.001']} />
        <mesh name="203x203x46UC_17" geometry={nodes['203x203x46UC_17'].geometry} material={materials['Default Wall(3) สีขาว']} />
        <mesh name="203x203x46UC_18" geometry={nodes['203x203x46UC_18'].geometry} material={materials['Steel, 45-345 ดำ(1)']} />
        <mesh name="203x203x46UC_19" geometry={nodes['203x203x46UC_19'].geometry} material={materials['Masonry.Stone.Granite.Square.Stacked.Polished.Mauve-Grey.001']} />
      </Select>
      <group name="EN110RF" position={[-0.057, 9.128, -0.002]} rotation={[-Math.PI / 2, 0, -3.116]} scale={0.305}>
        <mesh name="ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095" geometry={nodes['ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095'].geometry} material={materials['Default Wall(3) ขาว.002']} />
        <mesh name="ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095_1" geometry={nodes['ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095_1'].geometry} material={materials['Default Wall.002']} />
        <mesh name="ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095_2" geometry={nodes['ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095_2'].geometry} material={materials['Roofs 2 - fsded lite gray']} />
        <mesh name="ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095_3" geometry={nodes['ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095_3'].geometry} material={materials.Wood01} />
        <mesh name="ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095_4" geometry={nodes['ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095_4'].geometry} material={materials['Metal Stud Layer']} />
        <mesh name="ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095_5" geometry={nodes['ASA_Exterior_-_Brick_w_Finish_2_Sides_100mm_-ขาวน095_5'].geometry} material={materials['Gypsum Wall Board']} />
      </group>
      <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[76.543, 0.059, -29.001]} scale={[950, 1, 950]} />
    </group>
  )
}

useGLTF.preload('/models/building/en110/en110-building.glb')
