/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/building/en110/en110.glb -t -k -E -R -f 
*/
"use client";

import * as THREE from "three";
import React, { useCallback, useEffect, useRef, useState } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useEN101Store, useEN110Store } from "@/stores/use-building-store";
import { IFloorDetails } from "@/types/model";
import { getData } from "@/actions/actions";
import Link from "next/link";
import { Button } from "@/components/shadcn-ui/button";
import { ExternalLink } from "lucide-react";
import {
  Table,
  TableBody,
  TableCell,
  TableRow,
} from "@/components/shadcn-ui/table";
import { Select } from "@react-three/postprocessing";
import { getFloorActiveStatus } from "@/lib/utils";

type GLTFResult = GLTF & {
  nodes: {
    เก้าอี้_3: THREE.Mesh
    เก้าอี้_3_1: THREE.Mesh
    เก้าอี้_3_2: THREE.Mesh
    เก้าอี้_3_3: THREE.Mesh
    เก้าอี้001: THREE.Mesh
    เก้าอี้001_1: THREE.Mesh
    เก้าอี้001_2: THREE.Mesh
    เก้าอี้001_3: THREE.Mesh
    เก้าอี้001_4: THREE.Mesh
    เก้าอี้001_5: THREE.Mesh
    เก้าอี้001_6: THREE.Mesh
    เก้าอี้001_7: THREE.Mesh
    เก้าอี้001_8: THREE.Mesh
    เก้าอี้001_9: THREE.Mesh
    เก้าอี้001_10: THREE.Mesh
    ['เก้าอี้ระเบียง-8ม002']: THREE.Mesh
    ['เก้าอี้ระเบียง-8ม002_1']: THREE.Mesh
    ['เก้าอี้ระเบียง-8ม002_2']: THREE.Mesh
    ['เก้าอี้ระเบียง-8ม002_3']: THREE.Mesh
    ['เก้าอี้ระเบียง-8ม002_4']: THREE.Mesh
    ['เก้าอี้ระเบียง-8ม002_5']: THREE.Mesh
    ['เก้าอี้ระเบียง-8ม002_6']: THREE.Mesh
    ['เก้าอี้ระเบียง-8ม002_7']: THREE.Mesh
    ['เก้าอี้ระเบียง-8ม002_8']: THREE.Mesh
    ['เก้าอี้ระเบียง-8ม002_9']: THREE.Mesh
  }
  materials: {
    ['concrete cream']: THREE.MeshStandardMaterial
    ['Roofing, Tile']: THREE.MeshStandardMaterial
    steel: THREE.MeshStandardMaterial
    wood: THREE.MeshStandardMaterial
    ['concrete cream.001']: THREE.MeshStandardMaterial
    ['Concrete, Cast In Situ']: THREE.MeshStandardMaterial
    ['Steel, 45-345']: THREE.MeshStandardMaterial
    ['Door - Frame']: THREE.MeshStandardMaterial
    ['Door - Panel']: THREE.MeshStandardMaterial
    ['Clad - White']: THREE.MeshStandardMaterial
    ['Wood - Stained']: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['wood.001']: THREE.MeshStandardMaterial
    ['steel.001']: THREE.MeshStandardMaterial
    ['rock wall']: THREE.MeshStandardMaterial
    ['concrete cream.002']: THREE.MeshStandardMaterial
    ['Concrete, Cast In Situ.001']: THREE.MeshStandardMaterial
    ['Steel, 45-345.001']: THREE.MeshStandardMaterial
    ['Door - Frame.001']: THREE.MeshStandardMaterial
    ['Door - Panel.001']: THREE.MeshStandardMaterial
    ['Clad - White.001']: THREE.MeshStandardMaterial
    ['Wood - Stained.001']: THREE.MeshStandardMaterial
    ['Glass.001']: THREE.MeshStandardMaterial
    ['steel.002']: THREE.MeshStandardMaterial
    ['wood.002']: THREE.MeshStandardMaterial
  }
}

export const en110Floors = ["EN11001", "EN11002"] as const;

export type EN110Floor = (typeof en110Floors)[number];

type Props = JSX.IntrinsicElements["group"] & {
  isManage: boolean;
};

export default function EN110Building(props: Props) {
  const { nodes, materials } = useGLTF('/models/building/en110/en110.glb') as GLTFResult
  const groupRef = useRef<any>();
  const [hover, setHover] = useState<EN110Floor | null>(null);
  const { select, setSelect } = useEN110Store((state) => state);
  const [floorDetail, setFloorDetail] = useState<IFloorDetails | null>(null);

  const handleObjectHover = useCallback((object: EN110Floor | null) => {
    setHover(object);
  }, []);

  const handleObjectSelect = useCallback(
    (object: EN110Floor) => {
      setSelect(object);
    },
    [setSelect]
  );

  useEffect(() => {
    const fetchFloorDetail = async () => {
      const data = await getData(
        `buildingFloorDetail/${select?.toUpperCase()}`
      );
      setFloorDetail(data);
    };

    fetchFloorDetail();
  }, [select]);

  const renderModalDetail = (floorCode: string) => {
    const isFloorActive = getFloorActiveStatus(
      select?.substring(0, 5),
      select as string
    );
    if (select === floorCode && !props.isManage) {
      return (
        <Html distanceFactor={40}>
          <div className="pt-[10px] transform translate-x-[80%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ชั้น ${floorCode.substring(5, 7)} - ${floorCode}`}
              </label>
              {isFloorActive && (
                <Link href={`/floor/${floorCode.toUpperCase()}`} target="_blank">
                  <Button variant={"ghost"} size={"icon"}>
                    <ExternalLink className="size-5" />
                  </Button>
                </Link>
              )}
            </div>
            {renderFloorDetail()}
          </div>
        </Html>
      );
    }
  };

  const renderFloorDetail = () => {
    return (
      <Table className="border rounded-md">
        <TableBody>
          <TableRow>
            <TableCell className="p-2">Building Code</TableCell>
            <TableCell className="p-2">
              {floorDetail?.buildingCode || select?.substring(0, 5)}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Floor</TableCell>
            <TableCell className="p-2">
              {floorDetail?.floorNumber || select?.substring(5, 7)}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Meter Energy</TableCell>
            <TableCell className="p-2">
              {floorDetail?.floorMeter ? floorDetail?.floorMeter : "-"}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Meter Power</TableCell>
            <TableCell className="p-2">
              {floorDetail?.floorPower ? floorDetail?.floorPower : "-"}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Average PM 2.5</TableCell>
            <TableCell className="p-2">
              {floorDetail?.averagefloorPM25 ? floorDetail?.averagefloorPM25 : "-"}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Average Temperature</TableCell>
            <TableCell className="p-2">
              {floorDetail?.averagefloorTemp ? floorDetail?.averagefloorTemp : "-"}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="p-2">Average Humidity</TableCell>
            <TableCell className="p-2">
              {floorDetail?.averagefloorHumidity ? floorDetail?.averagefloorHumidity : "-"}
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    );
  };

  return (
    <group 
      onPointerOver={(e) => {
        e.stopPropagation();
        handleObjectHover(e.object.parent?.name as any);
      }} 
      onPointerOut={(e) => {
        e.stopPropagation();
        handleObjectHover(null)
      }}
      onClick={(e) => {
        e.stopPropagation();
        handleObjectSelect(e.object.parent?.name as any)
      }}
      ref={groupRef} 
      {...props} 
      dispose={null}
      position={[0, 0.5, 0]}
    >
      <group name="EN110RF" position={[-0.203, 4.514, 3.545]} rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
        <mesh name="เก้าอี้_3" geometry={nodes.เก้าอี้_3.geometry} material={materials['concrete cream']} />
        <mesh name="เก้าอี้_3_1" geometry={nodes.เก้าอี้_3_1.geometry} material={materials['Roofing, Tile']} />
        <mesh name="เก้าอี้_3_2" geometry={nodes.เก้าอี้_3_2.geometry} material={materials.steel} />
        <mesh name="เก้าอี้_3_3" geometry={nodes.เก้าอี้_3_3.geometry} material={materials.wood} />
      </group>
      <Select name="EN11001" enabled={hover === "EN11001" || select === "EN11001"} position={[-0.065, 1.692, -0.2]} rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
        {renderModalDetail("EN11001")}
        <mesh name="เก้าอี้001" geometry={nodes.เก้าอี้001.geometry} material={materials['concrete cream.001']} />
        <mesh name="เก้าอี้001_1" geometry={nodes.เก้าอี้001_1.geometry} material={materials['Concrete, Cast In Situ']} />
        <mesh name="เก้าอี้001_2" geometry={nodes.เก้าอี้001_2.geometry} material={materials['Steel, 45-345']} />
        <mesh name="เก้าอี้001_3" geometry={nodes.เก้าอี้001_3.geometry} material={materials['Door - Frame']} />
        <mesh name="เก้าอี้001_4" geometry={nodes.เก้าอี้001_4.geometry} material={materials['Door - Panel']} />
        <mesh name="เก้าอี้001_5" geometry={nodes.เก้าอี้001_5.geometry} material={materials['Clad - White']} />
        <mesh name="เก้าอี้001_6" geometry={nodes.เก้าอี้001_6.geometry} material={materials['Wood - Stained']} />
        <mesh name="เก้าอี้001_7" geometry={nodes.เก้าอี้001_7.geometry} material={materials.Glass} />
        <mesh name="เก้าอี้001_8" geometry={nodes.เก้าอี้001_8.geometry} material={materials['wood.001']} />
        <mesh name="เก้าอี้001_9" geometry={nodes.เก้าอี้001_9.geometry} material={materials['steel.001']} />
        <mesh name="เก้าอี้001_10" geometry={nodes.เก้าอี้001_10.geometry} material={materials['rock wall']} />
      </Select>
      <Select name="EN11002" enabled={hover === "EN11002" || select === "EN11002"} position={[-0.073, 4.456, 0.116]} rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
        {renderModalDetail("EN11002")}
        <mesh name="เก้าอี้ระเบียง-8ม002" geometry={nodes['เก้าอี้ระเบียง-8ม002'].geometry} material={materials['concrete cream.002']} />
        <mesh name="เก้าอี้ระเบียง-8ม002_1" geometry={nodes['เก้าอี้ระเบียง-8ม002_1'].geometry} material={materials['Concrete, Cast In Situ.001']} />
        <mesh name="เก้าอี้ระเบียง-8ม002_2" geometry={nodes['เก้าอี้ระเบียง-8ม002_2'].geometry} material={materials['Steel, 45-345.001']} />
        <mesh name="เก้าอี้ระเบียง-8ม002_3" geometry={nodes['เก้าอี้ระเบียง-8ม002_3'].geometry} material={materials['Door - Frame.001']} />
        <mesh name="เก้าอี้ระเบียง-8ม002_4" geometry={nodes['เก้าอี้ระเบียง-8ม002_4'].geometry} material={materials['Door - Panel.001']} />
        <mesh name="เก้าอี้ระเบียง-8ม002_5" geometry={nodes['เก้าอี้ระเบียง-8ม002_5'].geometry} material={materials['Clad - White.001']} />
        <mesh name="เก้าอี้ระเบียง-8ม002_6" geometry={nodes['เก้าอี้ระเบียง-8ม002_6'].geometry} material={materials['Wood - Stained.001']} />
        <mesh name="เก้าอี้ระเบียง-8ม002_7" geometry={nodes['เก้าอี้ระเบียง-8ม002_7'].geometry} material={materials['Glass.001']} />
        <mesh name="เก้าอี้ระเบียง-8ม002_8" geometry={nodes['เก้าอี้ระเบียง-8ม002_8'].geometry} material={materials['steel.002']} />
        <mesh name="เก้าอี้ระเบียง-8ม002_9" geometry={nodes['เก้าอี้ระเบียง-8ม002_9'].geometry} material={materials['wood.002']} />
      </Select>
    </group>
  )
}

useGLTF.preload('/models/building/en110/en110.glb')
