/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/building/en104/en104-1.glb -t -k -E -R -f 
*/
"use client"

import * as THREE from 'three'
import React, { useCallback, useEffect, useRef, useState } from 'react'
import { Html, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { usePathname } from 'next/navigation'
import { IModalRoomDetails } from '@/types/model'
import { useContourMenuStore } from '@/stores/use-menu-store'
import { configs } from '@/lib/configs'
import { useEN10401Store } from '@/stores/use-floor-store'
import { getData } from '@/actions/actions'
import Link from 'next/link'
import { Button } from '@/components/shadcn-ui/button'
import { ExternalLink } from 'lucide-react'
import { Table, TableBody, TableCell, TableRow } from '@/components/shadcn-ui/table'
import { Select } from '@react-three/postprocessing'

type GLTFResult = GLTF & {
  nodes: {
    ['B1_(3-3)_025_x_08_m']: THREE.Mesh
    ['B1_(3-3)_025_x_08_m_1']: THREE.Mesh
    ['B1_(3-3)_025_x_08_m_2']: THREE.Mesh
    ['B1_(3-3)_025_x_08_m_3']: THREE.Mesh
    ['B1_(3-3)_025_x_08_m_4']: THREE.Mesh
    ['B1_(3-3)_025_x_08_m_5']: THREE.Mesh
    ['B1_(2-2)_025_x_08_m']: THREE.Mesh
    ['B1_(2-2)_025_x_08_m_1']: THREE.Mesh
    ['B1_(2-2)_025_x_08_m_2']: THREE.Mesh
    ['B1_(2-2)_025_x_08_m_3']: THREE.Mesh
    ['B1_(2-2)_025_x_08_m_4']: THREE.Mesh
    ['B1_(2-2)_025_x_08_m_5']: THREE.Mesh
    ['B1_(2-2)_025_x_08_m_6']: THREE.Mesh
    ['B1_(2-2)_025_x_08_m_7']: THREE.Mesh
    C1_025_x_04_m021: THREE.Mesh
    C1_025_x_04_m021_1: THREE.Mesh
    C1_025_x_04_m021_2: THREE.Mesh
    C1_025_x_04_m021_3: THREE.Mesh
    C1_025_x_04_m021_4: THREE.Mesh
    C1_025_x_04_m021_5: THREE.Mesh
    C1_025_x_04_m021_6: THREE.Mesh
    C1_025_x_04_m021_7: THREE.Mesh
    C1_025_x_04_m021_8: THREE.Mesh
    ['1500mm']: THREE.Mesh
    ['1500mm_1']: THREE.Mesh
    ['1500mm_2']: THREE.Mesh
    ['1500mm_3']: THREE.Mesh
    ['1500mm_4']: THREE.Mesh
    ['1500mm_5']: THREE.Mesh
    ['1500mm_6']: THREE.Mesh
    ['50x25x25RHS']: THREE.Mesh
    ['50x25x25RHS_1']: THREE.Mesh
    ['50x25x25RHS_2']: THREE.Mesh
    ['50x25x25RHS_3']: THREE.Mesh
    ['50x25x25RHS_4']: THREE.Mesh
    ['50x25x25RHS_5']: THREE.Mesh
    ['50x25x25RHS_6']: THREE.Mesh
    ['50x25x25RHS_7']: THREE.Mesh
    ['50x25x25RHS_8']: THREE.Mesh
    ['50x25x25RHS_9']: THREE.Mesh
    ['50x25x25RHS_10']: THREE.Mesh
    ['50x25x25RHS_11']: THREE.Mesh
    ['50x25x25RHS_12']: THREE.Mesh
    ['50x25x25RHS_13']: THREE.Mesh
    ['50x25x25RHS_14']: THREE.Mesh
    ['50x25x25RHS_15']: THREE.Mesh
    ['50x25x25RHS_16']: THREE.Mesh
  }
  materials: {
    ['Concrete, Cast-in-Place gray']: THREE.MeshStandardMaterial
    ['Steel, Paint Finish, Ivory, Matte']: THREE.MeshStandardMaterial
    ['Wisawa-ruamjai-Front-coverway-white']: THREE.MeshStandardMaterial
    ['Default Wall']: THREE.MeshStandardMaterial
    ['Glass very light green']: THREE.MeshStandardMaterial
    ['Aluminium silver']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.001']: THREE.MeshStandardMaterial
    ['Plastic, Opaque White']: THREE.MeshStandardMaterial
    ['Wisawa-ruamjai-Front-coverway-white.001']: THREE.MeshStandardMaterial
    ['Default Wall.001']: THREE.MeshStandardMaterial
    ['Gypsum Wall Board']: THREE.MeshStandardMaterial
    ['Glass very light green.001']: THREE.MeshStandardMaterial
    ['Aluminium-silver']: THREE.MeshStandardMaterial
    ['Aluminium silver.001']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.002']: THREE.MeshStandardMaterial
    ['Plastic, Opaque White.001']: THREE.MeshStandardMaterial
    ['Wisawa-ruamjai-Front-coverway-white.002']: THREE.MeshStandardMaterial
    ['Default Wall.002']: THREE.MeshStandardMaterial
    ['Glass very light green.002']: THREE.MeshStandardMaterial
    ['Aluminium-silver.001']: THREE.MeshStandardMaterial
    ['Aluminium silver.002']: THREE.MeshStandardMaterial
    ['Color RGB 212-204-191']: THREE.MeshStandardMaterial
    ['Color RGB 040-040-040']: THREE.MeshStandardMaterial
    ['Default Wall.003']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.003']: THREE.MeshStandardMaterial
    ['Plastic, Opaque White.002']: THREE.MeshStandardMaterial
    ['Wisawa-ruamjai-Front-coverway-white.003']: THREE.MeshStandardMaterial
    ['Glass very light green.003']: THREE.MeshStandardMaterial
    ['Aluminium-silver.002']: THREE.MeshStandardMaterial
    ['Aluminium silver.003']: THREE.MeshStandardMaterial
    ['Steel, 45-345']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.004']: THREE.MeshStandardMaterial
    ['Plastic, Opaque White.003']: THREE.MeshStandardMaterial
    ['Glass-Gray01']: THREE.MeshStandardMaterial
    ['Metal Deck']: THREE.MeshStandardMaterial
    Granite: THREE.MeshStandardMaterial
    ['Wisawa-ruamjai-Front-coverway-white.004']: THREE.MeshStandardMaterial
    ['Default Wall.004']: THREE.MeshStandardMaterial
    ['Gypsum Wall Board.001']: THREE.MeshStandardMaterial
    ['Glass very light green.004']: THREE.MeshStandardMaterial
    ['Aluminium-silver.003']: THREE.MeshStandardMaterial
    ['Aluminium silver.004']: THREE.MeshStandardMaterial
    ['Steel, Paint Finish, Ivory, Matte.001']: THREE.MeshStandardMaterial
    ['Color RGB 212-204-191.001']: THREE.MeshStandardMaterial
    ['Color RGB 040-040-040.001']: THREE.MeshStandardMaterial
    ['Clear Toughened Glass']: THREE.MeshStandardMaterial
    ['Die-cast aluminium - Powder Coated in Black']: THREE.MeshStandardMaterial
  }
}

export const en104Floors01 = [
  "EN1040101", "EN1040102", "EN1040103", "EN1040104"
] as const;

export type EN104Floor1 = typeof en104Floors01[number];

type Props = JSX.IntrinsicElements["group"] & {
  isShowLamp?: boolean;
  isShowAir?: boolean;
  isManage?: boolean;
  isFloorPage?: boolean;
  isRoomPage?: boolean;
  roomData? : any[];
  pathname?: string;
  isFloorColorChange?: boolean;
  activeAirId?: string | null;
  activeLampId?: string | null;
};

export default function EN10401Floor(props: Props) {
  const {
    isShowLamp,
    isShowAir,
    isManage,
    isFloorPage,
    isRoomPage,
    roomData,
    pathname,
    isFloorColorChange,
    activeAirId,
    activeLampId,
  } = props;

  const groupRef = useRef<any>();
  const floorId = pathname;

  const path = usePathname();
  const roomId = path.split('/room/')[1];
  
  const { nodes, materials } = useGLTF('/models/building/en104/en104-1.glb') as GLTFResult

  const [hover, setHover] = useState<EN104Floor1 | null>(null);
  const { select, setSelect } = useEN10401Store(state => (state));
  const { menuState } = useContourMenuStore();
  const [modalFloorRoomDetail, setModalFloorRoomDetail] = useState<IModalRoomDetails | null>(null);
  const [modalRoomDetail, setModalRoomDetail] = useState<any>(null);
  const [modalLampDetail, setModalLampDetail] = useState<any>(null);
  const [modalAirDetail, setModalAirDetail] = useState<any>(null);

  const modalDistance = configs.building[roomId?.substring(0, 5).toLowerCase()]?.floor?.[roomId?.substring(0, 7).toLowerCase()]?.room?.[roomId?.toLowerCase()]?.modalDistance

  const handleObjectHover = useCallback((object: EN104Floor1 | null | any) => {
    setHover(object);
  }, []);

  const handleObjectSelect = useCallback(
    (object: EN104Floor1 | null | any, group: THREE.Group) => {
      setSelect(object);
    },
    [setSelect]
  );

  useEffect(() => {
    const floorContourColor = () => {
      if (!groupRef.current) return;
  
      groupRef.current.traverse((groupChild: any) => {
        if ((groupChild.isGroup || groupChild.type === 'Select') && !groupChild.name.includes('-')) {
          const roomData = props.roomData?.[groupChild.name];
  
          if (roomData && roomData.Humi_Temp_PM25) {
            // Calculate averages
            const sensors = Object.values(roomData.Humi_Temp_PM25) as Array<{
              Temp?: number;
              Humidity?: number;
              PM25?: number;
            }>;
  
            let averages: any = null;
            if (sensors.length > 1) {
              const total = sensors.reduce(
                (acc: { Temp: number; Humidity: number; PM25: number; count: number }, sensor) => {
                  acc.Temp += sensor.Temp || 0;
                  acc.Humidity += sensor.Humidity || 0;
                  acc.PM25 += sensor.PM25 || 0;
                  acc.count += 1;
                  return acc;
                },
                { Temp: 0, Humidity: 0, PM25: 0, count: 0 }
              );
  
              averages = {
                Temp: total.Temp / total.count,
                Humidity: total.Humidity / total.count,
                PM25: total.PM25 / total.count,
              };
            } else if (sensors.length === 1) {
              const sensor = sensors[0];
              averages = {
                Temp: sensor.Temp || 0,
                Humidity: sensor.Humidity || 0,
                PM25: sensor.PM25 || 0,
              };
            }
  
            if (averages) {
              // console.log(`Averages for ${groupChild.name}:`, averages);
  
              // Handle menuState
              if (menuState === null) {
                // Reset to original color
                groupChild.traverse((meshChild: any) => {
                  if (meshChild.isMesh || meshChild.isInstancedMesh) {
                    if (meshChild.material) {
                      if (Array.isArray(meshChild.material)) {
                        meshChild.material.forEach((mat: any) => {
                          if (mat.userData.originalColor) {
                            mat.color.set(mat.userData.originalColor);
                            mat.needsUpdate = true;
                          }
                        });
                      } else {
                        if (meshChild.material.userData.originalColor) {
                          meshChild.material.color.set(meshChild.material.userData.originalColor);
                          meshChild.material.needsUpdate = true;
                        }
                      }
                    }
                  }
                });
              } else {
                // Process PM2.5, Humidity, or Temperature
                const processState = (value: number, scale: any, groupName: string) => {
                  const normalizedValue = Math.max(0, Math.min(value, 1));
                  const color = getColorFromScale(normalizedValue, scale);
  
                  groupChild.traverse((meshChild: any) => {
                    if (meshChild.isMesh || meshChild.isInstancedMesh) {
                      if (
                        meshChild.material &&
                        (meshChild.material.name?.includes('Concrete, Cast-in-Place gray'))
                      ) {
                        // Save original color if not saved yet
                        if (!meshChild.material.userData.originalColor) {
                          meshChild.material.userData.originalColor = meshChild.material.color.getHex();
                        }
  
                        // Set new color
                        if (Array.isArray(meshChild.material)) {
                          meshChild.material.forEach((mat: any) => {
                            mat.color.set(color);
                            mat.needsUpdate = true;
                          });
                        } else {
                          meshChild.material.color.set(color);
                          meshChild.material.needsUpdate = true;
                        }
  
                        // console.log(`Changed color for ${meshChild.name} in ${groupName}`);
                      }
                    }
                  });
                };
  
                if (menuState === 'pm25') {
                  const pm25Value = averages.PM25 || 0;
                  processState(pm25Value / 600, configs.colorScale.pm25, groupChild.name);
                } else if (menuState === 'humidity') {
                  const humidityValue = averages.Humidity || 0;
                  processState(humidityValue / 100, configs.colorScale.humidity, groupChild.name);
                } else if (menuState === 'temperature') {
                  const tempValue = averages.Temp || 0;
                  processState(tempValue / 50, configs.colorScale.temperature, groupChild.name);
                }
              }
            }
          }
        }
      });
    };
  
    floorContourColor();
  }, [roomData, menuState]);

  useEffect(() => {
    const changeFloorColor = () => {
      if (!groupRef.current || !isFloorColorChange) return;
  
      groupRef.current.traverse((groupChild: any) => {
        groupChild.traverse((meshChild: any) => {
          if (meshChild.isMesh || meshChild.isInstancedMesh) {
            if (
              meshChild.material &&
              (meshChild.material.name?.includes('Concrete, Cast-in-Place gray'))
            ) {
              // Save original color if not saved yet
              if (!meshChild.material.userData.originalColor) {
                meshChild.material.userData.originalColor = meshChild.material.color.getHex();
              }
  
              // Change to gray color
              const grayColor = 0x959595; // Hex for gray
              if (Array.isArray(meshChild.material)) {
                meshChild.material.forEach((mat: any) => {
                  mat.color.set(grayColor);
                  mat.needsUpdate = true;
                });
              } else {
                meshChild.material.color.set(grayColor);
                meshChild.material.needsUpdate = true;
              }
            }
          }
        });
      });
    };
    changeFloorColor();
  }, [isFloorColorChange]);

  const getColorFromScale = (value: number, scale: Array<[number, string]>) => {
    for (let i = 0; i < scale.length - 1; i++) {
      const [start, startColor] = scale[i];
      const [end, endColor] = scale[i + 1];
  
      if (value >= start && value <= end) {
        const ratio = (value - start) / (end - start);
        return interpolateColor(startColor, endColor, ratio);
      }
    }
    return scale[scale.length - 1][1];
  };

  const interpolateColor = (color1: string, color2: string, ratio: number) => {
    const hexToRgb = (hex: string) =>
      hex
        .replace(/^#/, "")
        .match(/.{2}/g)
        ?.map((x) => parseInt(x, 16)) || [0, 0, 0];
  
    const rgbToHex = (rgb: number[]) =>
      `#${rgb.map((x) => x.toString(16).padStart(2, "0")).join("")}`;
  
    const rgb1 = hexToRgb(color1);
    const rgb2 = hexToRgb(color2);
  
    const interpolatedRgb = rgb1.map((c, i) => Math.round(c + (rgb2[i] - c) * ratio));
  
    return rgbToHex(interpolatedRgb);
  };

  useEffect(() => {
    const fetchFloorRoomDetail = async () => {
      if (isRoomPage) {
        if (select?.includes("L")) {
          const formattedSelect = select.replace("-", "");
          const lampData = await getData(`getLampById/${formattedSelect.toUpperCase()}`);
          setModalLampDetail(lampData);
        } else if (select?.includes("A")) {
          const formattedSelect = select.replace("-", "");
          const airData = await getData(`getAirById/${formattedSelect.toUpperCase()}`);
          setModalAirDetail(airData[0]);
        } else {
          const roomData = await getData(`roomDetail/${select?.toUpperCase()}`);
          setModalRoomDetail(roomData);
        }
      } else {
        const floorRoomData = await getData(`floorRoomDetail/${select?.toUpperCase()}`);
        setModalFloorRoomDetail(floorRoomData);
      }
    }

    fetchFloorRoomDetail();
  }, [select]);

  const renderModalDetail = (roomCode: string) => {
    if (select === roomCode && !isManage) {
      return (
        <Html distanceFactor={50}>
          <div className="pt-[10px] transform z-0 translate-x-[30%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ห้อง ${roomCode.substring(6, 9)} - ${roomCode}`}
              </label>
              <Link href={`/room/${roomCode.toUpperCase()}`} target="_blank">
                <Button variant={"ghost"} size={"icon"}>
                  <ExternalLink className="size-5" />
                </Button>
              </Link>
            </div>
            <Table className="border rounded-md">
              <TableBody>
                <TableRow>
                  <TableCell className="p-2">Building Code</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.buildingCode || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Floor</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.floorNumber || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Room</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.roomNumber || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Energy</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.roomMeter || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Power</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.roomPower || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average PM 2.5</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.averagePM25 || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Temperature</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.averageTemp ? `${modalFloorRoomDetail?.averageTemp} °C` : "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Humidity</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.averageHumidity ? `${modalFloorRoomDetail?.averageHumidity} %` : "-"}
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </Html>
      )
    }
  }

  const renderModalRoomDetail = (roomCode: string) => {
    if (select === roomCode && select === roomId?.toUpperCase() && !isManage) {
      return (
        <Html distanceFactor={modalDistance || 20}>
          <div className="pt-[10px] transform z-0 translate-x-[30%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ห้อง ${roomCode.substring(6, 9)} - ${roomCode}`}
              </label>
            </div>
            <Table className="border rounded-md">
              <TableBody>
                <TableRow>
                  <TableCell className="p-2">Building Code</TableCell>
                  <TableCell className="p-2">
                    {roomCode.substring(0, 5) || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Floor</TableCell>
                  <TableCell className="p-2">
                    {roomCode.substring(5, 7) || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Room</TableCell>
                  <TableCell className="p-2">
                    {roomCode.substring(6, 9) || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Number of Air Conditioners</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.airStatus?.length as number || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Number of Lamps</TableCell>
                  <TableCell className="p-2">
                    {
                      configs.building[roomId.substring(0, 5).toLowerCase()]?.floor?.[roomId.substring(0, 7).toLowerCase()]?.room?.[roomId.toLowerCase()]
                      ?.lampCount || "-"
                    }
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Energy</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomMeter || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Power</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomPower || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average PM 2.5</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomPM25 || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Temperature</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomTemp ? `${modalRoomDetail?.roomTemp} °C` : "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Humidity</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomHumidity ? `${modalRoomDetail?.roomHumidity} %` : "-"}
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </Html>
      )
    }
  }
  
  return (
    <group 
      onPointerOver={(e) => {
        e.stopPropagation();
        handleObjectHover(e.object.parent?.name);
      }} 
      onPointerOut={(e) => {
        e.stopPropagation();
        handleObjectHover(null)
      }}
      onClick={(e) => {
        e.stopPropagation();
        handleObjectSelect(e.object.parent?.name, e.object.parent as THREE.Group)
      }}
      ref={groupRef} 
      {...props} 
      dispose={null}
      position={[0, 0.5, 0]}
    >
      <Select name="EN1040101" enabled={hover === "EN1040101" || select === "EN1040101"} position={[-15.511, 1.809, -2.847]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1040101")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1040101")}
        <mesh name="B1_(3-3)_025_x_08_m" geometry={nodes['B1_(3-3)_025_x_08_m'].geometry} material={materials['Concrete, Cast-in-Place gray']} />
        <mesh name="B1_(3-3)_025_x_08_m_1" geometry={nodes['B1_(3-3)_025_x_08_m_1'].geometry} material={materials['Steel, Paint Finish, Ivory, Matte']} />
        <mesh name="B1_(3-3)_025_x_08_m_2" geometry={nodes['B1_(3-3)_025_x_08_m_2'].geometry} material={materials['Wisawa-ruamjai-Front-coverway-white']} />
        <mesh name="B1_(3-3)_025_x_08_m_3" geometry={nodes['B1_(3-3)_025_x_08_m_3'].geometry} material={materials['Default Wall']} />
        <mesh name="B1_(3-3)_025_x_08_m_4" geometry={nodes['B1_(3-3)_025_x_08_m_4'].geometry} material={materials['Glass very light green']} />
        <mesh name="B1_(3-3)_025_x_08_m_5" geometry={nodes['B1_(3-3)_025_x_08_m_5'].geometry} material={materials['Aluminium silver']} />
      </Select>
      <Select name="EN1040102" enabled={hover === "EN1040102" || select === "EN1040102"} position={[-7.637, 1.598, -0.686]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1040102")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1040102")}
        <mesh name="B1_(2-2)_025_x_08_m" geometry={nodes['B1_(2-2)_025_x_08_m'].geometry} material={materials['Concrete, Cast-in-Place gray.001']} />
        <mesh name="B1_(2-2)_025_x_08_m_1" geometry={nodes['B1_(2-2)_025_x_08_m_1'].geometry} material={materials['Plastic, Opaque White']} />
        <mesh name="B1_(2-2)_025_x_08_m_2" geometry={nodes['B1_(2-2)_025_x_08_m_2'].geometry} material={materials['Wisawa-ruamjai-Front-coverway-white.001']} />
        <mesh name="B1_(2-2)_025_x_08_m_3" geometry={nodes['B1_(2-2)_025_x_08_m_3'].geometry} material={materials['Default Wall.001']} />
        <mesh name="B1_(2-2)_025_x_08_m_4" geometry={nodes['B1_(2-2)_025_x_08_m_4'].geometry} material={materials['Gypsum Wall Board']} />
        <mesh name="B1_(2-2)_025_x_08_m_5" geometry={nodes['B1_(2-2)_025_x_08_m_5'].geometry} material={materials['Glass very light green.001']} />
        <mesh name="B1_(2-2)_025_x_08_m_6" geometry={nodes['B1_(2-2)_025_x_08_m_6'].geometry} material={materials['Aluminium-silver']} />
        <mesh name="B1_(2-2)_025_x_08_m_7" geometry={nodes['B1_(2-2)_025_x_08_m_7'].geometry} material={materials['Aluminium silver.001']} />
      </Select>
      <Select name="EN1040103" enabled={hover === "EN1040103" || select === "EN1040103"} position={[9.847, 1.525, -0.687]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1040103")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1040103")}
        <mesh name="C1_025_x_04_m021" geometry={nodes.C1_025_x_04_m021.geometry} material={materials['Concrete, Cast-in-Place gray.002']} />
        <mesh name="C1_025_x_04_m021_1" geometry={nodes.C1_025_x_04_m021_1.geometry} material={materials['Plastic, Opaque White.001']} />
        <mesh name="C1_025_x_04_m021_2" geometry={nodes.C1_025_x_04_m021_2.geometry} material={materials['Wisawa-ruamjai-Front-coverway-white.002']} />
        <mesh name="C1_025_x_04_m021_3" geometry={nodes.C1_025_x_04_m021_3.geometry} material={materials['Default Wall.002']} />
        <mesh name="C1_025_x_04_m021_4" geometry={nodes.C1_025_x_04_m021_4.geometry} material={materials['Glass very light green.002']} />
        <mesh name="C1_025_x_04_m021_5" geometry={nodes.C1_025_x_04_m021_5.geometry} material={materials['Aluminium-silver.001']} />
        <mesh name="C1_025_x_04_m021_6" geometry={nodes.C1_025_x_04_m021_6.geometry} material={materials['Aluminium silver.002']} />
        <mesh name="C1_025_x_04_m021_7" geometry={nodes.C1_025_x_04_m021_7.geometry} material={materials['Color RGB 212-204-191']} />
        <mesh name="C1_025_x_04_m021_8" geometry={nodes.C1_025_x_04_m021_8.geometry} material={materials['Color RGB 040-040-040']} />
      </Select>
      <Select name="EN1040104" enabled={hover === "EN1040104" || select === "EN1040104"} position={[16.182, 1.596, -0.633]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1040104")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1040104")}
        <mesh name="1500mm" geometry={nodes['1500mm'].geometry} material={materials['Default Wall.003']} />
        <mesh name="1500mm_1" geometry={nodes['1500mm_1'].geometry} material={materials['Concrete, Cast-in-Place gray.003']} />
        <mesh name="1500mm_2" geometry={nodes['1500mm_2'].geometry} material={materials['Plastic, Opaque White.002']} />
        <mesh name="1500mm_3" geometry={nodes['1500mm_3'].geometry} material={materials['Wisawa-ruamjai-Front-coverway-white.003']} />
        <mesh name="1500mm_4" geometry={nodes['1500mm_4'].geometry} material={materials['Glass very light green.003']} />
        <mesh name="1500mm_5" geometry={nodes['1500mm_5'].geometry} material={materials['Aluminium-silver.002']} />
        <mesh name="1500mm_6" geometry={nodes['1500mm_6'].geometry} material={materials['Aluminium silver.003']} />
      </Select>
      <group name="EN1040199" position={[-0.913, 1.254, 0.369]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        <mesh name="50x25x25RHS" geometry={nodes['50x25x25RHS'].geometry} material={materials['Steel, 45-345']} />
        <mesh name="50x25x25RHS_1" geometry={nodes['50x25x25RHS_1'].geometry} material={materials['Concrete, Cast-in-Place gray.004']} />
        <mesh name="50x25x25RHS_2" geometry={nodes['50x25x25RHS_2'].geometry} material={materials['Plastic, Opaque White.003']} />
        <mesh name="50x25x25RHS_3" geometry={nodes['50x25x25RHS_3'].geometry} material={materials['Glass-Gray01']} />
        <mesh name="50x25x25RHS_4" geometry={nodes['50x25x25RHS_4'].geometry} material={materials['Metal Deck']} />
        <mesh name="50x25x25RHS_5" geometry={nodes['50x25x25RHS_5'].geometry} material={materials.Granite} />
        <mesh name="50x25x25RHS_6" geometry={nodes['50x25x25RHS_6'].geometry} material={materials['Wisawa-ruamjai-Front-coverway-white.004']} />
        <mesh name="50x25x25RHS_7" geometry={nodes['50x25x25RHS_7'].geometry} material={materials['Default Wall.004']} />
        <mesh name="50x25x25RHS_8" geometry={nodes['50x25x25RHS_8'].geometry} material={materials['Gypsum Wall Board.001']} />
        <mesh name="50x25x25RHS_9" geometry={nodes['50x25x25RHS_9'].geometry} material={materials['Glass very light green.004']} />
        <mesh name="50x25x25RHS_10" geometry={nodes['50x25x25RHS_10'].geometry} material={materials['Aluminium-silver.003']} />
        <mesh name="50x25x25RHS_11" geometry={nodes['50x25x25RHS_11'].geometry} material={materials['Aluminium silver.004']} />
        <mesh name="50x25x25RHS_12" geometry={nodes['50x25x25RHS_12'].geometry} material={materials['Steel, Paint Finish, Ivory, Matte.001']} />
        <mesh name="50x25x25RHS_13" geometry={nodes['50x25x25RHS_13'].geometry} material={materials['Color RGB 212-204-191.001']} />
        <mesh name="50x25x25RHS_14" geometry={nodes['50x25x25RHS_14'].geometry} material={materials['Color RGB 040-040-040.001']} />
        <mesh name="50x25x25RHS_15" geometry={nodes['50x25x25RHS_15'].geometry} material={materials['Clear Toughened Glass']} />
        <mesh name="50x25x25RHS_16" geometry={nodes['50x25x25RHS_16'].geometry} material={materials['Die-cast aluminium - Powder Coated in Black']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/building/en104/en104-1.glb')
