/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/building/en120/en120-1.glb -t -k -E -R -f 
*/
"use client"

import * as THREE from 'three'
import React, { useCallback, useEffect, useRef, useState } from 'react'
import { Html, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { usePathname } from 'next/navigation'
import { IModalRoomDetails } from '@/types/model'
import { useContourMenuStore } from '@/stores/use-menu-store'
import { configs } from '@/lib/configs'
import { useEN12001Store } from '@/stores/use-floor-store'
import { getData } from '@/actions/actions'
import Link from 'next/link'
import { Button } from '@/components/shadcn-ui/button'
import { ExternalLink } from 'lucide-react'
import { Table, TableBody, TableCell, TableRow } from '@/components/shadcn-ui/table'
import { Select } from '@react-three/postprocessing'
import { getColorFromScale } from '@/lib/utils'

type GLTFResult = GLTF & {
  nodes: {
    EN1200101_1: THREE.Mesh
    EN1200101_2: THREE.Mesh
    EN1200101_3: THREE.Mesh
    EN1200101_4: THREE.Mesh
    EN1200101_5: THREE.Mesh
    EN1200101_6: THREE.Mesh
    EN1200101_7: THREE.Mesh
    EN1200101_8: THREE.Mesh
    EN1200101_9: THREE.Mesh
    EN1200101_10: THREE.Mesh
    EN1200101_11: THREE.Mesh
    EN1200101_12: THREE.Mesh
    EN1200102_1: THREE.Mesh
    EN1200102_2: THREE.Mesh
    EN1200102_3: THREE.Mesh
    EN1200102_4: THREE.Mesh
    EN1200102_5: THREE.Mesh
    EN1200102_6: THREE.Mesh
    EN1200102_7: THREE.Mesh
    EN1200102_8: THREE.Mesh
    EN1200102_9: THREE.Mesh
    EN1200102_10: THREE.Mesh
    EN1200102_11: THREE.Mesh
    EN1200102_12: THREE.Mesh
    EN1200103_1: THREE.Mesh
    EN1200103_2: THREE.Mesh
    EN1200103_3: THREE.Mesh
    EN1200103_4: THREE.Mesh
    EN1200103_5: THREE.Mesh
    EN1200103_6: THREE.Mesh
    EN1200103_7: THREE.Mesh
    EN1200103_8: THREE.Mesh
    EN1200103_9: THREE.Mesh
    EN1200103_10: THREE.Mesh
    EN1200103_11: THREE.Mesh
    EN1200103_12: THREE.Mesh
    EN1200103_13: THREE.Mesh
    EN1200103_14: THREE.Mesh
    EN1200103_15: THREE.Mesh
    EN1200103_16: THREE.Mesh
    EN1200103_17: THREE.Mesh
    EN1200103_18: THREE.Mesh
    EN1200103_19: THREE.Mesh
    EN1200104_1: THREE.Mesh
    EN1200104_2: THREE.Mesh
    EN1200104_3: THREE.Mesh
    EN1200104_4: THREE.Mesh
    EN1200104_5: THREE.Mesh
    EN1200104_6: THREE.Mesh
    EN1200104_7: THREE.Mesh
    EN1200104_8: THREE.Mesh
    EN1200104_9: THREE.Mesh
    EN1200104_10: THREE.Mesh
    EN1200105_1: THREE.Mesh
    EN1200105_2: THREE.Mesh
    EN1200105_3: THREE.Mesh
    EN1200105_4: THREE.Mesh
    EN1200105_5: THREE.Mesh
    EN1200105_6: THREE.Mesh
    EN1200105_7: THREE.Mesh
    EN1200105_8: THREE.Mesh
    EN1200105_9: THREE.Mesh
    EN1200106_1: THREE.Mesh
    EN1200106_2: THREE.Mesh
    EN1200106_3: THREE.Mesh
    EN1200106_4: THREE.Mesh
    EN1200106_5: THREE.Mesh
    EN1200106_6: THREE.Mesh
    EN1200106_7: THREE.Mesh
    EN1200106_8: THREE.Mesh
    EN1200106_9: THREE.Mesh
    EN1200107_1: THREE.Mesh
    EN1200107_2: THREE.Mesh
    EN1200107_3: THREE.Mesh
    EN1200107_4: THREE.Mesh
    EN1200107_5: THREE.Mesh
    EN1200107_6: THREE.Mesh
    EN1200107_7: THREE.Mesh
    EN1200107_8: THREE.Mesh
    EN1200107_9: THREE.Mesh
    EN1200107_10: THREE.Mesh
    EN1200107_11: THREE.Mesh
    EN1200107_12: THREE.Mesh
    EN1200107_13: THREE.Mesh
    EN1200108_1: THREE.Mesh
    EN1200108_2: THREE.Mesh
    EN1200108_3: THREE.Mesh
    EN1200108_4: THREE.Mesh
    EN1200108_5: THREE.Mesh
    EN1200108_6: THREE.Mesh
    EN1200108_7: THREE.Mesh
    EN1200109_1: THREE.Mesh
    EN1200109_2: THREE.Mesh
    EN1200109_3: THREE.Mesh
    EN1200109_4: THREE.Mesh
    EN1200109_5: THREE.Mesh
    EN1200109_6: THREE.Mesh
    EN1200109_7: THREE.Mesh
    EN1200110_1: THREE.Mesh
    EN1200110_2: THREE.Mesh
    EN1200110_3: THREE.Mesh
    EN1200110_4: THREE.Mesh
    EN1200110_5: THREE.Mesh
    EN1200110_6: THREE.Mesh
    EN1200110_7: THREE.Mesh
    EN1200111_1: THREE.Mesh
    EN1200111_2: THREE.Mesh
    EN1200111_3: THREE.Mesh
    EN1200111_4: THREE.Mesh
    EN1200111_5: THREE.Mesh
    EN1200111_6: THREE.Mesh
    EN1200111_7: THREE.Mesh
    EN1200111_8: THREE.Mesh
    EN1200111_9: THREE.Mesh
    EN1200111_10: THREE.Mesh
    EN1200111_11: THREE.Mesh
    EN1200112_1: THREE.Mesh
    EN1200112_2: THREE.Mesh
    EN1200112_3: THREE.Mesh
    EN1200112_4: THREE.Mesh
    EN1200112_5: THREE.Mesh
    EN1200112_6: THREE.Mesh
    EN1200112_7: THREE.Mesh
    EN1200112_8: THREE.Mesh
    EN1200112_9: THREE.Mesh
    EN1200112_10: THREE.Mesh
    EN1200112_11: THREE.Mesh
    EN1200112_12: THREE.Mesh
    EN1200113_1: THREE.Mesh
    EN1200113_2: THREE.Mesh
    EN1200113_3: THREE.Mesh
    EN1200113_4: THREE.Mesh
    EN1200113_5: THREE.Mesh
    EN1200113_6: THREE.Mesh
    EN1200113_7: THREE.Mesh
    EN1200113_8: THREE.Mesh
    EN1200113_9: THREE.Mesh
    EN1200113_10: THREE.Mesh
    EN1200113_11: THREE.Mesh
    EN1200113_12: THREE.Mesh
    EN1200199_1: THREE.Mesh
    EN1200199_2: THREE.Mesh
    EN1200199_3: THREE.Mesh
    EN1200199_4: THREE.Mesh
    EN1200199_5: THREE.Mesh
    EN1200199_6: THREE.Mesh
    EN1200199_7: THREE.Mesh
    EN1200199_8: THREE.Mesh
    EN1200199_9: THREE.Mesh
    EN1200199_10: THREE.Mesh
    EN1200199_11: THREE.Mesh
    EN1200199_12: THREE.Mesh
    EN1200199_13: THREE.Mesh
    EN1200199_14: THREE.Mesh
    EN1200199_15: THREE.Mesh
    EN1200199_16: THREE.Mesh
    EN1200199_17: THREE.Mesh
    EN1200199_18: THREE.Mesh
    EN1200199_19: THREE.Mesh
    EN1200199_20: THREE.Mesh
    EN1200199_21: THREE.Mesh
    EN1200199_22: THREE.Mesh
    EN1200199_23: THREE.Mesh
    EN1200199_24: THREE.Mesh
    EN1200199_25: THREE.Mesh
    EN1200199_26: THREE.Mesh
    EN1200199_27: THREE.Mesh
    EN1200199_28: THREE.Mesh
    EN1200199_29: THREE.Mesh
    Plane: THREE.Mesh
  }
  materials: {
    ['Concrete, Cast-in-Place gray']: THREE.MeshStandardMaterial
    ปูนฉาบ: THREE.MeshStandardMaterial
    กระเบื้องดินเผา: THREE.MeshStandardMaterial
    ['Default Wall']: THREE.MeshStandardMaterial
    Aluminum: THREE.MeshStandardMaterial
    ไม้มะปิน: THREE.MeshStandardMaterial
    เหล็กตัวC: THREE.MeshStandardMaterial
    Aluminium: THREE.MeshStandardMaterial
    เหล็ก: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ไม้: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.001']: THREE.MeshStandardMaterial
    ['ปูนฉาบ.001']: THREE.MeshStandardMaterial
    ['กระเบื้องดินเผา.001']: THREE.MeshStandardMaterial
    ['Default Wall.001']: THREE.MeshStandardMaterial
    ['Aluminium.001']: THREE.MeshStandardMaterial
    ['เหล็ก.001']: THREE.MeshStandardMaterial
    ['Glass.001']: THREE.MeshStandardMaterial
    ['Aluminum.001']: THREE.MeshStandardMaterial
    ['ไม้มะปิน.001']: THREE.MeshStandardMaterial
    ['เหล็กตัวC.001']: THREE.MeshStandardMaterial
    ['ไม้.001']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.001']: THREE.MeshStandardMaterial
    ['ปูนฉาบ.003']: THREE.MeshStandardMaterial
    ['Default Wall.003']: THREE.MeshStandardMaterial
    ['กระเบื้องเคลือบสี.001']: THREE.MeshStandardMaterial
    ['Aluminium.003']: THREE.MeshStandardMaterial
    ['เหล็ก.003']: THREE.MeshStandardMaterial
    ['Glass.003']: THREE.MeshStandardMaterial
    ['Steel, Paint Finish, Ivory, Matte.001']: THREE.MeshStandardMaterial
    ['Steel, 45-345.001']: THREE.MeshStandardMaterial
    ['Label - Aluminium - RAL 6005 Moss Green.001']: THREE.MeshStandardMaterial
    ['Label - Glass - Clear.001']: THREE.MeshStandardMaterial
    ['Label - Rubber - Black.001']: THREE.MeshStandardMaterial
    ['Metal - Solar Innovations - Powder Coat.001']: THREE.MeshStandardMaterial
    ['Glazing - Solar Innovations - Clear.001']: THREE.MeshStandardMaterial
    ['Glas GEALAN.001']: THREE.MeshStandardMaterial
    ['Rubber_Gealan_Black.001']: THREE.MeshStandardMaterial
    ['Color_Gealan_Realwood-RAL-7016.001']: THREE.MeshStandardMaterial
    ['Frame_Gealan_PVC-H.001']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.003']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.003']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.004']: THREE.MeshStandardMaterial
    ['กระเบื้องเคลือบสี.002']: THREE.MeshStandardMaterial
    ['ปูนฉาบ.004']: THREE.MeshStandardMaterial
    ['Default Wall.004']: THREE.MeshStandardMaterial
    ['Aluminum.002']: THREE.MeshStandardMaterial
    ['Glass.004']: THREE.MeshStandardMaterial
    ไม่มะปิน: THREE.MeshStandardMaterial
    ['เหล็ก.004']: THREE.MeshStandardMaterial
    ['Aluminium.004']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.004']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.005']: THREE.MeshStandardMaterial
    ['ปูนฉาบ.005']: THREE.MeshStandardMaterial
    ['Default Wall.005']: THREE.MeshStandardMaterial
    ['Aluminum.003']: THREE.MeshStandardMaterial
    ['Glass.005']: THREE.MeshStandardMaterial
    ['ไม่มะปิน.001']: THREE.MeshStandardMaterial
    ['เหล็ก.005']: THREE.MeshStandardMaterial
    ['Aluminium.005']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.005']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.006']: THREE.MeshStandardMaterial
    ['ปูนฉาบ.006']: THREE.MeshStandardMaterial
    ['Default Wall.006']: THREE.MeshStandardMaterial
    ['Aluminium.006']: THREE.MeshStandardMaterial
    ['เหล็ก.006']: THREE.MeshStandardMaterial
    ['Glass.006']: THREE.MeshStandardMaterial
    ['Aluminum.004']: THREE.MeshStandardMaterial
    ['ไม่มะปิน.002']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.006']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.007']: THREE.MeshStandardMaterial
    ['กระเบื้องเคลือบสี.003']: THREE.MeshStandardMaterial
    ['ปูนฉาบ.007']: THREE.MeshStandardMaterial
    ['Default Wall.007']: THREE.MeshStandardMaterial
    ['Aluminum.005']: THREE.MeshStandardMaterial
    ไม้อัดยางกันน้ำทาสีน้: THREE.MeshStandardMaterial
    ['เหล็ก.007']: THREE.MeshStandardMaterial
    เกล็ดไม้สัก: THREE.MeshStandardMaterial
    ['กระเบื้องดินเผา.002']: THREE.MeshStandardMaterial
    ['Glass.007']: THREE.MeshStandardMaterial
    ['Porcelain, Linen']: THREE.MeshStandardMaterial
    ['Laminate, Linen, Matte']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.007']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.008']: THREE.MeshStandardMaterial
    ['ปูนฉาบ.008']: THREE.MeshStandardMaterial
    ['Default Wall.008']: THREE.MeshStandardMaterial
    ['Aluminum.006']: THREE.MeshStandardMaterial
    ไม้สัก: THREE.MeshStandardMaterial
    ['เหล็กตัวC.002']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.008']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.009']: THREE.MeshStandardMaterial
    ['ปูนฉาบ.009']: THREE.MeshStandardMaterial
    ['Default Wall.009']: THREE.MeshStandardMaterial
    ['Aluminum.007']: THREE.MeshStandardMaterial
    ['ไม้สัก.001']: THREE.MeshStandardMaterial
    ['เหล็กตัวC.003']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.009']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.010']: THREE.MeshStandardMaterial
    ['ปูนฉาบ.010']: THREE.MeshStandardMaterial
    ['Default Wall.010']: THREE.MeshStandardMaterial
    ['Aluminum.008']: THREE.MeshStandardMaterial
    ['ไม้สัก.002']: THREE.MeshStandardMaterial
    ['เหล็กตัวC.004']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.010']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.011']: THREE.MeshStandardMaterial
    ['ปูนฉาบ.011']: THREE.MeshStandardMaterial
    ['Default Wall.011']: THREE.MeshStandardMaterial
    ['Glas GEALAN.002']: THREE.MeshStandardMaterial
    ['Aluminium.007']: THREE.MeshStandardMaterial
    ['Rubber_Gealan_Black.002']: THREE.MeshStandardMaterial
    ['Color_Gealan_Realwood-RAL-7016.002']: THREE.MeshStandardMaterial
    ['Frame_Gealan_PVC-H.002']: THREE.MeshStandardMaterial
    ['Glass.008']: THREE.MeshStandardMaterial
    ['เหล็ก.008']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.011']: THREE.MeshStandardMaterial
    ['Metal - Strugal - Stainless Steel']: THREE.MeshStandardMaterial
    ['Glass - Strugal - Clear Glazing']: THREE.MeshStandardMaterial
    ['Aluminum - Strugal - RAL 9016']: THREE.MeshStandardMaterial
    ['ปูนฉาบ.012']: THREE.MeshStandardMaterial
    ['Default Wall.012']: THREE.MeshStandardMaterial
    ['Aluminum.009']: THREE.MeshStandardMaterial
    ['Glass.009']: THREE.MeshStandardMaterial
    ['ไม่มะปิน.003']: THREE.MeshStandardMaterial
    ['เหล็ก.009']: THREE.MeshStandardMaterial
    ['Aluminium.008']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.012']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.012']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.013']: THREE.MeshStandardMaterial
    ['ปูนฉาบ.013']: THREE.MeshStandardMaterial
    ['Default Wall.013']: THREE.MeshStandardMaterial
    ['กระเบื้องดินเผา.003']: THREE.MeshStandardMaterial
    ['Glas GEALAN.003']: THREE.MeshStandardMaterial
    ['Aluminium.009']: THREE.MeshStandardMaterial
    ['Rubber_Gealan_Black.003']: THREE.MeshStandardMaterial
    ['Color_Gealan_Realwood-RAL-7016.003']: THREE.MeshStandardMaterial
    ['Frame_Gealan_PVC-H.003']: THREE.MeshStandardMaterial
    ['Glass.010']: THREE.MeshStandardMaterial
    ['เหล็ก.010']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.013']: THREE.MeshStandardMaterial
    ['Steel, 45-345.002']: THREE.MeshStandardMaterial
    ['ปูนฉาบ.014']: THREE.MeshStandardMaterial
    ['กระเบื้องดินเผา.004']: THREE.MeshStandardMaterial
    ['Default Wall.014']: THREE.MeshStandardMaterial
    ['กระเบื้องเคลือบสี.004']: THREE.MeshStandardMaterial
    ['Aluminum.010']: THREE.MeshStandardMaterial
    ['Glass.011']: THREE.MeshStandardMaterial
    ['ไม่มะปิน.004']: THREE.MeshStandardMaterial
    ['เหล็ก.011']: THREE.MeshStandardMaterial
    ['ไม้สัก.003']: THREE.MeshStandardMaterial
    ['เหล็กตัวC.005']: THREE.MeshStandardMaterial
    ['Steel, Paint Finish, Ivory, Matte.002']: THREE.MeshStandardMaterial
    ['Glas GEALAN.004']: THREE.MeshStandardMaterial
    ['Aluminium.010']: THREE.MeshStandardMaterial
    ['Rubber_Gealan_Black.004']: THREE.MeshStandardMaterial
    ['Color_Gealan_Realwood-RAL-7016.004']: THREE.MeshStandardMaterial
    ['Frame_Gealan_PVC-H.004']: THREE.MeshStandardMaterial
    ไม้อัดยางกันน้ำทาสี: THREE.MeshStandardMaterial
    ['เกล็ดไม้สัก.001']: THREE.MeshStandardMaterial
    ['Metal - Strugal - Stainless Steel.001']: THREE.MeshStandardMaterial
    ['Glass - Strugal - Clear Glazing.001']: THREE.MeshStandardMaterial
    ['Aluminum - Strugal - RAL 9016.001']: THREE.MeshStandardMaterial
    ['Default Floor']: THREE.MeshStandardMaterial
    ['Label - Aluminium - RAL 6005 Moss Green.002']: THREE.MeshStandardMaterial
    ['Label - Glass - Clear.002']: THREE.MeshStandardMaterial
    ['Label - Rubber - Black.002']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.014']: THREE.MeshStandardMaterial
    ['Concrete - Cast-in-Place Concrete - Concr_240 ksc.014']: THREE.MeshStandardMaterial
    ['Concrete, Cast In Situ']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export const en120Floors01 = [
  "EN1200101", "EN1200102", "EN1200103", "EN1200104", "EN1200105", "EN1200106", "EN1200107", "EN1200108", "EN1200109", "EN1200110", "EN1200111", "EN1200112", "EN1200113", "EN1200199"
] as const;

export type EN120Floor1 = typeof en120Floors01[number];

type Props = JSX.IntrinsicElements["group"] & {
  isShowLamp?: boolean;
  isShowAir?: boolean;
  isManage?: boolean;
  isFloorPage?: boolean;
  isRoomPage?: boolean;
  roomData? : any[];
  pathname?: string;
  isFloorColorChange?: boolean;
  activeAirId?: string | null;
  activeLampId?: string | null;
};

export default function EN12001Floor(props: Props) {
  const {
    isShowLamp,
    isShowAir,
    isManage,
    isFloorPage,
    isRoomPage,
    roomData,
    pathname,
    isFloorColorChange,
    activeAirId,
    activeLampId,
  } = props;

  const groupRef = useRef<any>();
  const floorId = pathname;

  const path = usePathname();
  const roomId = path.split('/room/')[1];

  const { nodes, materials } = useGLTF('/models/building/en120/en120-1.glb') as GLTFResult

  const [hover, setHover] = useState<EN120Floor1 | null>(null);
  const { select, setSelect } = useEN12001Store(state => (state));
  const { menuState } = useContourMenuStore();
  const [modalFloorRoomDetail, setModalFloorRoomDetail] = useState<IModalRoomDetails | null>(null);
  const [modalRoomDetail, setModalRoomDetail] = useState<any>(null);
  const [modalLampDetail, setModalLampDetail] = useState<any>(null);
  const [modalAirDetail, setModalAirDetail] = useState<any>(null);

  const modalDistance = configs.building[roomId?.substring(0, 5).toLowerCase()]?.floor?.[roomId?.substring(0, 7).toLowerCase()]?.room?.[roomId?.toLowerCase()]?.modalDistance

  const handleObjectHover = useCallback((object: EN120Floor1 | null | any) => {
    setHover(object);
  }, []);

  const handleObjectSelect = useCallback(
    (object: EN120Floor1 | null | any) => {
      setSelect(object);
    },
    [setSelect]
  );

  useEffect(() => {
    const floorContourColor = () => {
      if (!groupRef.current) return;
  
      groupRef.current.traverse((groupChild: any) => {
        if ((groupChild.isGroup || groupChild.type === 'Select') && !groupChild.name.includes('-')) {
          const roomData = props.roomData?.[groupChild.name];
  
          if (roomData && roomData.Humi_Temp_PM25) {
            // Calculate averages
            const sensors = Object.values(roomData.Humi_Temp_PM25) as Array<{
              Temp?: number;
              Humidity?: number;
              PM25?: number;
            }>;
  
            let averages: any = null;
            if (sensors.length > 1) {
              const total = sensors.reduce(
                (acc: { Temp: number; Humidity: number; PM25: number; count: number }, sensor) => {
                  acc.Temp += sensor.Temp || 0;
                  acc.Humidity += sensor.Humidity || 0;
                  acc.PM25 += sensor.PM25 || 0;
                  acc.count += 1;
                  return acc;
                },
                { Temp: 0, Humidity: 0, PM25: 0, count: 0 }
              );
  
              averages = {
                Temp: total.Temp / total.count,
                Humidity: total.Humidity / total.count,
                PM25: total.PM25 / total.count,
              };
            } else if (sensors.length === 1) {
              const sensor = sensors[0];
              averages = {
                Temp: sensor.Temp || 0,
                Humidity: sensor.Humidity || 0,
                PM25: sensor.PM25 || 0,
              };
            }
  
            if (averages) {
              // console.log(`Averages for ${groupChild.name}:`, averages);
  
              // Handle menuState
              if (menuState === null) {
                // Reset to original color
                groupChild.traverse((meshChild: any) => {
                  if (meshChild.isMesh || meshChild.isInstancedMesh) {
                    if (meshChild.material) {
                      if (Array.isArray(meshChild.material)) {
                        meshChild.material.forEach((mat: any) => {
                          if (mat.userData.originalColor) {
                            mat.color.set(mat.userData.originalColor);
                            mat.needsUpdate = true;
                          }
                        });
                      } else {
                        if (meshChild.material.userData.originalColor) {
                          meshChild.material.color.set(meshChild.material.userData.originalColor);
                          meshChild.material.needsUpdate = true;
                        }
                      }
                    }
                  }
                });
              } else {
                // Process PM2.5, Humidity, or Temperature
                const processState = (value: number, scale: any, groupName: string) => {
                  const normalizedValue = Math.max(0, Math.min(value, 1));
                  const color = getColorFromScale(normalizedValue, scale);
  
                  groupChild.traverse((meshChild: any) => {
                    if (meshChild.isMesh || meshChild.isInstancedMesh) {
                      if (
                        meshChild.material &&
                        (meshChild.material.name?.includes('Concrete, Cast-in-Place gray'))
                      ) {
                        // Save original color if not saved yet
                        if (!meshChild.material.userData.originalColor) {
                          meshChild.material.userData.originalColor = meshChild.material.color.getHex();
                        }
  
                        // Set new color
                        if (Array.isArray(meshChild.material)) {
                          meshChild.material.forEach((mat: any) => {
                            mat.color.set(color);
                            mat.needsUpdate = true;
                          });
                        } else {
                          meshChild.material.color.set(color);
                          meshChild.material.needsUpdate = true;
                        }
  
                        // console.log(`Changed color for ${meshChild.name} in ${groupName}`);
                      }
                    }
                  });
                };
  
                if (menuState === 'pm25') {
                  const pm25Value = averages.PM25 || 0;
                  processState(pm25Value / 600, configs.colorScale.pm25, groupChild.name);
                } else if (menuState === 'humidity') {
                  const humidityValue = averages.Humidity || 0;
                  processState(humidityValue / 100, configs.colorScale.humidity, groupChild.name);
                } else if (menuState === 'temperature') {
                  const tempValue = averages.Temp || 0;
                  processState(tempValue / 50, configs.colorScale.temperature, groupChild.name);
                }
              }
            }
          }
        }
      });
    };
  
    floorContourColor();
  }, [roomData, menuState]);

  useEffect(() => {
    const changeFloorColor = () => {
      if (!groupRef.current || !isFloorColorChange) return;
  
      groupRef.current.traverse((groupChild: any) => {
        groupChild.traverse((meshChild: any) => {
          if (meshChild.isMesh || meshChild.isInstancedMesh) {
            if (
              meshChild.material &&
              (meshChild.material.name?.includes('Concrete, Cast-in-Place gray'))
            ) {
              // Save original color if not saved yet
              if (!meshChild.material.userData.originalColor) {
                meshChild.material.userData.originalColor = meshChild.material.color.getHex();
              }
  
              // Change to gray color
              const grayColor = 0x959595; // Hex for gray
              if (Array.isArray(meshChild.material)) {
                meshChild.material.forEach((mat: any) => {
                  mat.color.set(grayColor);
                  mat.needsUpdate = true;
                });
              } else {
                meshChild.material.color.set(grayColor);
                meshChild.material.needsUpdate = true;
              }
            }
          }
        });
      });
    };
    changeFloorColor();
  }, [isFloorColorChange, isManage]);

  useEffect(() => {
    if (isRoomPage && !isManage && groupRef.current) {
      groupRef.current.traverse((child: any) => {
        if (child.isMesh && child.parent?.name) {
          const isMatchingRoom = child.parent.name.startsWith(roomId)
          if (Array.isArray(child.material)) {
            child.material.forEach((m: any) => {
              m.transparent = true;
              m.opacity = isMatchingRoom ? 1 : 0.3;
              m.needsUpdate = true; // Force material update
            });
          } else if (child.material) {
            child.material.transparent = true;
            child.material.opacity = isMatchingRoom ? 1 : 0.3;
            child.material.needsUpdate = true; // Force material update
          }
        }
      });
    }
  }, [isRoomPage, roomId]);

  useEffect(() => {
    const fetchFloorRoomDetail = async () => {
      if (isRoomPage) {
        if (select?.includes("L")) {
          const formattedSelect = select.replace("-", "");
          const lampData = await getData(`getLampById/${formattedSelect.toUpperCase()}`, true);
          setModalLampDetail(lampData);
        } else if (select?.includes("A")) {
          const formattedSelect = select.replace("-", "");
          const airData = await getData(`getAirById/${formattedSelect.toUpperCase()}`, true);
          setModalAirDetail(airData[0]);
        } else {
          const roomData = await getData(`roomDetail/${select?.toUpperCase()}`, true);
          setModalRoomDetail(roomData);
        }
      } else {
        const floorRoomData = await getData(`floorRoomDetail/${select?.toUpperCase()}`, true);
        setModalFloorRoomDetail(floorRoomData);
      }
    }

    fetchFloorRoomDetail();
  }, [select]);

  const renderModalDetail = (roomCode: string) => {
    if (select === roomCode && !isManage) {
      return (
        <Html distanceFactor={50}>
          <div className="pt-[10px] transform z-0 translate-x-[30%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ห้อง ${roomCode.substring(6, 9)} - ${roomCode}`}
              </label>
              <Link href={`/room/${roomCode.toUpperCase()}`} target="_blank">
                <Button variant={"ghost"} size={"icon"}>
                  <ExternalLink className="size-5" />
                </Button>
              </Link>
            </div>
            <Table className="border rounded-md">
              <TableBody>
                <TableRow>
                  <TableCell className="p-2">Building Code</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.buildingCode || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Floor</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.floorNumber || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Room</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.roomNumber || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Energy</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.roomMeter || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Power</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.roomPower || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average PM 2.5</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.averagePM25 || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Temperature</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.averageTemp ? `${modalFloorRoomDetail?.averageTemp} °C` : "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Humidity</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.averageHumidity ? `${modalFloorRoomDetail?.averageHumidity} %` : "-"}
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </Html>
      )
    }
  }

  const renderModalRoomDetail = (roomCode: string) => {
    if (select === roomCode && select === roomId?.toUpperCase() && !isManage) {
      return (
        <Html distanceFactor={modalDistance || 20}>
          <div className="pt-[10px] transform z-0 translate-x-[30%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ห้อง ${roomCode.substring(6, 9)} - ${roomCode}`}
              </label>
            </div>
            <Table className="border rounded-md">
              <TableBody>
                <TableRow>
                  <TableCell className="p-2">Building Code</TableCell>
                  <TableCell className="p-2">
                    {roomCode.substring(0, 5) || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Floor</TableCell>
                  <TableCell className="p-2">
                    {roomCode.substring(5, 7) || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Room</TableCell>
                  <TableCell className="p-2">
                    {roomCode.substring(6, 9) || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Number of Air Conditioners</TableCell>
                  <TableCell className="p-2">
                    {
                      configs.building[roomId.substring(0, 5).toLowerCase()]?.floor?.[roomId.substring(0, 7).toLowerCase()]?.room?.[roomId.toLowerCase()]
                      ?.airCount || "-"
                    }
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Number of Lamps</TableCell>
                  <TableCell className="p-2">
                    {
                      configs.building[roomId.substring(0, 5).toLowerCase()]?.floor?.[roomId.substring(0, 7).toLowerCase()]?.room?.[roomId.toLowerCase()]
                      ?.lampCount || "-"
                    }
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Energy</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomMeter || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Power</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomPower || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average PM 2.5</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomPM25 || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Temperature</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomTemp ? `${modalRoomDetail?.roomTemp} °C` : "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Humidity</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomHumidity ? `${modalRoomDetail?.roomHumidity} %` : "-"}
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </Html>
      )
    }
  }

  return (
    <group 
      onPointerOver={(e) => {
        e.stopPropagation();
        handleObjectHover(e.object.parent?.name);
      }} 
      onPointerOut={(e) => {
        e.stopPropagation();
        handleObjectHover(null)
      }}
      onClick={(e) => {
        e.stopPropagation();
        handleObjectSelect(e.object.parent?.name)
      }}
      ref={groupRef} 
      {...props} 
      dispose={null}
    >
      <Select name="EN1200101" enabled={hover === "EN1200101" || select === "EN1200101"} position={[17.476, 2.75, -23.034]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1200101")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1200101")}
        <mesh name="EN1200101_1" geometry={nodes.EN1200101_1.geometry} material={materials['Concrete, Cast-in-Place gray']} />
        <mesh name="EN1200101_2" geometry={nodes.EN1200101_2.geometry} material={materials.ปูนฉาบ} />
        <mesh name="EN1200101_3" geometry={nodes.EN1200101_3.geometry} material={materials.กระเบื้องดินเผา} />
        <mesh name="EN1200101_4" geometry={nodes.EN1200101_4.geometry} material={materials['Default Wall']} />
        <mesh name="EN1200101_5" geometry={nodes.EN1200101_5.geometry} material={materials.Aluminum} />
        <mesh name="EN1200101_6" geometry={nodes.EN1200101_6.geometry} material={materials.ไม้มะปิน} />
        <mesh name="EN1200101_7" geometry={nodes.EN1200101_7.geometry} material={materials.เหล็กตัวC} />
        <mesh name="EN1200101_8" geometry={nodes.EN1200101_8.geometry} material={materials.Aluminium} />
        <mesh name="EN1200101_9" geometry={nodes.EN1200101_9.geometry} material={materials.เหล็ก} />
        <mesh name="EN1200101_10" geometry={nodes.EN1200101_10.geometry} material={materials.Glass} />
        <mesh name="EN1200101_11" geometry={nodes.EN1200101_11.geometry} material={materials.ไม้} />
        <mesh name="EN1200101_12" geometry={nodes.EN1200101_12.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc']} />
      </Select>
      <Select name="EN1200102" enabled={hover === "EN1200102" || select === "EN1200102"} position={[24.41, 2.817, -22.93]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1200102")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1200102")}
        <mesh name="EN1200102_1" geometry={nodes.EN1200102_1.geometry} material={materials['Concrete, Cast-in-Place gray.001']} />
        <mesh name="EN1200102_2" geometry={nodes.EN1200102_2.geometry} material={materials['ปูนฉาบ.001']} />
        <mesh name="EN1200102_3" geometry={nodes.EN1200102_3.geometry} material={materials['กระเบื้องดินเผา.001']} />
        <mesh name="EN1200102_4" geometry={nodes.EN1200102_4.geometry} material={materials['Default Wall.001']} />
        <mesh name="EN1200102_5" geometry={nodes.EN1200102_5.geometry} material={materials['Aluminium.001']} />
        <mesh name="EN1200102_6" geometry={nodes.EN1200102_6.geometry} material={materials['เหล็ก.001']} />
        <mesh name="EN1200102_7" geometry={nodes.EN1200102_7.geometry} material={materials['Glass.001']} />
        <mesh name="EN1200102_8" geometry={nodes.EN1200102_8.geometry} material={materials['Aluminum.001']} />
        <mesh name="EN1200102_9" geometry={nodes.EN1200102_9.geometry} material={materials['ไม้มะปิน.001']} />
        <mesh name="EN1200102_10" geometry={nodes.EN1200102_10.geometry} material={materials['เหล็กตัวC.001']} />
        <mesh name="EN1200102_11" geometry={nodes.EN1200102_11.geometry} material={materials['ไม้.001']} />
        <mesh name="EN1200102_12" geometry={nodes.EN1200102_12.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.001']} />
      </Select>
      <Select name="EN1200103" enabled={hover === "EN1200103" || select === "EN1200103"} position={[-20.306, 2.797, -5.139]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1200103")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1200103")}
        <mesh name="EN1200103_1" geometry={nodes.EN1200103_1.geometry} material={materials['ปูนฉาบ.003']} />
        <mesh name="EN1200103_2" geometry={nodes.EN1200103_2.geometry} material={materials['Default Wall.003']} />
        <mesh name="EN1200103_3" geometry={nodes.EN1200103_3.geometry} material={materials['กระเบื้องเคลือบสี.001']} />
        <mesh name="EN1200103_4" geometry={nodes.EN1200103_4.geometry} material={materials['Aluminium.003']} />
        <mesh name="EN1200103_5" geometry={nodes.EN1200103_5.geometry} material={materials['เหล็ก.003']} />
        <mesh name="EN1200103_6" geometry={nodes.EN1200103_6.geometry} material={materials['Glass.003']} />
        <mesh name="EN1200103_7" geometry={nodes.EN1200103_7.geometry} material={materials['Steel, Paint Finish, Ivory, Matte.001']} />
        <mesh name="EN1200103_8" geometry={nodes.EN1200103_8.geometry} material={materials['Steel, 45-345.001']} />
        <mesh name="EN1200103_9" geometry={nodes.EN1200103_9.geometry} material={materials['Label - Aluminium - RAL 6005 Moss Green.001']} />
        <mesh name="EN1200103_10" geometry={nodes.EN1200103_10.geometry} material={materials['Label - Glass - Clear.001']} />
        <mesh name="EN1200103_11" geometry={nodes.EN1200103_11.geometry} material={materials['Label - Rubber - Black.001']} />
        <mesh name="EN1200103_12" geometry={nodes.EN1200103_12.geometry} material={materials['Metal - Solar Innovations - Powder Coat.001']} />
        <mesh name="EN1200103_13" geometry={nodes.EN1200103_13.geometry} material={materials['Glazing - Solar Innovations - Clear.001']} />
        <mesh name="EN1200103_14" geometry={nodes.EN1200103_14.geometry} material={materials['Glas GEALAN.001']} />
        <mesh name="EN1200103_15" geometry={nodes.EN1200103_15.geometry} material={materials['Rubber_Gealan_Black.001']} />
        <mesh name="EN1200103_16" geometry={nodes.EN1200103_16.geometry} material={materials['Color_Gealan_Realwood-RAL-7016.001']} />
        <mesh name="EN1200103_17" geometry={nodes.EN1200103_17.geometry} material={materials['Frame_Gealan_PVC-H.001']} />
        <mesh name="EN1200103_18" geometry={nodes.EN1200103_18.geometry} material={materials['Concrete, Cast-in-Place gray.003']} />
        <mesh name="EN1200103_19" geometry={nodes.EN1200103_19.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.003']} />
      </Select>
      <Select name="EN1200104" enabled={hover === "EN1200104" || select === "EN1200104"} position={[-1.31, 2.564, -5.151]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1200104")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1200104")}
        <mesh name="EN1200104_1" geometry={nodes.EN1200104_1.geometry} material={materials['Concrete, Cast-in-Place gray.004']} />
        <mesh name="EN1200104_2" geometry={nodes.EN1200104_2.geometry} material={materials['กระเบื้องเคลือบสี.002']} />
        <mesh name="EN1200104_3" geometry={nodes.EN1200104_3.geometry} material={materials['ปูนฉาบ.004']} />
        <mesh name="EN1200104_4" geometry={nodes.EN1200104_4.geometry} material={materials['Default Wall.004']} />
        <mesh name="EN1200104_5" geometry={nodes.EN1200104_5.geometry} material={materials['Aluminum.002']} />
        <mesh name="EN1200104_6" geometry={nodes.EN1200104_6.geometry} material={materials['Glass.004']} />
        <mesh name="EN1200104_7" geometry={nodes.EN1200104_7.geometry} material={materials.ไม่มะปิน} />
        <mesh name="EN1200104_8" geometry={nodes.EN1200104_8.geometry} material={materials['เหล็ก.004']} />
        <mesh name="EN1200104_9" geometry={nodes.EN1200104_9.geometry} material={materials['Aluminium.004']} />
        <mesh name="EN1200104_10" geometry={nodes.EN1200104_10.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.004']} />
      </Select>
      <Select name="EN1200105" enabled={hover === "EN1200105" || select === "EN1200105"} position={[10.868, 2.915, -5.131]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1200105")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1200105")}  
        <mesh name="EN1200105_1" geometry={nodes.EN1200105_1.geometry} material={materials['Concrete, Cast-in-Place gray.005']} />
        <mesh name="EN1200105_2" geometry={nodes.EN1200105_2.geometry} material={materials['ปูนฉาบ.005']} />
        <mesh name="EN1200105_3" geometry={nodes.EN1200105_3.geometry} material={materials['Default Wall.005']} />
        <mesh name="EN1200105_4" geometry={nodes.EN1200105_4.geometry} material={materials['Aluminum.003']} />
        <mesh name="EN1200105_5" geometry={nodes.EN1200105_5.geometry} material={materials['Glass.005']} />
        <mesh name="EN1200105_6" geometry={nodes.EN1200105_6.geometry} material={materials['ไม่มะปิน.001']} />
        <mesh name="EN1200105_7" geometry={nodes.EN1200105_7.geometry} material={materials['เหล็ก.005']} />
        <mesh name="EN1200105_8" geometry={nodes.EN1200105_8.geometry} material={materials['Aluminium.005']} />
        <mesh name="EN1200105_9" geometry={nodes.EN1200105_9.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.005']} />
      </Select>
      <Select name="EN1200106" enabled={hover === "EN1200106" || select === "EN1200106"} position={[16.695, 2.794, -5.208]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1200106")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1200106")}  
        <mesh name="EN1200106_1" geometry={nodes.EN1200106_1.geometry} material={materials['Concrete, Cast-in-Place gray.006']} />
        <mesh name="EN1200106_2" geometry={nodes.EN1200106_2.geometry} material={materials['ปูนฉาบ.006']} />
        <mesh name="EN1200106_3" geometry={nodes.EN1200106_3.geometry} material={materials['Default Wall.006']} />
        <mesh name="EN1200106_4" geometry={nodes.EN1200106_4.geometry} material={materials['Aluminium.006']} />
        <mesh name="EN1200106_5" geometry={nodes.EN1200106_5.geometry} material={materials['เหล็ก.006']} />
        <mesh name="EN1200106_6" geometry={nodes.EN1200106_6.geometry} material={materials['Glass.006']} />
        <mesh name="EN1200106_7" geometry={nodes.EN1200106_7.geometry} material={materials['Aluminum.004']} />
        <mesh name="EN1200106_8" geometry={nodes.EN1200106_8.geometry} material={materials['ไม่มะปิน.002']} />
        <mesh name="EN1200106_9" geometry={nodes.EN1200106_9.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.006']} />
      </Select>
      <Select name="EN1200107" enabled={hover === "EN1200107" || select === "EN1200107"} position={[24.178, 2.857, -4.906]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1200107")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1200107")}
        <mesh name="EN1200107_1" geometry={nodes.EN1200107_1.geometry} material={materials['Concrete, Cast-in-Place gray.007']} />
        <mesh name="EN1200107_2" geometry={nodes.EN1200107_2.geometry} material={materials['กระเบื้องเคลือบสี.003']} />
        <mesh name="EN1200107_3" geometry={nodes.EN1200107_3.geometry} material={materials['ปูนฉาบ.007']} />
        <mesh name="EN1200107_4" geometry={nodes.EN1200107_4.geometry} material={materials['Default Wall.007']} />
        <mesh name="EN1200107_5" geometry={nodes.EN1200107_5.geometry} material={materials['Aluminum.005']} />
        <mesh name="EN1200107_6" geometry={nodes.EN1200107_6.geometry} material={materials.ไม้อัดยางกันน้ำทาสีน้} />
        <mesh name="EN1200107_7" geometry={nodes.EN1200107_7.geometry} material={materials['เหล็ก.007']} />
        <mesh name="EN1200107_8" geometry={nodes.EN1200107_8.geometry} material={materials.เกล็ดไม้สัก} />
        <mesh name="EN1200107_9" geometry={nodes.EN1200107_9.geometry} material={materials['กระเบื้องดินเผา.002']} />
        <mesh name="EN1200107_10" geometry={nodes.EN1200107_10.geometry} material={materials['Glass.007']} />
        <mesh name="EN1200107_11" geometry={nodes.EN1200107_11.geometry} material={materials['Porcelain, Linen']} />
        <mesh name="EN1200107_12" geometry={nodes.EN1200107_12.geometry} material={materials['Laminate, Linen, Matte']} />
        <mesh name="EN1200107_13" geometry={nodes.EN1200107_13.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.007']} />
      </Select>
      <Select name="EN1200108" enabled={hover === "EN1200108" || select === "EN1200108"} position={[-8.546, 2.813, 4.743]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1200108")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1200108")}    
        <mesh name="EN1200108_1" geometry={nodes.EN1200108_1.geometry} material={materials['Concrete, Cast-in-Place gray.008']} />
        <mesh name="EN1200108_2" geometry={nodes.EN1200108_2.geometry} material={materials['ปูนฉาบ.008']} />
        <mesh name="EN1200108_3" geometry={nodes.EN1200108_3.geometry} material={materials['Default Wall.008']} />
        <mesh name="EN1200108_4" geometry={nodes.EN1200108_4.geometry} material={materials['Aluminum.006']} />
        <mesh name="EN1200108_5" geometry={nodes.EN1200108_5.geometry} material={materials.ไม้สัก} />
        <mesh name="EN1200108_6" geometry={nodes.EN1200108_6.geometry} material={materials['เหล็กตัวC.002']} />
        <mesh name="EN1200108_7" geometry={nodes.EN1200108_7.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.008']} />
      </Select>
      <Select name="EN1200109" enabled={hover === "EN1200109" || select === "EN1200109"} position={[-4.18, 2.732, 4.737]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1200109")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1200109")}  
        <mesh name="EN1200109_1" geometry={nodes.EN1200109_1.geometry} material={materials['Concrete, Cast-in-Place gray.009']} />
        <mesh name="EN1200109_2" geometry={nodes.EN1200109_2.geometry} material={materials['ปูนฉาบ.009']} />
        <mesh name="EN1200109_3" geometry={nodes.EN1200109_3.geometry} material={materials['Default Wall.009']} />
        <mesh name="EN1200109_4" geometry={nodes.EN1200109_4.geometry} material={materials['Aluminum.007']} />
        <mesh name="EN1200109_5" geometry={nodes.EN1200109_5.geometry} material={materials['ไม้สัก.001']} />
        <mesh name="EN1200109_6" geometry={nodes.EN1200109_6.geometry} material={materials['เหล็กตัวC.003']} />
        <mesh name="EN1200109_7" geometry={nodes.EN1200109_7.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.009']} />
      </Select>
      <Select name="EN1200110" enabled={hover === "EN1200110" || select === "EN1200110"} position={[0.201, 2.907, 4.687]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1200110")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1200110")}
        <mesh name="EN1200110_1" geometry={nodes.EN1200110_1.geometry} material={materials['Concrete, Cast-in-Place gray.010']} />
        <mesh name="EN1200110_2" geometry={nodes.EN1200110_2.geometry} material={materials['ปูนฉาบ.010']} />
        <mesh name="EN1200110_3" geometry={nodes.EN1200110_3.geometry} material={materials['Default Wall.010']} />
        <mesh name="EN1200110_4" geometry={nodes.EN1200110_4.geometry} material={materials['Aluminum.008']} />
        <mesh name="EN1200110_5" geometry={nodes.EN1200110_5.geometry} material={materials['ไม้สัก.002']} />
        <mesh name="EN1200110_6" geometry={nodes.EN1200110_6.geometry} material={materials['เหล็กตัวC.004']} />
        <mesh name="EN1200110_7" geometry={nodes.EN1200110_7.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.010']} />
      </Select>
      <Select name="EN1200111" enabled={hover === "EN1200111" || select === "EN1200111"} position={[4.8, 2.857, 4.912]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1200111")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1200111")}  
        <mesh name="EN1200111_1" geometry={nodes.EN1200111_1.geometry} material={materials['Concrete, Cast-in-Place gray.011']} />
        <mesh name="EN1200111_2" geometry={nodes.EN1200111_2.geometry} material={materials['ปูนฉาบ.011']} />
        <mesh name="EN1200111_3" geometry={nodes.EN1200111_3.geometry} material={materials['Default Wall.011']} />
        <mesh name="EN1200111_4" geometry={nodes.EN1200111_4.geometry} material={materials['Glas GEALAN.002']} />
        <mesh name="EN1200111_5" geometry={nodes.EN1200111_5.geometry} material={materials['Aluminium.007']} />
        <mesh name="EN1200111_6" geometry={nodes.EN1200111_6.geometry} material={materials['Rubber_Gealan_Black.002']} />
        <mesh name="EN1200111_7" geometry={nodes.EN1200111_7.geometry} material={materials['Color_Gealan_Realwood-RAL-7016.002']} />
        <mesh name="EN1200111_8" geometry={nodes.EN1200111_8.geometry} material={materials['Frame_Gealan_PVC-H.002']} />
        <mesh name="EN1200111_9" geometry={nodes.EN1200111_9.geometry} material={materials['Glass.008']} />
        <mesh name="EN1200111_10" geometry={nodes.EN1200111_10.geometry} material={materials['เหล็ก.008']} />
        <mesh name="EN1200111_11" geometry={nodes.EN1200111_11.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.011']} />
      </Select>
      <Select name="EN1200112" enabled={hover === "EN1200112" || select === "EN1200112"} position={[10.836, 2.843, 4.812]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1200112")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1200112")}
        <mesh name="EN1200112_1" geometry={nodes.EN1200112_1.geometry} material={materials['Metal - Strugal - Stainless Steel']} />
        <mesh name="EN1200112_2" geometry={nodes.EN1200112_2.geometry} material={materials['Glass - Strugal - Clear Glazing']} />
        <mesh name="EN1200112_3" geometry={nodes.EN1200112_3.geometry} material={materials['Aluminum - Strugal - RAL 9016']} />
        <mesh name="EN1200112_4" geometry={nodes.EN1200112_4.geometry} material={materials['ปูนฉาบ.012']} />
        <mesh name="EN1200112_5" geometry={nodes.EN1200112_5.geometry} material={materials['Default Wall.012']} />
        <mesh name="EN1200112_6" geometry={nodes.EN1200112_6.geometry} material={materials['Aluminum.009']} />
        <mesh name="EN1200112_7" geometry={nodes.EN1200112_7.geometry} material={materials['Glass.009']} />
        <mesh name="EN1200112_8" geometry={nodes.EN1200112_8.geometry} material={materials['ไม่มะปิน.003']} />
        <mesh name="EN1200112_9" geometry={nodes.EN1200112_9.geometry} material={materials['เหล็ก.009']} />
        <mesh name="EN1200112_10" geometry={nodes.EN1200112_10.geometry} material={materials['Aluminium.008']} />
        <mesh name="EN1200112_11" geometry={nodes.EN1200112_11.geometry} material={materials['Concrete, Cast-in-Place gray.012']} />
        <mesh name="EN1200112_12" geometry={nodes.EN1200112_12.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.012']} />
      </Select>
      <Select name="EN1200113" enabled={hover === "EN1200113" || select === "EN1200113"} position={[16.876, 2.83, 4.906]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1200113")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1200113")}
        <mesh name="EN1200113_1" geometry={nodes.EN1200113_1.geometry} material={materials['Concrete, Cast-in-Place gray.013']} />
        <mesh name="EN1200113_2" geometry={nodes.EN1200113_2.geometry} material={materials['ปูนฉาบ.013']} />
        <mesh name="EN1200113_3" geometry={nodes.EN1200113_3.geometry} material={materials['Default Wall.013']} />
        <mesh name="EN1200113_4" geometry={nodes.EN1200113_4.geometry} material={materials['กระเบื้องดินเผา.003']} />
        <mesh name="EN1200113_5" geometry={nodes.EN1200113_5.geometry} material={materials['Glas GEALAN.003']} />
        <mesh name="EN1200113_6" geometry={nodes.EN1200113_6.geometry} material={materials['Aluminium.009']} />
        <mesh name="EN1200113_7" geometry={nodes.EN1200113_7.geometry} material={materials['Rubber_Gealan_Black.003']} />
        <mesh name="EN1200113_8" geometry={nodes.EN1200113_8.geometry} material={materials['Color_Gealan_Realwood-RAL-7016.003']} />
        <mesh name="EN1200113_9" geometry={nodes.EN1200113_9.geometry} material={materials['Frame_Gealan_PVC-H.003']} />
        <mesh name="EN1200113_10" geometry={nodes.EN1200113_10.geometry} material={materials['Glass.010']} />
        <mesh name="EN1200113_11" geometry={nodes.EN1200113_11.geometry} material={materials['เหล็ก.010']} />
        <mesh name="EN1200113_12" geometry={nodes.EN1200113_12.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.013']} />
      </Select>
      <Select name="EN1200199" enabled={hover === "EN1200199" || select === "EN1200199"} position={[-3.47, 2.596, 2.594]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1200199")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1200199")}
        <mesh name="EN1200199_1" geometry={nodes.EN1200199_1.geometry} material={materials['Steel, 45-345.002']} />
        <mesh name="EN1200199_2" geometry={nodes.EN1200199_2.geometry} material={materials['ปูนฉาบ.014']} />
        <mesh name="EN1200199_3" geometry={nodes.EN1200199_3.geometry} material={materials['กระเบื้องดินเผา.004']} />
        <mesh name="EN1200199_4" geometry={nodes.EN1200199_4.geometry} material={materials['Default Wall.014']} />
        <mesh name="EN1200199_5" geometry={nodes.EN1200199_5.geometry} material={materials['กระเบื้องเคลือบสี.004']} />
        <mesh name="EN1200199_6" geometry={nodes.EN1200199_6.geometry} material={materials['Aluminum.010']} />
        <mesh name="EN1200199_7" geometry={nodes.EN1200199_7.geometry} material={materials['Glass.011']} />
        <mesh name="EN1200199_8" geometry={nodes.EN1200199_8.geometry} material={materials['ไม่มะปิน.004']} />
        <mesh name="EN1200199_9" geometry={nodes.EN1200199_9.geometry} material={materials['เหล็ก.011']} />
        <mesh name="EN1200199_10" geometry={nodes.EN1200199_10.geometry} material={materials['ไม้สัก.003']} />
        <mesh name="EN1200199_11" geometry={nodes.EN1200199_11.geometry} material={materials['เหล็กตัวC.005']} />
        <mesh name="EN1200199_12" geometry={nodes.EN1200199_12.geometry} material={materials['Steel, Paint Finish, Ivory, Matte.002']} />
        <mesh name="EN1200199_13" geometry={nodes.EN1200199_13.geometry} material={materials['Glas GEALAN.004']} />
        <mesh name="EN1200199_14" geometry={nodes.EN1200199_14.geometry} material={materials['Aluminium.010']} />
        <mesh name="EN1200199_15" geometry={nodes.EN1200199_15.geometry} material={materials['Rubber_Gealan_Black.004']} />
        <mesh name="EN1200199_16" geometry={nodes.EN1200199_16.geometry} material={materials['Color_Gealan_Realwood-RAL-7016.004']} />
        <mesh name="EN1200199_17" geometry={nodes.EN1200199_17.geometry} material={materials['Frame_Gealan_PVC-H.004']} />
        <mesh name="EN1200199_18" geometry={nodes.EN1200199_18.geometry} material={materials.ไม้อัดยางกันน้ำทาสี} />
        <mesh name="EN1200199_19" geometry={nodes.EN1200199_19.geometry} material={materials['เกล็ดไม้สัก.001']} />
        <mesh name="EN1200199_20" geometry={nodes.EN1200199_20.geometry} material={materials['Metal - Strugal - Stainless Steel.001']} />
        <mesh name="EN1200199_21" geometry={nodes.EN1200199_21.geometry} material={materials['Glass - Strugal - Clear Glazing.001']} />
        <mesh name="EN1200199_22" geometry={nodes.EN1200199_22.geometry} material={materials['Aluminum - Strugal - RAL 9016.001']} />
        <mesh name="EN1200199_23" geometry={nodes.EN1200199_23.geometry} material={materials['Default Floor']} />
        <mesh name="EN1200199_24" geometry={nodes.EN1200199_24.geometry} material={materials['Label - Aluminium - RAL 6005 Moss Green.002']} />
        <mesh name="EN1200199_25" geometry={nodes.EN1200199_25.geometry} material={materials['Label - Glass - Clear.002']} />
        <mesh name="EN1200199_26" geometry={nodes.EN1200199_26.geometry} material={materials['Label - Rubber - Black.002']} />
        <mesh name="EN1200199_27" geometry={nodes.EN1200199_27.geometry} material={materials['Concrete, Cast-in-Place gray.014']} />
        <mesh name="EN1200199_28" geometry={nodes.EN1200199_28.geometry} material={materials['Concrete - Cast-in-Place Concrete - Concr_240 ksc.014']} />
        <mesh name="EN1200199_29" geometry={nodes.EN1200199_29.geometry} material={materials['Concrete, Cast In Situ']} />
      </Select>
      {/* <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[32, 0, -120]} scale={[950, 1, 950]} /> */}
    </group>
  )
}

useGLTF.preload('/models/building/en120/en120-1.glb')
