/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/building/en202/en202-B1.glb -t -k -E -R -f 
*/
"use client"

import * as THREE from 'three'
import React, { useCallback, useEffect, useRef, useState } from 'react'
import { Html, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { usePathname } from 'next/navigation'
import { IModalRoomDetails } from '@/types/model'
import { useContourMenuStore } from '@/stores/use-menu-store'
import { configs } from '@/lib/configs'
import { useEN202B1Store } from '@/stores/use-floor-store'
import { getData } from '@/actions/actions'
import Link from 'next/link'
import { Button } from '@/components/shadcn-ui/button'
import { ExternalLink } from 'lucide-react'
import { Table, TableBody, TableCell, TableRow } from '@/components/shadcn-ui/table'
import { Select } from '@react-three/postprocessing'
import { getColorFromScale, getRoomActiveStatus } from '@/lib/utils'

type GLTFResult = GLTF & {
  nodes: {
    ['300_x_300mm_สีขาว']: THREE.Mesh
    ['300_x_300mm_สีขาว_1']: THREE.Mesh
    ['300_x_300mm_สีขาว_2']: THREE.Mesh
    ['300_x_300mm_สีขาว_3']: THREE.Mesh
    C1_200_x_200mm_สีขาว: THREE.Mesh
    C1_200_x_200mm_สีขาว_1: THREE.Mesh
    C1_200_x_200mm_สีขาว_2: THREE.Mesh
    C1_200_x_200mm_สีขาว_3: THREE.Mesh
    ['300_x_100mm_สีขาว']: THREE.Mesh
    ['300_x_100mm_สีขาว_1']: THREE.Mesh
    ['300_x_100mm_สีขาว_2']: THREE.Mesh
    ['300_x_100mm_สีขาว_3']: THREE.Mesh
    ['300_x_100mm_สีขาว_4']: THREE.Mesh
    ['300_x_100mm_สีขาว_5']: THREE.Mesh
    ['300_x_100mm_สีขาว_6']: THREE.Mesh
    ['300_x_100mm_สีขาว_7']: THREE.Mesh
    ['300_x_100mm_สีขาว_8']: THREE.Mesh
    ['300_x_100mm_สีขาว007']: THREE.Mesh
    ['300_x_100mm_สีขาว007_1']: THREE.Mesh
    ['300_x_100mm_สีขาว007_2']: THREE.Mesh
    ['300_x_100mm_สีขาว007_3']: THREE.Mesh
    ['300_x_100mm_สีขาว007_4']: THREE.Mesh
    ['300_x_100mm_สีขาว007_5']: THREE.Mesh
    ['300_x_100mm_สีขาว007_6']: THREE.Mesh
    ['300_x_100mm_สีขาว007_7']: THREE.Mesh
    ['300_x_100mm_สีขาว007_8']: THREE.Mesh
  }
  materials: {
    ['สีขาว 247 (White 247)']: THREE.MeshStandardMaterial
    ['สีเทา 128 (White 128)']: THREE.MeshStandardMaterial
    Aluminum: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['สีขาว 247 (White 247).001']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray']: THREE.MeshStandardMaterial
    ['Aluminum.001']: THREE.MeshStandardMaterial
    ['Glass.001']: THREE.MeshStandardMaterial
    ['สีขาว 247 (White 247).002']: THREE.MeshStandardMaterial
    ['สีเทา 128 (White 128).001']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.001']: THREE.MeshStandardMaterial
    ['Glass.002']: THREE.MeshStandardMaterial
    ['สีขาว 247']: THREE.MeshStandardMaterial
    ['Stainless steel Matt']: THREE.MeshStandardMaterial
    ['Aluminum.002']: THREE.MeshStandardMaterial
    Default: THREE.MeshStandardMaterial
    ['Concrete, Normal Weight - 5 ksi']: THREE.MeshStandardMaterial
    ['สีขาว 247 (White 247).003']: THREE.MeshStandardMaterial
    ['สีเทา 128 (White 128).002']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.002']: THREE.MeshStandardMaterial
    ['Glass.003']: THREE.MeshStandardMaterial
    ['Concrete, Normal Weight - 5 ksi.001']: THREE.MeshStandardMaterial
    ['สีขาว 247.001']: THREE.MeshStandardMaterial
    ['Stainless steel Matt.001']: THREE.MeshStandardMaterial
    ['Aluminum.003']: THREE.MeshStandardMaterial
    ['Default.001']: THREE.MeshStandardMaterial
  }
}

export const en202Floorsb1 = [
  "EN202B101", "EN202B102", "EN202B103", "EN202B199"
] as const;

export type EN202FloorB1 = typeof en202Floorsb1[number];

type Props = JSX.IntrinsicElements["group"] & {
  isShowLamp?: boolean;
  isShowAir?: boolean;
  isManage?: boolean;
  isFloorPage?: boolean;
  isRoomPage?: boolean;
  roomData? : any[];
  pathname?: string;
  isFloorColorChange?: boolean;
  activeAirId?: string | null;
  activeLampId?: string | null;
};

export default function EN202B1Floor(props: Props) {
  const {
    isShowLamp,
    isShowAir,
    isManage,
    isFloorPage,
    isRoomPage,
    roomData,
    pathname,
    isFloorColorChange,
    activeAirId,
    activeLampId,
  } = props;

  const groupRef = useRef<any>();
  const floorId = pathname;

  const path = usePathname();
  const roomId = path.split('/room/')[1];

  const { nodes, materials } = useGLTF('/models/building/en202/en202-B1.glb') as GLTFResult

  const [hover, setHover] = useState<EN202FloorB1 | null>(null);
  const { select, setSelect } = useEN202B1Store(state => (state));
  const { menuState } = useContourMenuStore();
  const [modalFloorRoomDetail, setModalFloorRoomDetail] = useState<IModalRoomDetails | null>(null);
  const [modalRoomDetail, setModalRoomDetail] = useState<any>(null);
  const [modalLampDetail, setModalLampDetail] = useState<any>(null);
  const [modalAirDetail, setModalAirDetail] = useState<any>(null);

  const modalDistance = configs.building[roomId?.substring(0, 5).toLowerCase()]?.floor?.[roomId?.substring(0, 7).toLowerCase()]?.room?.[roomId?.toLowerCase()]?.modalDistance

  const handleObjectHover = useCallback((object: EN202FloorB1 | null | any) => {
    setHover(object);
  }, []);

  const handleObjectSelect = useCallback(
    (object: EN202FloorB1 | null | any, group: THREE.Group) => {
      setSelect(object);
    },
    [setSelect]
  );

  useEffect(() => {
    const floorContourColor = () => {
      if (!groupRef.current) return;
  
      groupRef.current.traverse((groupChild: any) => {
        if ((groupChild.isGroup || groupChild.type === 'Select') && !groupChild.name.includes('-')) {
          const roomData = props.roomData?.[groupChild.name];
  
          if (roomData && roomData.Humi_Temp_PM25) {
            // Calculate averages
            const sensors = Object.values(roomData.Humi_Temp_PM25) as Array<{
              Temp?: number;
              Humidity?: number;
              PM25?: number;
            }>;
  
            let averages: any = null;
            if (sensors.length > 1) {
              const total = sensors.reduce(
                (acc: { Temp: number; Humidity: number; PM25: number; count: number }, sensor) => {
                  acc.Temp += sensor.Temp || 0;
                  acc.Humidity += sensor.Humidity || 0;
                  acc.PM25 += sensor.PM25 || 0;
                  acc.count += 1;
                  return acc;
                },
                { Temp: 0, Humidity: 0, PM25: 0, count: 0 }
              );
  
              averages = {
                Temp: total.Temp / total.count,
                Humidity: total.Humidity / total.count,
                PM25: total.PM25 / total.count,
              };
            } else if (sensors.length === 1) {
              const sensor = sensors[0];
              averages = {
                Temp: sensor.Temp || 0,
                Humidity: sensor.Humidity || 0,
                PM25: sensor.PM25 || 0,
              };
            }
  
            if (averages) {
              // console.log(`Averages for ${groupChild.name}:`, averages);
  
              // Handle menuState
              if (menuState === null) {
                // Reset to original color
                groupChild.traverse((meshChild: any) => {
                  if (meshChild.isMesh || meshChild.isInstancedMesh) {
                    if (meshChild.material) {
                      if (Array.isArray(meshChild.material)) {
                        meshChild.material.forEach((mat: any) => {
                          if (mat.userData.originalColor) {
                            mat.color.set(mat.userData.originalColor);
                            mat.needsUpdate = true;
                          }
                        });
                      } else {
                        if (meshChild.material.userData.originalColor) {
                          meshChild.material.color.set(meshChild.material.userData.originalColor);
                          meshChild.material.needsUpdate = true;
                        }
                      }
                    }
                  }
                });
              } else {
                // Process PM2.5, Humidity, or Temperature
                const processState = (value: number, scale: any, groupName: string) => {
                  const normalizedValue = Math.max(0, Math.min(value, 1));
                  const color = getColorFromScale(normalizedValue, scale);
  
                  groupChild.traverse((meshChild: any) => {
                    if (meshChild.isMesh || meshChild.isInstancedMesh) {
                      if (
                        meshChild.material &&
                        (meshChild.material.name?.includes('สีขาว 247 (White 247)'))
                      ) {
                        // Save original color if not saved yet
                        if (!meshChild.material.userData.originalColor) {
                          meshChild.material.userData.originalColor = meshChild.material.color.getHex();
                        }
  
                        // Set new color
                        if (Array.isArray(meshChild.material)) {
                          meshChild.material.forEach((mat: any) => {
                            mat.color.set(color);
                            mat.needsUpdate = true;
                          });
                        } else {
                          meshChild.material.color.set(color);
                          meshChild.material.needsUpdate = true;
                        }
  
                        // console.log(`Changed color for ${meshChild.name} in ${groupName}`);
                      }
                    }
                  });
                };
  
                if (menuState === 'pm25') {
                  const pm25Value = averages.PM25 || 0;
                  processState(pm25Value / 600, configs.colorScale.pm25, groupChild.name);
                } else if (menuState === 'humidity') {
                  const humidityValue = averages.Humidity || 0;
                  processState(humidityValue / 100, configs.colorScale.humidity, groupChild.name);
                } else if (menuState === 'temperature') {
                  const tempValue = averages.Temp || 0;
                  processState(tempValue / 50, configs.colorScale.temperature, groupChild.name);
                }
              }
            }
          }
        }
      });
    };
  
    floorContourColor();
  }, [roomData, menuState]);

  useEffect(() => {
    if (isManage) {
      const changeFloorColor = () => {
        if (!groupRef.current || !isFloorColorChange) return;
    
        groupRef.current.traverse((groupChild: any) => {
          groupChild.traverse((meshChild: any) => {
            if (meshChild.isMesh || meshChild.isInstancedMesh) {
              if (
                meshChild.material &&
                (meshChild.material.name?.includes('สีขาว 247 (White 247)'))
              ) {
                // Save original color if not saved yet
                if (!meshChild.material.userData.originalColor) {
                  meshChild.material.userData.originalColor = meshChild.material.color.getHex();
                }
    
                // Change to gray color
                const grayColor = 0x959595; // Hex for gray
                if (Array.isArray(meshChild.material)) {
                  meshChild.material.forEach((mat: any) => {
                    mat.color.set(grayColor);
                    mat.needsUpdate = true;
                  });
                } else {
                  meshChild.material.color.set(grayColor);
                  meshChild.material.needsUpdate = true;
                }
              }
            }
          });
        });
      };
      changeFloorColor();
    }
  }, [isFloorColorChange, isManage]);

  useEffect(() => {
    if (isRoomPage && !isManage && groupRef.current) {
      groupRef.current.traverse((child: any) => {
        if (child.isMesh && child.parent?.name) {
          const isMatchingRoom = child.parent.name.startsWith(roomId)
          if (Array.isArray(child.material)) {
            child.material.forEach((m: any) => {
              m.transparent = true;
              m.opacity = isMatchingRoom ? 1 : 0.3;
              m.needsUpdate = true; // Force material update
            });
          } else if (child.material) {
            child.material.transparent = true;
            child.material.opacity = isMatchingRoom ? 1 : 0.3;
            child.material.needsUpdate = true; // Force material update
          }
        }
      });
    }
  }, [isRoomPage, roomId]);

  useEffect(() => {
    const fetchFloorRoomDetail = async () => {
      if (isRoomPage) {
        if (select?.includes("L")) {
          const formattedSelect = select.replace("-", "");
          const lampData = await getData(`getLampById/${formattedSelect.toUpperCase()}`, true);
          setModalLampDetail(lampData);
        } else if (select?.includes("A")) {
          const formattedSelect = select.replace("-", "");
          const airData = await getData(`getAirById/${formattedSelect.toUpperCase()}`, true);
          setModalAirDetail(airData[0]);
        } else {
          const roomData = await getData(`roomDetail/${select?.toUpperCase()}`, true);
          setModalRoomDetail(roomData);
        }
      } else {
        const floorRoomData = await getData(`floorRoomDetail/${select?.toUpperCase()}`, true);
        setModalFloorRoomDetail(floorRoomData);
      }
    }

    fetchFloorRoomDetail();
  }, [select]);

  const renderModalDetail = (roomCode: string) => {
    const isRoomActive = getRoomActiveStatus(
      select?.substring(0, 5),
      select?.substring(0, 7),
      select?.substring(0, 9),
    )
    if (select === roomCode && !isManage) {
      return (
        <Html distanceFactor={50}>
          <div className="pt-[10px] transform z-0 translate-x-[30%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ห้อง ${roomCode.substring(6, 9)} - ${roomCode}`}
              </label>
              {isRoomActive && (
                <Link href={`/room/${roomCode.toUpperCase()}`} target="_blank">
                  <Button variant={"ghost"} size={"icon"}>
                    <ExternalLink className="size-5" />
                  </Button>
                </Link>
              )}
            </div>
            <Table className="border rounded-md">
              <TableBody>
                <TableRow>
                  <TableCell className="p-2">Building Code</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.buildingCode || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Floor</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.floorNumber || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Room</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.roomNumber || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Energy</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.roomMeter || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Power</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.roomPower || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average PM 2.5</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.averagePM25 || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Temperature</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.averageTemp ? `${modalFloorRoomDetail?.averageTemp} °C` : "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Humidity</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.averageHumidity ? `${modalFloorRoomDetail?.averageHumidity} %` : "-"}
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </Html>
      )
    }
  }

  const renderModalRoomDetail = (roomCode: string) => {
    if (select === roomCode && select === roomId?.toUpperCase() && !isManage) {
      return (
        <Html distanceFactor={modalDistance || 20}>
          <div className="pt-[10px] transform z-0 translate-x-[30%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ห้อง ${roomCode.substring(6, 9)} - ${roomCode}`}
              </label>
            </div>
            <Table className="border rounded-md">
              <TableBody>
                <TableRow>
                  <TableCell className="p-2">Building Code</TableCell>
                  <TableCell className="p-2">
                    {roomCode.substring(0, 5) || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Floor</TableCell>
                  <TableCell className="p-2">
                    {roomCode.substring(5, 7) || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Room</TableCell>
                  <TableCell className="p-2">
                    {roomCode.substring(6, 9) || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Number of Air Conditioners</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.airStatus?.length as number || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Number of Lamps</TableCell>
                  <TableCell className="p-2">
                    {
                      configs.building[roomId.substring(0, 5).toLowerCase()]?.floor?.[roomId.substring(0, 7).toLowerCase()]?.room?.[roomId.toLowerCase()]
                      ?.lampCount || "-"
                    }
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Energy</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomMeter || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Power</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomPower || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average PM 2.5</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomPM25 || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Temperature</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomTemp ? `${modalRoomDetail?.roomTemp} °C` : "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Humidity</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomHumidity ? `${modalRoomDetail?.roomHumidity} %` : "-"}
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </Html>
      )
    }
  }

  return (
    <group 
      onPointerOver={(e) => {
        e.stopPropagation();
        handleObjectHover(e.object.parent?.name);
      }} 
      onPointerOut={(e) => {
        e.stopPropagation();
        handleObjectHover(null)
      }}
      onClick={(e) => {
        e.stopPropagation();
        handleObjectSelect(e.object.parent?.name, e.object.parent as THREE.Group)
      }}
      ref={groupRef} 
      {...props} 
      dispose={null}
      // position={[0, 0.5, 0]}
    >
      <Select name="EN202B101" enabled={hover === "EN202B101" || select === "EN202B101"} position={[-7.056, 1.625, -15.983]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN202B101")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN202B101")}
        <mesh name="300_x_300mm_สีขาว" geometry={nodes['300_x_300mm_สีขาว'].geometry} material={materials['สีขาว 247 (White 247)']} />
        <mesh name="300_x_300mm_สีขาว_1" geometry={nodes['300_x_300mm_สีขาว_1'].geometry} material={materials['สีเทา 128 (White 128)']} />
        <mesh name="300_x_300mm_สีขาว_2" geometry={nodes['300_x_300mm_สีขาว_2'].geometry} material={materials.Aluminum} />
        <mesh name="300_x_300mm_สีขาว_3" geometry={nodes['300_x_300mm_สีขาว_3'].geometry} material={materials.Glass} />
      </Select>
      <Select name="EN202B102" enabled={hover === "EN202B102" || select === "EN202B102"} position={[-0.617, 1.992, -16.565]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN202B102")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN202B102")}
        <mesh name="C1_200_x_200mm_สีขาว" geometry={nodes.C1_200_x_200mm_สีขาว.geometry} material={materials['สีขาว 247 (White 247).001']} />
        <mesh name="C1_200_x_200mm_สีขาว_1" geometry={nodes.C1_200_x_200mm_สีขาว_1.geometry} material={materials['Concrete, Cast-in-Place gray']} />
        <mesh name="C1_200_x_200mm_สีขาว_2" geometry={nodes.C1_200_x_200mm_สีขาว_2.geometry} material={materials['Aluminum.001']} />
        <mesh name="C1_200_x_200mm_สีขาว_3" geometry={nodes.C1_200_x_200mm_สีขาว_3.geometry} material={materials['Glass.001']} />
      </Select>
      <Select name="EN202B103" enabled={hover === "EN202B103" || select === "EN202B103"} position={[16.234, 0.974, -0.111]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN202B103")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN202B103")}
        <mesh name="300_x_100mm_สีขาว" geometry={nodes['300_x_100mm_สีขาว'].geometry} material={materials['สีขาว 247 (White 247).002']} />
        <mesh name="300_x_100mm_สีขาว_1" geometry={nodes['300_x_100mm_สีขาว_1'].geometry} material={materials['สีเทา 128 (White 128).001']} />
        <mesh name="300_x_100mm_สีขาว_2" geometry={nodes['300_x_100mm_สีขาว_2'].geometry} material={materials['Concrete, Cast-in-Place gray.001']} />
        <mesh name="300_x_100mm_สีขาว_3" geometry={nodes['300_x_100mm_สีขาว_3'].geometry} material={materials['Glass.002']} />
        <mesh name="300_x_100mm_สีขาว_4" geometry={nodes['300_x_100mm_สีขาว_4'].geometry} material={materials['สีขาว 247']} />
        <mesh name="300_x_100mm_สีขาว_5" geometry={nodes['300_x_100mm_สีขาว_5'].geometry} material={materials['Stainless steel Matt']} />
        <mesh name="300_x_100mm_สีขาว_6" geometry={nodes['300_x_100mm_สีขาว_6'].geometry} material={materials['Aluminum.002']} />
        <mesh name="300_x_100mm_สีขาว_7" geometry={nodes['300_x_100mm_สีขาว_7'].geometry} material={materials.Default} />
        <mesh name="300_x_100mm_สีขาว_8" geometry={nodes['300_x_100mm_สีขาว_8'].geometry} material={materials['Concrete, Normal Weight - 5 ksi']} />
      </Select>
      <Select name="EN202B199" enabled={hover === "EN202B199" || select === "EN202B199"} position={[-9.98, 1.065, 0.497]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN202B199")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN202B199")}
        <mesh name="300_x_100mm_สีขาว007" geometry={nodes['300_x_100mm_สีขาว007'].geometry} material={materials['สีขาว 247 (White 247).003']} />
        <mesh name="300_x_100mm_สีขาว007_1" geometry={nodes['300_x_100mm_สีขาว007_1'].geometry} material={materials['สีเทา 128 (White 128).002']} />
        <mesh name="300_x_100mm_สีขาว007_2" geometry={nodes['300_x_100mm_สีขาว007_2'].geometry} material={materials['Concrete, Cast-in-Place gray.002']} />
        <mesh name="300_x_100mm_สีขาว007_3" geometry={nodes['300_x_100mm_สีขาว007_3'].geometry} material={materials['Glass.003']} />
        <mesh name="300_x_100mm_สีขาว007_4" geometry={nodes['300_x_100mm_สีขาว007_4'].geometry} material={materials['Concrete, Normal Weight - 5 ksi.001']} />
        <mesh name="300_x_100mm_สีขาว007_5" geometry={nodes['300_x_100mm_สีขาว007_5'].geometry} material={materials['สีขาว 247.001']} />
        <mesh name="300_x_100mm_สีขาว007_6" geometry={nodes['300_x_100mm_สีขาว007_6'].geometry} material={materials['Stainless steel Matt.001']} />
        <mesh name="300_x_100mm_สีขาว007_7" geometry={nodes['300_x_100mm_สีขาว007_7'].geometry} material={materials['Aluminum.003']} />
        <mesh name="300_x_100mm_สีขาว007_8" geometry={nodes['300_x_100mm_สีขาว007_8'].geometry} material={materials['Default.001']} />
      </Select>
    </group>
  )
}

useGLTF.preload('/models/building/en202/en202-B1.glb')
