/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/building/en117/en117-building.glb -t -k -E -R -f 
*/
"use client";

import * as THREE from "three";
import React, { useCallback, useEffect, useState } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useEN117Store } from "@/stores/use-building-store";
import { IFloorDetails } from "@/types/model";
import { getData } from "@/actions/actions";
import Link from "next/link";
import { Button } from "@/components/shadcn-ui/button";
import { ExternalLink } from "lucide-react";
import {
  Table,
  TableBody,
  TableCell,
  TableRow,
} from "@/components/shadcn-ui/table";
import { Select } from "@react-three/postprocessing";
import { getFloorActiveStatus } from "@/lib/utils";

type GLTFResult = GLTF & {
  nodes: {
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_1"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_2"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_3"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_4"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_5"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_6"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_7"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_8"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_9"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_10"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_11"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_12"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_13"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_14"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_15"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_16"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_17"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_18"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_19"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_20"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_21"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_22"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_23"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_24"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_25"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_26"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_27"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_28"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_29"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_30"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_31"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_32"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_33"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_34"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_35"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_36"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_37"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_38"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_39"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_40"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_41"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_42"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_43"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_44"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_45"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_46"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_47"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_48"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_49"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_1"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_2"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_3"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_4"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_5"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_6"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_7"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_8"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_9"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_10"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_11"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_12"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_13"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_14"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_15"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_16"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_17"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_18"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_19"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_20"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_21"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_22"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_23"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_24"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_25"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_26"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_27"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_28"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_29"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_30"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_31"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_32"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_33"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_34"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_35"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_36"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_37"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_1"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_2"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_3"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_4"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_5"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_6"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_7"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_8"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_9"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_10"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_11"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_12"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_13"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_14"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_15"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_16"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_17"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_18"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_19"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_20"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_21"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_22"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_23"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_24"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_25"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_26"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_27"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_28"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_29"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_30"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_31"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_32"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_33"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_34"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_1"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_2"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_3"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_4"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_5"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_6"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_7"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_8"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_9"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_10"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_11"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_12"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_13"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_14"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_15"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_16"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_17"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_18"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_19"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_20"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_21"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_22"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_23"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_24"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_25"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_26"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_27"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_28"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_29"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_30"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_31"]: THREE.Mesh;
    ["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_32"]: THREE.Mesh;
    Floors_1: THREE.Mesh;
    Floors_1_1: THREE.Mesh;
    Floors_1_2: THREE.Mesh;
    Floors_1_3: THREE.Mesh;
    Floors_1_4: THREE.Mesh;
    Floors_1_5: THREE.Mesh;
    Floors_1_6: THREE.Mesh;
    Floors_1_7: THREE.Mesh;
    Floors_1_8: THREE.Mesh;
    Floors_1_9: THREE.Mesh;
    Floors_1_10: THREE.Mesh;
    Floors_1_11: THREE.Mesh;
    Floors_1_12: THREE.Mesh;
    Floors_1_13: THREE.Mesh;
  };
  materials: {
    ["Nickel-chromium"]: THREE.MeshStandardMaterial;
    ปูนฉาบสีขาว: THREE.MeshStandardMaterial;
    ["Brick, Dark Blend, Soldier"]: THREE.MeshStandardMaterial;
    ["Default Wall"]: THREE.MeshStandardMaterial;
    ลายกระเบื้องน้ำตาลบัน: THREE.MeshStandardMaterial;
    สีเทา: THREE.MeshStandardMaterial;
    ["เหล็ก สีน้ำเงิน"]: THREE.MeshStandardMaterial;
    ["กระจกใส 5 mm."]: THREE.MeshStandardMaterial;
    ลายหินขัด: THREE.MeshStandardMaterial;
    ลายกระเบื้องดินเผา: THREE.MeshStandardMaterial;
    ["Brick, Dark Blend, Running"]: THREE.MeshStandardMaterial;
    ลายบล็อก: THREE.MeshStandardMaterial;
    ปูนขาว: THREE.MeshStandardMaterial;
    ["กระเบื้องห้องน้ำชั้น 3-"]: THREE.MeshStandardMaterial;
    ลายตารางขาว: THREE.MeshStandardMaterial;
    กระเบื้องผนังห้องน้ำ: THREE.MeshStandardMaterial;
    ["กระจกใส 5 มม."]: THREE.MeshStandardMaterial;
    เหล็กสีน้ำเงิน: THREE.MeshStandardMaterial;
    Aluminum: THREE.MeshStandardMaterial;
    สีน้ำเงิน: THREE.MeshStandardMaterial;
    สีไม้สัก: THREE.MeshStandardMaterial;
    หน้าต่างใส: THREE.MeshStandardMaterial;
    ["ยาง 2"]: THREE.MeshStandardMaterial;
    ยาง: THREE.MeshStandardMaterial;
    Concrete: THREE.MeshStandardMaterial;
    ["วัสดุคัดเลือก 2"]: THREE.MeshStandardMaterial;
    วัสดุคัดเลือก: THREE.MeshStandardMaterial;
    ชั้นดินเดิม: THREE.MeshStandardMaterial;
    ไม้: THREE.MeshStandardMaterial;
    ไม้อัด: THREE.MeshStandardMaterial;
    ไม้เนื้อแข็ง: THREE.MeshStandardMaterial;
    ["PVC, Flexible"]: THREE.MeshStandardMaterial;
    อะลูมิเนียม: THREE.MeshStandardMaterial;
    กระจกใส: THREE.MeshStandardMaterial;
    ["Default New Material"]: THREE.MeshStandardMaterial;
    เหล็ก: THREE.MeshStandardMaterial;
    น้ำเงินเงา: THREE.MeshStandardMaterial;
    เหล็กเคลือบเงา: THREE.MeshStandardMaterial;
    ["เหล็กสีน้ำเหงิน น8"]: THREE.MeshStandardMaterial;
    ดำ: THREE.MeshStandardMaterial;
    กรอบลิฟต์: THREE.MeshStandardMaterial;
    เทา: THREE.MeshStandardMaterial;
    สีขาว: THREE.MeshStandardMaterial;
    Glass: THREE.MeshStandardMaterial;
    ไม้วอลนัท: THREE.MeshStandardMaterial;
    ["Glass - Ketcham - Mirror"]: THREE.MeshStandardMaterial;
    ["Steel, 45-345"]: THREE.MeshStandardMaterial;
    สีแดง: THREE.MeshStandardMaterial;
    สีทอง: THREE.MeshStandardMaterial;
    สีดำ: THREE.MeshStandardMaterial;
    ["Nickel-chromium.001"]: THREE.MeshStandardMaterial;
    ["ปูนฉาบสีขาว.001"]: THREE.MeshStandardMaterial;
    ["Default Wall.001"]: THREE.MeshStandardMaterial;
    ["ลายบล็อก.001"]: THREE.MeshStandardMaterial;
    ["ลายหินขัด.001"]: THREE.MeshStandardMaterial;
    ["ลายกระเบื้องดินเผา ม้"]: THREE.MeshStandardMaterial;
    ลายกระเบื้องน้ำตาลบ: THREE.MeshStandardMaterial;
    ["Brick, Dark Blend, Soldier.001"]: THREE.MeshStandardMaterial;
    ["PVC, Flexible.001"]: THREE.MeshStandardMaterial;
    ["ปูนขาว.001"]: THREE.MeshStandardMaterial;
    ["กระจกใส 5 มม..001"]: THREE.MeshStandardMaterial;
    ["เหล็ก สีน้ำเงิน.001"]: THREE.MeshStandardMaterial;
    ["Aluminum.001"]: THREE.MeshStandardMaterial;
    ["สีน้ำเงิน.001"]: THREE.MeshStandardMaterial;
    ["สีไม้สัก.001"]: THREE.MeshStandardMaterial;
    ["หน้าต่างใส.001"]: THREE.MeshStandardMaterial;
    ["ไม้เนื้อแข็ง.001"]: THREE.MeshStandardMaterial;
    ["เหล็กสีน้ำเงิน.001"]: THREE.MeshStandardMaterial;
    ["ไม้.001"]: THREE.MeshStandardMaterial;
    ["อะลูมิเนียม.001"]: THREE.MeshStandardMaterial;
    ["กระจกใส.001"]: THREE.MeshStandardMaterial;
    ["Default New Material.001"]: THREE.MeshStandardMaterial;
    ["ไม้อัด.001"]: THREE.MeshStandardMaterial;
    ["เหล็กเคลือบเงา.001"]: THREE.MeshStandardMaterial;
    ["เหล็กสีน้ำเหงิน น8.001"]: THREE.MeshStandardMaterial;
    ["ดำ.001"]: THREE.MeshStandardMaterial;
    ["กรอบลิฟต์.001"]: THREE.MeshStandardMaterial;
    ["เทา.001"]: THREE.MeshStandardMaterial;
    ["ลายตารางขาว.001"]: THREE.MeshStandardMaterial;
    กระเบื้องห้องน้ำชั้: THREE.MeshStandardMaterial;
    Aluminium: THREE.MeshStandardMaterial;
    ["Gypsum Wall Board"]: THREE.MeshStandardMaterial;
    ["Brick, Dark Blend, Running.001"]: THREE.MeshStandardMaterial;
    ["สีขาว.001"]: THREE.MeshStandardMaterial;
    ["Glass - Ketcham - Mirror.001"]: THREE.MeshStandardMaterial;
    ["Steel, 45-345.001"]: THREE.MeshStandardMaterial;
    ["สีเทา.001"]: THREE.MeshStandardMaterial;
    ["กระจกใส 5 mm..001"]: THREE.MeshStandardMaterial;
    ["Nickel-chromium.002"]: THREE.MeshStandardMaterial;
    ["ลายบล็อก.002"]: THREE.MeshStandardMaterial;
    ["ปูนฉาบสีขาว.002"]: THREE.MeshStandardMaterial;
    ["Default Wall.002"]: THREE.MeshStandardMaterial;
    ["ลายหินขัด.002"]: THREE.MeshStandardMaterial;
    ["Concrete, Cast In Situ"]: THREE.MeshStandardMaterial;
    ["ผนังอิฐห้องน้ำ 3 เหลียม"]: THREE.MeshStandardMaterial;
    ["ลายกระเบื้องน้ำตาลบ.001"]: THREE.MeshStandardMaterial;
    ["Brick, Dark Blend, Soldier.002"]: THREE.MeshStandardMaterial;
    ["กระเบื้องห้องน้ำชั้.001"]: THREE.MeshStandardMaterial;
    ลายไม้อัดสัก: THREE.MeshStandardMaterial;
    ["PVC, Flexible.002"]: THREE.MeshStandardMaterial;
    ["ปูนขาว.002"]: THREE.MeshStandardMaterial;
    ["กระจกใส 5 มม..002"]: THREE.MeshStandardMaterial;
    ["เหล็ก สีน้ำเงิน.002"]: THREE.MeshStandardMaterial;
    ["ไม้.002"]: THREE.MeshStandardMaterial;
    ["ดำ.002"]: THREE.MeshStandardMaterial;
    ["กรอบลิฟต์.002"]: THREE.MeshStandardMaterial;
    ["เทา.002"]: THREE.MeshStandardMaterial;
    ["Aluminium.001"]: THREE.MeshStandardMaterial;
    ["Gypsum Wall Board.001"]: THREE.MeshStandardMaterial;
    ["Aluminum.002"]: THREE.MeshStandardMaterial;
    ["ไม้อัด.002"]: THREE.MeshStandardMaterial;
    ["ไม้เนื้อแข็ง.002"]: THREE.MeshStandardMaterial;
    ["Glass.001"]: THREE.MeshStandardMaterial;
    ["อะลูมิเนียม.002"]: THREE.MeshStandardMaterial;
    ["กระจกใส.002"]: THREE.MeshStandardMaterial;
    ["Default New Material.002"]: THREE.MeshStandardMaterial;
    ["ลายตารางขาว.002"]: THREE.MeshStandardMaterial;
    ["เหล็กเคลือบเงา.002"]: THREE.MeshStandardMaterial;
    ["เหล็กสีน้ำเหงิน น8.002"]: THREE.MeshStandardMaterial;
    ["Glass - Ketcham - Mirror.002"]: THREE.MeshStandardMaterial;
    ["Steel, 45-345.002"]: THREE.MeshStandardMaterial;
    ["สีเทา.002"]: THREE.MeshStandardMaterial;
    ["กระจกใส 5 mm..002"]: THREE.MeshStandardMaterial;
    ["Nickel-chromium.003"]: THREE.MeshStandardMaterial;
    ["ปูนฉาบสีขาว.003"]: THREE.MeshStandardMaterial;
    ["Default Wall.003"]: THREE.MeshStandardMaterial;
    ["ลายกระเบื้องดินเผา ม"]: THREE.MeshStandardMaterial;
    ["ลายหินขัด.003"]: THREE.MeshStandardMaterial;
    ["ผนังอิฐห้องน้ำ 3 เหลี"]: THREE.MeshStandardMaterial;
    ["ลายบล็อก.003"]: THREE.MeshStandardMaterial;
    ["Concrete, Cast In Situ.001"]: THREE.MeshStandardMaterial;
    ["กระเบื้องห้องน้ำชั้.002"]: THREE.MeshStandardMaterial;
    ["ลายตารางขาว.003"]: THREE.MeshStandardMaterial;
    ["ลายกระเบื้องน้ำตาลบ.002"]: THREE.MeshStandardMaterial;
    ["Brick, Dark Blend, Soldier.003"]: THREE.MeshStandardMaterial;
    ["PVC, Flexible.003"]: THREE.MeshStandardMaterial;
    ["ปูนขาว.003"]: THREE.MeshStandardMaterial;
    ["กระจกใส 5 มม..003"]: THREE.MeshStandardMaterial;
    ["เหล็ก สีน้ำเงิน.003"]: THREE.MeshStandardMaterial;
    ["ไม้.003"]: THREE.MeshStandardMaterial;
    ["ดำ.003"]: THREE.MeshStandardMaterial;
    ["กรอบลิฟต์.003"]: THREE.MeshStandardMaterial;
    ["เทา.003"]: THREE.MeshStandardMaterial;
    ["Aluminum.003"]: THREE.MeshStandardMaterial;
    ["ไม้เนื้อแข็ง.003"]: THREE.MeshStandardMaterial;
    ["ไม้อัด.003"]: THREE.MeshStandardMaterial;
    ["Aluminium.002"]: THREE.MeshStandardMaterial;
    ["Gypsum Wall Board.002"]: THREE.MeshStandardMaterial;
    ["เหล็กเคลือบเงา.003"]: THREE.MeshStandardMaterial;
    ["เหล็กสีน้ำเหงิน น8.003"]: THREE.MeshStandardMaterial;
    ["กระจกใส.003"]: THREE.MeshStandardMaterial;
    ["อะลูมิเนียม.003"]: THREE.MeshStandardMaterial;
    ["Glass - Ketcham - Mirror.003"]: THREE.MeshStandardMaterial;
    ["Steel, 45-345.003"]: THREE.MeshStandardMaterial;
    ["สีเทา.003"]: THREE.MeshStandardMaterial;
    ["กระจกใส 5 mm..003"]: THREE.MeshStandardMaterial;
    ["Roofing, Tile"]: THREE.MeshStandardMaterial;
    ["ปูนฉาบสีขาว.004"]: THREE.MeshStandardMaterial;
    ["Default Wall.004"]: THREE.MeshStandardMaterial;
    ["Concrete, Cast In Situ.002"]: THREE.MeshStandardMaterial;
    ["ลายหินขัด.004"]: THREE.MeshStandardMaterial;
    ปูนฉาบผิวแบบขรุขระ: THREE.MeshStandardMaterial;
    ["Brick, Dark Blend, Soldier.004"]: THREE.MeshStandardMaterial;
    ["Softwood, Lumber"]: THREE.MeshStandardMaterial;
    ["Roofing, Tile(1)"]: THREE.MeshStandardMaterial;
    ["เหล็ก.001"]: THREE.MeshStandardMaterial;
    ["น้ำเงินเงา.001"]: THREE.MeshStandardMaterial;
    ["สีเทา.004"]: THREE.MeshStandardMaterial;
    ["เหล็ก สีน้ำเงิน.004"]: THREE.MeshStandardMaterial;
    ["กระจกใส 5 mm..004"]: THREE.MeshStandardMaterial;
  };
};

export const en117Floors = [
  "EN11701",
  "EN11702",
  "EN11703",
  "EN11704",
] as const;

export type EN117Floor = (typeof en117Floors)[number];

type Props = JSX.IntrinsicElements["group"] & {
  isManage: boolean;
};

export default function Model(props: Props) {
  const { nodes, materials } = useGLTF(
    "/models/building/en117/en117-building.glb"
  ) as GLTFResult;
  const [hover, setHover] = useState<EN117Floor | null>(null);
  const { select, setSelect } = useEN117Store((state) => state);
  const [floorDetail, setFloorDetail] = useState<IFloorDetails | null>(null);

  const handleObjectHover = useCallback((object: EN117Floor | null) => {
    setHover(object);
  }, []);

  const handleObjectSelect = useCallback(
    (object: EN117Floor) => {
      setSelect(object);
    },
    [setSelect]
  );

  useEffect(() => {
    const fetchFloorDetail = async () => {
      const data = await getData(
        `buildingFloorDetail/${select?.toUpperCase()}`
      );
      setFloorDetail(data);
    };

    fetchFloorDetail();
  }, [select]);

  const renderModalDetail = (floorCode: string) => {
    const isFloorActive = getFloorActiveStatus(
      select?.substring(0, 5),
      select as string
    );
    if (select === floorCode && !props.isManage) {
      return (
        <Html distanceFactor={60}>
          <div className="pt-[10px] transform translate-x-[80%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ชั้น ${floorCode.substring(5, 7)} - ${floorCode}`}
              </label>
              {isFloorActive && (
                <Link href={`/floor/${floorCode.toUpperCase()}`} target="_blank">
                  <Button variant={"ghost"} size={"icon"}>
                    <ExternalLink className="size-5" />
                  </Button>
                </Link>
              )}
            </div>
            {renderFloorDetail()}
          </div>
        </Html>
      );
    }
  };

  const renderFloorDetail = () => {
    if (floorDetail) {
      return (
        <Table className="border rounded-md">
          <TableBody>
            <TableRow>
              <TableCell className="p-2">Building Code</TableCell>
              <TableCell className="p-2">
                {floorDetail?.buildingCode || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Floor</TableCell>
              <TableCell className="p-2">
                {floorDetail?.floorNumber || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Meter Energy</TableCell>
              <TableCell className="p-2">
                {floorDetail?.floorMeter || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Meter Power</TableCell>
              <TableCell className="p-2">
                {floorDetail?.floorPower || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Average PM 2.5</TableCell>
              <TableCell className="p-2">
                {floorDetail?.averagefloorPM25 || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Average Temperature</TableCell>
              <TableCell className="p-2">
                {floorDetail?.averagefloorTemp || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Average Humidity</TableCell>
              <TableCell className="p-2">
                {floorDetail?.averagefloorHumidity || "-"}
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      );
    }
  };

  return (
    <group {...props} dispose={null}>
      <Select
        name="EN11701"
        enabled={hover === "EN11701" || select === "EN11701"}
        onPointerOver={(e) => {
          e.stopPropagation();
          handleObjectHover("EN11701");
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          handleObjectHover(null);
        }}
        onClick={(e) => {
          e.stopPropagation();
          handleObjectSelect("EN11701");
        }}
        position={[-4.153, 1.836, 0.445]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.3}
      >
        {renderModalDetail("EN11701")}
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)"].geometry
          }
          material={materials["Nickel-chromium"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_1"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_1"].geometry
          }
          material={materials.ปูนฉาบสีขาว}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_2"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_2"].geometry
          }
          material={materials["Brick, Dark Blend, Soldier"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_3"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_3"].geometry
          }
          material={materials["Default Wall"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_4"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_4"].geometry
          }
          material={materials.ลายกระเบื้องน้ำตาลบัน}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_5"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_5"].geometry
          }
          material={materials.สีเทา}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_6"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_6"].geometry
          }
          material={materials["เหล็ก สีน้ำเงิน"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_7"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_7"].geometry
          }
          material={materials["กระจกใส 5 mm."]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_8"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_8"].geometry
          }
          material={materials.ลายหินขัด}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_9"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_9"].geometry
          }
          material={materials.ลายกระเบื้องดินเผา}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_10"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_10"].geometry
          }
          material={materials["Brick, Dark Blend, Running"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_11"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_11"].geometry
          }
          material={materials.ลายบล็อก}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_12"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_12"].geometry
          }
          material={materials.ปูนขาว}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_13"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_13"].geometry
          }
          material={materials["กระเบื้องห้องน้ำชั้น 3-"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_14"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_14"].geometry
          }
          material={materials.ลายตารางขาว}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_15"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_15"].geometry
          }
          material={materials.กระเบื้องผนังห้องน้ำ}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_16"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_16"].geometry
          }
          material={materials["กระจกใส 5 มม."]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_17"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_17"].geometry
          }
          material={materials.เหล็กสีน้ำเงิน}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_18"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_18"].geometry
          }
          material={materials.Aluminum}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_19"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_19"].geometry
          }
          material={materials.สีน้ำเงิน}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_20"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_20"].geometry
          }
          material={materials.สีไม้สัก}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_21"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_21"].geometry
          }
          material={materials.หน้าต่างใส}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_22"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_22"].geometry
          }
          material={materials["ยาง 2"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_23"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_23"].geometry
          }
          material={materials.ยาง}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_24"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_24"].geometry
          }
          material={materials.Concrete}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_25"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_25"].geometry
          }
          material={materials["วัสดุคัดเลือก 2"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_26"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_26"].geometry
          }
          material={materials.วัสดุคัดเลือก}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_27"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_27"].geometry
          }
          material={materials.ชั้นดินเดิม}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_28"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_28"].geometry
          }
          material={materials.ไม้}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_29"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_29"].geometry
          }
          material={materials.ไม้อัด}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_30"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_30"].geometry
          }
          material={materials.ไม้เนื้อแข็ง}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_31"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_31"].geometry
          }
          material={materials["PVC, Flexible"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_32"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_32"].geometry
          }
          material={materials.อะลูมิเนียม}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_33"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_33"].geometry
          }
          material={materials.กระจกใส}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_34"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_34"].geometry
          }
          material={materials["Default New Material"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_35"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_35"].geometry
          }
          material={materials.เหล็ก}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_36"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_36"].geometry
          }
          material={materials.น้ำเงินเงา}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_37"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_37"].geometry
          }
          material={materials.เหล็กเคลือบเงา}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_38"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_38"].geometry
          }
          material={materials["เหล็กสีน้ำเหงิน น8"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_39"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_39"].geometry
          }
          material={materials.ดำ}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_40"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_40"].geometry
          }
          material={materials.กรอบลิฟต์}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_41"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_41"].geometry
          }
          material={materials.เทา}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_42"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_42"].geometry
          }
          material={materials.สีขาว}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_43"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_43"].geometry
          }
          material={materials.Glass}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_44"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_44"].geometry
          }
          material={materials.ไม้วอลนัท}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_45"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_45"].geometry
          }
          material={materials["Glass - Ketcham - Mirror"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_46"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_46"].geometry
          }
          material={materials["Steel, 45-345"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_47"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_47"].geometry
          }
          material={materials.สีแดง}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_48"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_48"].geometry
          }
          material={materials.สีทอง}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_49"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)_49"].geometry
          }
          material={materials.สีดำ}
        />
      </Select>
      <Select
        name="EN11702"
        enabled={hover === "EN11702" || select === "EN11702"}
        onPointerOver={(e) => {
          e.stopPropagation();
          handleObjectHover("EN11702");
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          handleObjectHover(null);
        }}
        onClick={(e) => {
          e.stopPropagation();
          handleObjectSelect("EN11702");
        }}
        position={[-1.175, 5.133, 0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.3}
      >
        {renderModalDetail("EN11702")}
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002"].geometry
          }
          material={materials["Nickel-chromium.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_1"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_1"]
              .geometry
          }
          material={materials["ปูนฉาบสีขาว.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_2"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_2"]
              .geometry
          }
          material={materials["Default Wall.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_3"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_3"]
              .geometry
          }
          material={materials["ลายบล็อก.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_4"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_4"]
              .geometry
          }
          material={materials["ลายหินขัด.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_5"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_5"]
              .geometry
          }
          material={materials["ลายกระเบื้องดินเผา ม้"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_6"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_6"]
              .geometry
          }
          material={materials.ลายกระเบื้องน้ำตาลบ}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_7"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_7"]
              .geometry
          }
          material={materials["Brick, Dark Blend, Soldier.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_8"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_8"]
              .geometry
          }
          material={materials["PVC, Flexible.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_9"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_9"]
              .geometry
          }
          material={materials["ปูนขาว.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_10"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_10"]
              .geometry
          }
          material={materials["กระจกใส 5 มม..001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_11"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_11"]
              .geometry
          }
          material={materials["เหล็ก สีน้ำเงิน.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_12"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_12"]
              .geometry
          }
          material={materials["Aluminum.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_13"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_13"]
              .geometry
          }
          material={materials["สีน้ำเงิน.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_14"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_14"]
              .geometry
          }
          material={materials["สีไม้สัก.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_15"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_15"]
              .geometry
          }
          material={materials["หน้าต่างใส.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_16"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_16"]
              .geometry
          }
          material={materials["ไม้เนื้อแข็ง.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_17"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_17"]
              .geometry
          }
          material={materials["เหล็กสีน้ำเงิน.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_18"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_18"]
              .geometry
          }
          material={materials["ไม้.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_19"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_19"]
              .geometry
          }
          material={materials["อะลูมิเนียม.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_20"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_20"]
              .geometry
          }
          material={materials["กระจกใส.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_21"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_21"]
              .geometry
          }
          material={materials["Default New Material.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_22"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_22"]
              .geometry
          }
          material={materials["ไม้อัด.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_23"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_23"]
              .geometry
          }
          material={materials["เหล็กเคลือบเงา.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_24"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_24"]
              .geometry
          }
          material={materials["เหล็กสีน้ำเหงิน น8.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_25"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_25"]
              .geometry
          }
          material={materials["ดำ.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_26"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_26"]
              .geometry
          }
          material={materials["กรอบลิฟต์.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_27"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_27"]
              .geometry
          }
          material={materials["เทา.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_28"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_28"]
              .geometry
          }
          material={materials["ลายตารางขาว.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_29"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_29"]
              .geometry
          }
          material={materials.กระเบื้องห้องน้ำชั้}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_30"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_30"]
              .geometry
          }
          material={materials.Aluminium}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_31"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_31"]
              .geometry
          }
          material={materials["Gypsum Wall Board"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_32"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_32"]
              .geometry
          }
          material={materials["Brick, Dark Blend, Running.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_33"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_33"]
              .geometry
          }
          material={materials["สีขาว.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_34"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_34"]
              .geometry
          }
          material={materials["Glass - Ketcham - Mirror.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_35"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_35"]
              .geometry
          }
          material={materials["Steel, 45-345.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_36"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_36"]
              .geometry
          }
          material={materials["สีเทา.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_37"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)002_37"]
              .geometry
          }
          material={materials["กระจกใส 5 mm..001"]}
        />
      </Select>
      <Select
        name="EN11703"
        enabled={hover === "EN11703" || select === "EN11703"}
        onPointerOver={(e) => {
          e.stopPropagation();
          handleObjectHover("EN11703");
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          handleObjectHover(null);
        }}
        onClick={(e) => {
          e.stopPropagation();
          handleObjectSelect("EN11703");
        }}
        position={[-2.159, 8.649, 5.685]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.3}
      >
        {renderModalDetail("EN11703")}
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004"].geometry
          }
          material={materials["Nickel-chromium.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_1"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_1"]
              .geometry
          }
          material={materials["ลายบล็อก.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_2"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_2"]
              .geometry
          }
          material={materials["ปูนฉาบสีขาว.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_3"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_3"]
              .geometry
          }
          material={materials["Default Wall.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_4"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_4"]
              .geometry
          }
          material={materials["ลายหินขัด.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_5"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_5"]
              .geometry
          }
          material={materials["Concrete, Cast In Situ"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_6"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_6"]
              .geometry
          }
          material={materials["ผนังอิฐห้องน้ำ 3 เหลียม"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_7"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_7"]
              .geometry
          }
          material={materials["ลายกระเบื้องน้ำตาลบ.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_8"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_8"]
              .geometry
          }
          material={materials["Brick, Dark Blend, Soldier.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_9"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_9"]
              .geometry
          }
          material={materials["กระเบื้องห้องน้ำชั้.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_10"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_10"]
              .geometry
          }
          material={materials.ลายไม้อัดสัก}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_11"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_11"]
              .geometry
          }
          material={materials["PVC, Flexible.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_12"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_12"]
              .geometry
          }
          material={materials["ปูนขาว.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_13"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_13"]
              .geometry
          }
          material={materials["กระจกใส 5 มม..002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_14"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_14"]
              .geometry
          }
          material={materials["เหล็ก สีน้ำเงิน.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_15"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_15"]
              .geometry
          }
          material={materials["ไม้.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_16"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_16"]
              .geometry
          }
          material={materials["ดำ.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_17"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_17"]
              .geometry
          }
          material={materials["กรอบลิฟต์.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_18"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_18"]
              .geometry
          }
          material={materials["เทา.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_19"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_19"]
              .geometry
          }
          material={materials["Aluminium.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_20"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_20"]
              .geometry
          }
          material={materials["Gypsum Wall Board.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_21"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_21"]
              .geometry
          }
          material={materials["Aluminum.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_22"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_22"]
              .geometry
          }
          material={materials["ไม้อัด.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_23"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_23"]
              .geometry
          }
          material={materials["ไม้เนื้อแข็ง.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_24"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_24"]
              .geometry
          }
          material={materials["Glass.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_25"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_25"]
              .geometry
          }
          material={materials["อะลูมิเนียม.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_26"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_26"]
              .geometry
          }
          material={materials["กระจกใส.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_27"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_27"]
              .geometry
          }
          material={materials["Default New Material.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_28"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_28"]
              .geometry
          }
          material={materials["ลายตารางขาว.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_29"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_29"]
              .geometry
          }
          material={materials["เหล็กเคลือบเงา.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_30"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_30"]
              .geometry
          }
          material={materials["เหล็กสีน้ำเหงิน น8.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_31"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_31"]
              .geometry
          }
          material={materials["Glass - Ketcham - Mirror.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_32"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_32"]
              .geometry
          }
          material={materials["Steel, 45-345.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_33"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_33"]
              .geometry
          }
          material={materials["สีเทา.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_34"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)004_34"]
              .geometry
          }
          material={materials["กระจกใส 5 mm..002"]}
        />
      </Select>
      <Select
        name="EN11704"
        enabled={hover === "EN11704" || select === "EN11704"}
        onPointerOver={(e) => {
          e.stopPropagation();
          handleObjectHover("EN11704");
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          handleObjectHover(null);
        }}
        onClick={(e) => {
          e.stopPropagation();
          handleObjectSelect("EN11704");
        }}
        position={[-1.183, 12.051, 5.117]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.3}
      >
        {renderModalDetail("EN11704")}
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009"].geometry
          }
          material={materials["Nickel-chromium.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_1"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_1"]
              .geometry
          }
          material={materials["ปูนฉาบสีขาว.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_2"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_2"]
              .geometry
          }
          material={materials["Default Wall.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_3"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_3"]
              .geometry
          }
          material={materials["ลายกระเบื้องดินเผา ม"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_4"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_4"]
              .geometry
          }
          material={materials["ลายหินขัด.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_5"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_5"]
              .geometry
          }
          material={materials["ผนังอิฐห้องน้ำ 3 เหลี"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_6"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_6"]
              .geometry
          }
          material={materials["ลายบล็อก.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_7"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_7"]
              .geometry
          }
          material={materials["Concrete, Cast In Situ.001"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_8"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_8"]
              .geometry
          }
          material={materials["กระเบื้องห้องน้ำชั้.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_9"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_9"]
              .geometry
          }
          material={materials["ลายตารางขาว.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_10"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_10"]
              .geometry
          }
          material={materials["ลายกระเบื้องน้ำตาลบ.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_11"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_11"]
              .geometry
          }
          material={materials["Brick, Dark Blend, Soldier.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_12"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_12"]
              .geometry
          }
          material={materials["PVC, Flexible.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_13"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_13"]
              .geometry
          }
          material={materials["ปูนขาว.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_14"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_14"]
              .geometry
          }
          material={materials["กระจกใส 5 มม..003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_15"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_15"]
              .geometry
          }
          material={materials["เหล็ก สีน้ำเงิน.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_16"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_16"]
              .geometry
          }
          material={materials["ไม้.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_17"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_17"]
              .geometry
          }
          material={materials["ดำ.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_18"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_18"]
              .geometry
          }
          material={materials["กรอบลิฟต์.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_19"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_19"]
              .geometry
          }
          material={materials["เทา.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_20"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_20"]
              .geometry
          }
          material={materials["Aluminum.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_21"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_21"]
              .geometry
          }
          material={materials["ไม้เนื้อแข็ง.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_22"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_22"]
              .geometry
          }
          material={materials["ไม้อัด.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_23"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_23"]
              .geometry
          }
          material={materials["Aluminium.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_24"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_24"]
              .geometry
          }
          material={materials["Gypsum Wall Board.002"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_25"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_25"]
              .geometry
          }
          material={materials["เหล็กเคลือบเงา.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_26"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_26"]
              .geometry
          }
          material={materials["เหล็กสีน้ำเหงิน น8.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_27"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_27"]
              .geometry
          }
          material={materials["กระจกใส.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_28"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_28"]
              .geometry
          }
          material={materials["อะลูมิเนียม.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_29"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_29"]
              .geometry
          }
          material={materials["Glass - Ketcham - Mirror.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_30"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_30"]
              .geometry
          }
          material={materials["Steel, 45-345.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_31"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_31"]
              .geometry
          }
          material={materials["สีเทา.003"]}
        />
        <mesh
          name="COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_32"
          geometry={
            nodes["COTTO_Tissue_Holder_With_Cover_CROSS_CT0049(HM)009_32"]
              .geometry
          }
          material={materials["กระจกใส 5 mm..003"]}
        />
      </Select>
      <group
        name="EN117RF"
        position={[1.605, 15.351, 8.804]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.3}
      >
        <mesh
          name="Floors_1"
          geometry={nodes.Floors_1.geometry}
          material={materials["Roofing, Tile"]}
        />
        <mesh
          name="Floors_1_1"
          geometry={nodes.Floors_1_1.geometry}
          material={materials["ปูนฉาบสีขาว.004"]}
        />
        <mesh
          name="Floors_1_2"
          geometry={nodes.Floors_1_2.geometry}
          material={materials["Default Wall.004"]}
        />
        <mesh
          name="Floors_1_3"
          geometry={nodes.Floors_1_3.geometry}
          material={materials["Concrete, Cast In Situ.002"]}
        />
        <mesh
          name="Floors_1_4"
          geometry={nodes.Floors_1_4.geometry}
          material={materials["ลายหินขัด.004"]}
        />
        <mesh
          name="Floors_1_5"
          geometry={nodes.Floors_1_5.geometry}
          material={materials.ปูนฉาบผิวแบบขรุขระ}
        />
        <mesh
          name="Floors_1_6"
          geometry={nodes.Floors_1_6.geometry}
          material={materials["Brick, Dark Blend, Soldier.004"]}
        />
        <mesh
          name="Floors_1_7"
          geometry={nodes.Floors_1_7.geometry}
          material={materials["Softwood, Lumber"]}
        />
        <mesh
          name="Floors_1_8"
          geometry={nodes.Floors_1_8.geometry}
          material={materials["Roofing, Tile(1)"]}
        />
        <mesh
          name="Floors_1_9"
          geometry={nodes.Floors_1_9.geometry}
          material={materials["เหล็ก.001"]}
        />
        <mesh
          name="Floors_1_10"
          geometry={nodes.Floors_1_10.geometry}
          material={materials["น้ำเงินเงา.001"]}
        />
        <mesh
          name="Floors_1_11"
          geometry={nodes.Floors_1_11.geometry}
          material={materials["สีเทา.004"]}
        />
        <mesh
          name="Floors_1_12"
          geometry={nodes.Floors_1_12.geometry}
          material={materials["เหล็ก สีน้ำเงิน.004"]}
        />
        <mesh
          name="Floors_1_13"
          geometry={nodes.Floors_1_13.geometry}
          material={materials["กระจกใส 5 mm..004"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/building/en117/en117-building.glb");
