/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/building/en105/en105-1.glb -t -k -E -R -f 
*/
"use client";

import * as THREE from 'three'
import React, { useCallback, useEffect, useRef, useState } from 'react'
import { Html, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { usePathname } from 'next/navigation'
import { IModalRoomDetails } from '@/types/model'
import { useContourMenuStore } from '@/stores/use-menu-store'
import { configs } from '@/lib/configs'
import { useEN10501Store } from '@/stores/use-floor-store'
import { getData } from '@/actions/actions'
import Link from 'next/link'
import { Button } from '@/components/shadcn-ui/button'
import { ExternalLink } from 'lucide-react'
import { Table, TableBody, TableCell, TableRow } from '@/components/shadcn-ui/table'
import { Select } from '@react-three/postprocessing'
import { getColorFromScale } from '@/lib/utils'

type GLTFResult = GLTF & {
  nodes: {
    EN1050101_1: THREE.Mesh
    EN1050101_2: THREE.Mesh
    EN1050101_3: THREE.Mesh
    EN1050101_4: THREE.Mesh
    EN1050101_5: THREE.Mesh
    EN1050101_6: THREE.Mesh
    EN1050101_7: THREE.Mesh
    EN1050102_1: THREE.Mesh
    EN1050102_2: THREE.Mesh
    EN1050102_3: THREE.Mesh
    EN1050102_4: THREE.Mesh
    EN1050102_5: THREE.Mesh
    EN1050103_1: THREE.Mesh
    EN1050103_2: THREE.Mesh
    EN1050103_3: THREE.Mesh
    EN1050103_4: THREE.Mesh
    EN1050103_5: THREE.Mesh
    EN1050103_6: THREE.Mesh
    EN1050103_7: THREE.Mesh
    EN1050103_8: THREE.Mesh
    EN1050104_1: THREE.Mesh
    EN1050104_2: THREE.Mesh
    EN1050104_3: THREE.Mesh
    EN1050104_4: THREE.Mesh
    EN1050104_5: THREE.Mesh
    EN1050105_1: THREE.Mesh
    EN1050105_2: THREE.Mesh
    EN1050105_3: THREE.Mesh
    EN1050105_4: THREE.Mesh
    EN1050105_5: THREE.Mesh
    EN1050106_1: THREE.Mesh
    EN1050106_2: THREE.Mesh
    EN1050106_3: THREE.Mesh
    EN1050106_4: THREE.Mesh
    EN1050106_5: THREE.Mesh
    EN1050107_1: THREE.Mesh
    EN1050107_2: THREE.Mesh
    EN1050107_3: THREE.Mesh
    EN1050107_4: THREE.Mesh
    EN1050107_5: THREE.Mesh
    EN1050107_6: THREE.Mesh
    EN1050107_7: THREE.Mesh
    EN1050108_1: THREE.Mesh
    EN1050108_2: THREE.Mesh
    EN1050108_3: THREE.Mesh
    EN1050108_4: THREE.Mesh
    EN1050108_5: THREE.Mesh
    EN1050108_6: THREE.Mesh
    EN1050108_7: THREE.Mesh
    EN1050109_1: THREE.Mesh
    EN1050109_2: THREE.Mesh
    EN1050109_3: THREE.Mesh
    EN1050109_4: THREE.Mesh
    EN1050109_5: THREE.Mesh
    EN1050109_6: THREE.Mesh
    EN1050109_7: THREE.Mesh
    EN1050199_1: THREE.Mesh
    EN1050199_2: THREE.Mesh
    EN1050199_3: THREE.Mesh
    EN1050199_4: THREE.Mesh
    EN1050199_5: THREE.Mesh
    EN1050199_6: THREE.Mesh
    EN1050199_7: THREE.Mesh
    EN1050199_8: THREE.Mesh
    EN1050199_9: THREE.Mesh
    EN1050199_10: THREE.Mesh
    EN1050199_11: THREE.Mesh
    EN1050199_12: THREE.Mesh
    EN1050199_13: THREE.Mesh
    EN1050199_14: THREE.Mesh
    Plane: THREE.Mesh
  }
  materials: {
    ['Concrete, Cast-in-Place gray']: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['Default Floor 02']: THREE.MeshStandardMaterial
    ['Concrete wall']: THREE.MeshStandardMaterial
    ['Default Wall']: THREE.MeshStandardMaterial
    Aluminum: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    ['Concrete wall.001']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.001']: THREE.MeshStandardMaterial
    ['Default Floor 02.001']: THREE.MeshStandardMaterial
    ['Default Wall.001']: THREE.MeshStandardMaterial
    ['Glass.001']: THREE.MeshStandardMaterial
    ['Concrete wall.002']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.002']: THREE.MeshStandardMaterial
    ['Default Floor 02.002']: THREE.MeshStandardMaterial
    ['Default Wall.002']: THREE.MeshStandardMaterial
    ['Stainless steel Matt']: THREE.MeshStandardMaterial
    ['Glass.002']: THREE.MeshStandardMaterial
    Aluminium: THREE.MeshStandardMaterial
    ['Aluminum.001']: THREE.MeshStandardMaterial
    Cherry: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.003']: THREE.MeshStandardMaterial
    ['Default Floor 02.003']: THREE.MeshStandardMaterial
    ['Concrete wall.003']: THREE.MeshStandardMaterial
    ['Default Wall.003']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.004']: THREE.MeshStandardMaterial
    ['Concrete wall.004']: THREE.MeshStandardMaterial
    ['Default Wall.004']: THREE.MeshStandardMaterial
    ['Interior Floors Tile 01']: THREE.MeshStandardMaterial
    ['Cherry.001']: THREE.MeshStandardMaterial
    ['Cherry.002']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.005']: THREE.MeshStandardMaterial
    ['Concrete wall.005']: THREE.MeshStandardMaterial
    ['Default Wall.005']: THREE.MeshStandardMaterial
    ['Interior Floors Tile 01.001']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.006']: THREE.MeshStandardMaterial
    ['Concrete wall.006']: THREE.MeshStandardMaterial
    ['Default Wall.006']: THREE.MeshStandardMaterial
    ['Default Floor 02.004']: THREE.MeshStandardMaterial
    ['Wood.001']: THREE.MeshStandardMaterial
    ['Aluminum.002']: THREE.MeshStandardMaterial
    ['Glass.003']: THREE.MeshStandardMaterial
    ['Default Wall.007']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.007']: THREE.MeshStandardMaterial
    ['Default Floor 02.005']: THREE.MeshStandardMaterial
    ['Concrete wall.007']: THREE.MeshStandardMaterial
    ['Glass.004']: THREE.MeshStandardMaterial
    ['Wood.002']: THREE.MeshStandardMaterial
    ['Aluminum.003']: THREE.MeshStandardMaterial
    ['Glass.005']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.008']: THREE.MeshStandardMaterial
    ['Concrete wall.008']: THREE.MeshStandardMaterial
    ['Default Wall.008']: THREE.MeshStandardMaterial
    ['Default Floor 02.006']: THREE.MeshStandardMaterial
    ['Aluminum.004']: THREE.MeshStandardMaterial
    ['Wood.003']: THREE.MeshStandardMaterial
    ['Cherry.003']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.009']: THREE.MeshStandardMaterial
    ['Concrete wall.009']: THREE.MeshStandardMaterial
    ['Default Wall.009']: THREE.MeshStandardMaterial
    ['Default Floor 02.007']: THREE.MeshStandardMaterial
    ['Brick, Common']: THREE.MeshStandardMaterial
    ['Sliding Doors(1)']: THREE.MeshStandardMaterial
    ['Sliding Doors(2)']: THREE.MeshStandardMaterial
    ['Steel-01']: THREE.MeshStandardMaterial
    ['Aluminum.005']: THREE.MeshStandardMaterial
    ['Glass.006']: THREE.MeshStandardMaterial
    ['Wood.004']: THREE.MeshStandardMaterial
    ['Stainless steel Matt.001']: THREE.MeshStandardMaterial
    ['Aluminium.001']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export const en105Floors01 = [
  "EN1050101", "EN1050102", "EN1050103", "EN1050104", "EN1050105", "EN1050106", "EN1050107", "EN1050108", "EN1050109", "EN1050199"
] as const;

export type EN105Floor1 = typeof en105Floors01[number];

type Props = JSX.IntrinsicElements["group"] & {
  isShowLamp?: boolean;
  isShowAir?: boolean;
  isManage?: boolean;
  isFloorPage?: boolean;
  isRoomPage?: boolean;
  roomData? : any[];
  pathname?: string;
  isFloorColorChange?: boolean;
  activeAirId?: string | null;
  activeLampId?: string | null;
};

export default function EN10501Floor(props: Props) {
  const {
    isShowLamp,
    isShowAir,
    isManage,
    isFloorPage,
    isRoomPage,
    roomData,
    pathname,
    isFloorColorChange,
    activeAirId,
    activeLampId,
  } = props;

  const groupRef = useRef<any>();
  const floorId = pathname;

  const path = usePathname();
  const roomId = path.split('/room/')[1];
  
  const { nodes, materials } = useGLTF('/models/building/en105/en105-1.glb') as GLTFResult

  const [hover, setHover] = useState<EN105Floor1 | null>(null);
  const { select, setSelect } = useEN10501Store(state => (state));
  const { menuState } = useContourMenuStore();
  const [modalFloorRoomDetail, setModalFloorRoomDetail] = useState<IModalRoomDetails | null>(null);
  const [modalRoomDetail, setModalRoomDetail] = useState<any>(null);
  const [modalLampDetail, setModalLampDetail] = useState<any>(null);
  const [modalAirDetail, setModalAirDetail] = useState<any>(null);

  const modalDistance = configs.building[roomId?.substring(0, 5).toLowerCase()]?.floor?.[roomId?.substring(0, 7).toLowerCase()]?.room?.[roomId?.toLowerCase()]?.modalDistance

  const handleObjectHover = useCallback((object: EN105Floor1 | null | any) => {
    setHover(object);
  }, []);

  const handleObjectSelect = useCallback(
    (object: EN105Floor1 | null | any) => {
      setSelect(object);
    },
    [setSelect]
  );

  useEffect(() => {
    const floorContourColor = () => {
      if (!groupRef.current) return;
  
      groupRef.current.traverse((groupChild: any) => {
        if ((groupChild.isGroup || groupChild.type === 'Select') && !groupChild.name.includes('-')) {
          const roomData = props.roomData?.[groupChild.name];
  
          if (roomData && roomData.Humi_Temp_PM25) {
            // Calculate averages
            const sensors = Object.values(roomData.Humi_Temp_PM25) as Array<{
              Temp?: number;
              Humidity?: number;
              PM25?: number;
            }>;
  
            let averages: any = null;
            if (sensors.length > 1) {
              const total = sensors.reduce(
                (acc: { Temp: number; Humidity: number; PM25: number; count: number }, sensor) => {
                  acc.Temp += sensor.Temp || 0;
                  acc.Humidity += sensor.Humidity || 0;
                  acc.PM25 += sensor.PM25 || 0;
                  acc.count += 1;
                  return acc;
                },
                { Temp: 0, Humidity: 0, PM25: 0, count: 0 }
              );
  
              averages = {
                Temp: total.Temp / total.count,
                Humidity: total.Humidity / total.count,
                PM25: total.PM25 / total.count,
              };
            } else if (sensors.length === 1) {
              const sensor = sensors[0];
              averages = {
                Temp: sensor.Temp || 0,
                Humidity: sensor.Humidity || 0,
                PM25: sensor.PM25 || 0,
              };
            }
  
            if (averages) {
              // console.log(`Averages for ${groupChild.name}:`, averages);
  
              // Handle menuState
              if (menuState === null) {
                // Reset to original color
                groupChild.traverse((meshChild: any) => {
                  if (meshChild.isMesh || meshChild.isInstancedMesh) {
                    if (meshChild.material) {
                      if (Array.isArray(meshChild.material)) {
                        meshChild.material.forEach((mat: any) => {
                          if (mat.userData.originalColor) {
                            mat.color.set(mat.userData.originalColor);
                            mat.needsUpdate = true;
                          }
                        });
                      } else {
                        if (meshChild.material.userData.originalColor) {
                          meshChild.material.color.set(meshChild.material.userData.originalColor);
                          meshChild.material.needsUpdate = true;
                        }
                      }
                    }
                  }
                });
              } else {
                // Process PM2.5, Humidity, or Temperature
                const processState = (value: number, scale: any, groupName: string) => {
                  const normalizedValue = Math.max(0, Math.min(value, 1));
                  const color = getColorFromScale(normalizedValue, scale);
  
                  groupChild.traverse((meshChild: any) => {
                    if (meshChild.isMesh || meshChild.isInstancedMesh) {
                      if (
                        meshChild.material &&
                        (meshChild.material.name?.includes('Concrete, Cast-in-Place gray'))
                      ) {
                        // Save original color if not saved yet
                        if (!meshChild.material.userData.originalColor) {
                          meshChild.material.userData.originalColor = meshChild.material.color.getHex();
                        }
  
                        // Set new color
                        if (Array.isArray(meshChild.material)) {
                          meshChild.material.forEach((mat: any) => {
                            mat.color.set(color);
                            mat.needsUpdate = true;
                          });
                        } else {
                          meshChild.material.color.set(color);
                          meshChild.material.needsUpdate = true;
                        }
  
                        // console.log(`Changed color for ${meshChild.name} in ${groupName}`);
                      }
                    }
                  });
                };
  
                if (menuState === 'pm25') {
                  const pm25Value = averages.PM25 || 0;
                  processState(pm25Value / 600, configs.colorScale.pm25, groupChild.name);
                } else if (menuState === 'humidity') {
                  const humidityValue = averages.Humidity || 0;
                  processState(humidityValue / 100, configs.colorScale.humidity, groupChild.name);
                } else if (menuState === 'temperature') {
                  const tempValue = averages.Temp || 0;
                  processState(tempValue / 50, configs.colorScale.temperature, groupChild.name);
                }
              }
            }
          }
        }
      });
    };
  
    floorContourColor();
  }, [roomData, menuState]);

  useEffect(() => {
    const changeFloorColor = () => {
      if (!groupRef.current || !isFloorColorChange) return;
  
      groupRef.current.traverse((groupChild: any) => {
        groupChild.traverse((meshChild: any) => {
          if (meshChild.isMesh || meshChild.isInstancedMesh) {
            if (
              meshChild.material &&
              (meshChild.material.name?.includes('Concrete, Cast-in-Place gray'))
            ) {
              // Save original color if not saved yet
              if (!meshChild.material.userData.originalColor) {
                meshChild.material.userData.originalColor = meshChild.material.color.getHex();
              }
  
              // Change to gray color
              const grayColor = 0x959595; // Hex for gray
              if (Array.isArray(meshChild.material)) {
                meshChild.material.forEach((mat: any) => {
                  mat.color.set(grayColor);
                  mat.needsUpdate = true;
                });
              } else {
                meshChild.material.color.set(grayColor);
                meshChild.material.needsUpdate = true;
              }
            }
          }
        });
      });
    };
    changeFloorColor();
  }, [isFloorColorChange, isManage]);

  useEffect(() => {
    if (isRoomPage && !isManage && groupRef.current) {
      groupRef.current.traverse((child: any) => {
        if (child.isMesh && child.parent?.name) {
          const isMatchingRoom = child.parent.name.startsWith(roomId)
          if (Array.isArray(child.material)) {
            child.material.forEach((m: any) => {
              m.transparent = true;
              m.opacity = isMatchingRoom ? 1 : 0.3;
              m.needsUpdate = true; // Force material update
            });
          } else if (child.material) {
            child.material.transparent = true;
            child.material.opacity = isMatchingRoom ? 1 : 0.3;
            child.material.needsUpdate = true; // Force material update
          }
        }
      });
    }
  }, [isRoomPage, roomId]);

  useEffect(() => {
    const fetchFloorRoomDetail = async () => {
      if (isRoomPage) {
        if (select?.includes("L")) {
          const formattedSelect = select.replace("-", "");
          const lampData = await getData(`getLampById/${formattedSelect.toUpperCase()}`, true);
          setModalLampDetail(lampData);
        } else if (select?.includes("A")) {
          const formattedSelect = select.replace("-", "");
          const airData = await getData(`getAirById/${formattedSelect.toUpperCase()}`, true);
          setModalAirDetail(airData[0]);
        } else {
          const roomData = await getData(`roomDetail/${select?.toUpperCase()}`, true);
          setModalRoomDetail(roomData);
        }
      } else {
        const floorRoomData = await getData(`floorRoomDetail/${select?.toUpperCase()}`, true);
        setModalFloorRoomDetail(floorRoomData);
      }
    }

    fetchFloorRoomDetail();
  }, [select]);

  const renderModalDetail = (roomCode: string) => {
    if (select === roomCode && !isManage) {
      return (
        <Html distanceFactor={50}>
          <div className="pt-[10px] transform z-0 translate-x-[30%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ห้อง ${roomCode.substring(6, 9)} - ${roomCode}`}
              </label>
              <Link href={`/room/${roomCode.toUpperCase()}`} target="_blank">
                <Button variant={"ghost"} size={"icon"}>
                  <ExternalLink className="size-5" />
                </Button>
              </Link>
            </div>
            <Table className="border rounded-md">
              <TableBody>
                <TableRow>
                  <TableCell className="p-2">Building Code</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.buildingCode || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Floor</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.floorNumber || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Room</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.roomNumber || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Energy</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.roomMeter || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Power</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.roomPower || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average PM 2.5</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.averagePM25 || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Temperature</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.averageTemp ? `${modalFloorRoomDetail?.averageTemp} °C` : "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Humidity</TableCell>
                  <TableCell className="p-2">
                    {modalFloorRoomDetail?.averageHumidity ? `${modalFloorRoomDetail?.averageHumidity} %` : "-"}
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </Html>
      )
    }
  }

  const renderModalRoomDetail = (roomCode: string) => {
    if (select === roomCode && select === roomId?.toUpperCase() && !isManage) {
      return (
        <Html distanceFactor={modalDistance || 20}>
          <div className="pt-[10px] transform z-0 translate-x-[30%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ห้อง ${roomCode.substring(6, 9)} - ${roomCode}`}
              </label>
            </div>
            <Table className="border rounded-md">
              <TableBody>
                <TableRow>
                  <TableCell className="p-2">Building Code</TableCell>
                  <TableCell className="p-2">
                    {roomCode.substring(0, 5) || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Floor</TableCell>
                  <TableCell className="p-2">
                    {roomCode.substring(5, 7) || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Room</TableCell>
                  <TableCell className="p-2">
                    {roomCode.substring(6, 9) || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Number of Air Conditioners</TableCell>
                  <TableCell className="p-2">
                    {
                      configs.building[roomId.substring(0, 5).toLowerCase()]?.floor?.[roomId.substring(0, 7).toLowerCase()]?.room?.[roomId.toLowerCase()]
                      ?.airCount || "-"
                    }
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Number of Lamps</TableCell>
                  <TableCell className="p-2">
                    {
                      configs.building[roomId.substring(0, 5).toLowerCase()]?.floor?.[roomId.substring(0, 7).toLowerCase()]?.room?.[roomId.toLowerCase()]
                      ?.lampCount || "-"
                    }
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Energy</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomMeter || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Meter Power</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomPower || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average PM 2.5</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomPM25 || "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Temperature</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomTemp ? `${modalRoomDetail?.roomTemp} °C` : "-"}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="p-2">Average Humidity</TableCell>
                  <TableCell className="p-2">
                    {modalRoomDetail?.roomHumidity ? `${modalRoomDetail?.roomHumidity} %` : "-"}
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </Html>
      )
    }
  }

  return (
    <group 
      onPointerOver={(e) => {
        e.stopPropagation();
        handleObjectHover(e.object.parent?.name);
      }} 
      onPointerOut={(e) => {
        e.stopPropagation();
        handleObjectHover(null)
      }}
      onClick={(e) => {
        e.stopPropagation();
        handleObjectSelect(e.object.parent?.name)
      }}
      ref={groupRef} 
      {...props} 
      dispose={null}
    >
      <Select name="EN1050101" enabled={hover === "EN1050101" || select === "EN1050101"} position={[-17.212, 1.502, -10.014]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1050101")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1050101")}
        <mesh name="EN1050101_1" geometry={nodes.EN1050101_1.geometry} material={materials['Concrete, Cast-in-Place gray']} />
        <mesh name="EN1050101_2" geometry={nodes.EN1050101_2.geometry} material={materials.Glass} />
        <mesh name="EN1050101_3" geometry={nodes.EN1050101_3.geometry} material={materials['Default Floor 02']} />
        <mesh name="EN1050101_4" geometry={nodes.EN1050101_4.geometry} material={materials['Concrete wall']} />
        <mesh name="EN1050101_5" geometry={nodes.EN1050101_5.geometry} material={materials['Default Wall']} />
        <mesh name="EN1050101_6" geometry={nodes.EN1050101_6.geometry} material={materials.Aluminum} />
        <mesh name="EN1050101_7" geometry={nodes.EN1050101_7.geometry} material={materials.Wood} />
      </Select>
      <Select name="EN1050102" enabled={hover === "EN1050102" || select === "EN1050102"} position={[-12.078, 1.569, -11.788]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1050102")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1050102")}
        <mesh name="EN1050102_1" geometry={nodes.EN1050102_1.geometry} material={materials['Concrete wall.001']} />
        <mesh name="EN1050102_2" geometry={nodes.EN1050102_2.geometry} material={materials['Concrete, Cast-in-Place gray.001']} />
        <mesh name="EN1050102_3" geometry={nodes.EN1050102_3.geometry} material={materials['Default Floor 02.001']} />
        <mesh name="EN1050102_4" geometry={nodes.EN1050102_4.geometry} material={materials['Default Wall.001']} />
        <mesh name="EN1050102_5" geometry={nodes.EN1050102_5.geometry} material={materials['Glass.001']} />
      </Select>
      <Select name="EN1050103" enabled={hover === "EN1050103" || select === "EN1050103"} position={[6.876, 1.552, -11.873]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1050103")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1050103")}
        <mesh name="EN1050103_1" geometry={nodes.EN1050103_1.geometry} material={materials['Concrete wall.002']} />
        <mesh name="EN1050103_2" geometry={nodes.EN1050103_2.geometry} material={materials['Concrete, Cast-in-Place gray.002']} />
        <mesh name="EN1050103_3" geometry={nodes.EN1050103_3.geometry} material={materials['Default Floor 02.002']} />
        <mesh name="EN1050103_4" geometry={nodes.EN1050103_4.geometry} material={materials['Default Wall.002']} />
        <mesh name="EN1050103_5" geometry={nodes.EN1050103_5.geometry} material={materials['Stainless steel Matt']} />
        <mesh name="EN1050103_6" geometry={nodes.EN1050103_6.geometry} material={materials['Glass.002']} />
        <mesh name="EN1050103_7" geometry={nodes.EN1050103_7.geometry} material={materials.Aluminium} />
        <mesh name="EN1050103_8" geometry={nodes.EN1050103_8.geometry} material={materials['Aluminum.001']} />
      </Select>
      <Select name="EN1050104" enabled={hover === "EN1050104" || select === "EN1050104"} position={[15.234, 1.328, -11.768]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1050104")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1050104")}
        <mesh name="EN1050104_1" geometry={nodes.EN1050104_1.geometry} material={materials.Cherry} />
        <mesh name="EN1050104_2" geometry={nodes.EN1050104_2.geometry} material={materials['Concrete, Cast-in-Place gray.003']} />
        <mesh name="EN1050104_3" geometry={nodes.EN1050104_3.geometry} material={materials['Default Floor 02.003']} />
        <mesh name="EN1050104_4" geometry={nodes.EN1050104_4.geometry} material={materials['Concrete wall.003']} />
        <mesh name="EN1050104_5" geometry={nodes.EN1050104_5.geometry} material={materials['Default Wall.003']} />
      </Select>
      <Select name="EN1050105" enabled={hover === "EN1050105" || select === "EN1050105"} position={[-17.32, 1.883, 6.391]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1050105")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1050105")}
        <mesh name="EN1050105_1" geometry={nodes.EN1050105_1.geometry} material={materials['Concrete, Cast-in-Place gray.004']} />
        <mesh name="EN1050105_2" geometry={nodes.EN1050105_2.geometry} material={materials['Concrete wall.004']} />
        <mesh name="EN1050105_3" geometry={nodes.EN1050105_3.geometry} material={materials['Default Wall.004']} />
        <mesh name="EN1050105_4" geometry={nodes.EN1050105_4.geometry} material={materials['Interior Floors Tile 01']} />
        <mesh name="EN1050105_5" geometry={nodes.EN1050105_5.geometry} material={materials['Cherry.001']} />
      </Select>
      <Select name="EN1050106" enabled={hover === "EN1050106" || select === "EN1050106"} position={[17.933, 1.884, 6.385]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1050106")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1050106")}
        <mesh name="EN1050106_1" geometry={nodes.EN1050106_1.geometry} material={materials['Cherry.002']} />
        <mesh name="EN1050106_2" geometry={nodes.EN1050106_2.geometry} material={materials['Concrete, Cast-in-Place gray.005']} />
        <mesh name="EN1050106_3" geometry={nodes.EN1050106_3.geometry} material={materials['Concrete wall.005']} />
        <mesh name="EN1050106_4" geometry={nodes.EN1050106_4.geometry} material={materials['Default Wall.005']} />
        <mesh name="EN1050106_5" geometry={nodes.EN1050106_5.geometry} material={materials['Interior Floors Tile 01.001']} />
      </Select>
      <Select name="EN1050107" enabled={hover === "EN1050107" || select === "EN1050107"} position={[-12.67, 1.473, 11.827]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1050107")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1050107")}
        <mesh name="EN1050107_1" geometry={nodes.EN1050107_1.geometry} material={materials['Concrete, Cast-in-Place gray.006']} />
        <mesh name="EN1050107_2" geometry={nodes.EN1050107_2.geometry} material={materials['Concrete wall.006']} />
        <mesh name="EN1050107_3" geometry={nodes.EN1050107_3.geometry} material={materials['Default Wall.006']} />
        <mesh name="EN1050107_4" geometry={nodes.EN1050107_4.geometry} material={materials['Default Floor 02.004']} />
        <mesh name="EN1050107_5" geometry={nodes.EN1050107_5.geometry} material={materials['Wood.001']} />
        <mesh name="EN1050107_6" geometry={nodes.EN1050107_6.geometry} material={materials['Aluminum.002']} />
        <mesh name="EN1050107_7" geometry={nodes.EN1050107_7.geometry} material={materials['Glass.003']} />
      </Select>
      <Select name="EN1050108" enabled={hover === "EN1050108" || select === "EN1050108"} position={[-1.881, 1.388, 12.026]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1050108")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1050108")}
        <mesh name="EN1050108_1" geometry={nodes.EN1050108_1.geometry} material={materials['Default Wall.007']} />
        <mesh name="EN1050108_2" geometry={nodes.EN1050108_2.geometry} material={materials['Concrete, Cast-in-Place gray.007']} />
        <mesh name="EN1050108_3" geometry={nodes.EN1050108_3.geometry} material={materials['Default Floor 02.005']} />
        <mesh name="EN1050108_4" geometry={nodes.EN1050108_4.geometry} material={materials['Concrete wall.007']} />
        <mesh name="EN1050108_5" geometry={nodes.EN1050108_5.geometry} material={materials['Glass.004']} />
        <mesh name="EN1050108_6" geometry={nodes.EN1050108_6.geometry} material={materials['Wood.002']} />
        <mesh name="EN1050108_7" geometry={nodes.EN1050108_7.geometry} material={materials['Aluminum.003']} />
      </Select>
      <Select name="EN1050109" enabled={hover === "EN1050109" || select === "EN1050109"} position={[12.268, 1.462, 11.772]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1050109")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1050109")}
        <mesh name="EN1050109_1" geometry={nodes.EN1050109_1.geometry} material={materials['Glass.005']} />
        <mesh name="EN1050109_2" geometry={nodes.EN1050109_2.geometry} material={materials['Concrete, Cast-in-Place gray.008']} />
        <mesh name="EN1050109_3" geometry={nodes.EN1050109_3.geometry} material={materials['Concrete wall.008']} />
        <mesh name="EN1050109_4" geometry={nodes.EN1050109_4.geometry} material={materials['Default Wall.008']} />
        <mesh name="EN1050109_5" geometry={nodes.EN1050109_5.geometry} material={materials['Default Floor 02.006']} />
        <mesh name="EN1050109_6" geometry={nodes.EN1050109_6.geometry} material={materials['Aluminum.004']} />
        <mesh name="EN1050109_7" geometry={nodes.EN1050109_7.geometry} material={materials['Wood.003']} />
      </Select>
      <Select name="EN1050199" enabled={hover === "EN1050199" || select === "EN1050199"} position={[-0.099, 1.051, -1.206]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305}>
        {!isManage && !isRoomPage && renderModalDetail("EN1050199")}
        {!isManage && isRoomPage && renderModalRoomDetail("EN1050199")}
        <mesh name="EN1050199_1" geometry={nodes.EN1050199_1.geometry} material={materials['Cherry.003']} />
        <mesh name="EN1050199_2" geometry={nodes.EN1050199_2.geometry} material={materials['Concrete, Cast-in-Place gray.009']} />
        <mesh name="EN1050199_3" geometry={nodes.EN1050199_3.geometry} material={materials['Concrete wall.009']} />
        <mesh name="EN1050199_4" geometry={nodes.EN1050199_4.geometry} material={materials['Default Wall.009']} />
        <mesh name="EN1050199_5" geometry={nodes.EN1050199_5.geometry} material={materials['Default Floor 02.007']} />
        <mesh name="EN1050199_6" geometry={nodes.EN1050199_6.geometry} material={materials['Brick, Common']} />
        <mesh name="EN1050199_7" geometry={nodes.EN1050199_7.geometry} material={materials['Sliding Doors(1)']} />
        <mesh name="EN1050199_8" geometry={nodes.EN1050199_8.geometry} material={materials['Sliding Doors(2)']} />
        <mesh name="EN1050199_9" geometry={nodes.EN1050199_9.geometry} material={materials['Steel-01']} />
        <mesh name="EN1050199_10" geometry={nodes.EN1050199_10.geometry} material={materials['Aluminum.005']} />
        <mesh name="EN1050199_11" geometry={nodes.EN1050199_11.geometry} material={materials['Glass.006']} />
        <mesh name="EN1050199_12" geometry={nodes.EN1050199_12.geometry} material={materials['Wood.004']} />
        <mesh name="EN1050199_13" geometry={nodes.EN1050199_13.geometry} material={materials['Stainless steel Matt.001']} />
        <mesh name="EN1050199_14" geometry={nodes.EN1050199_14.geometry} material={materials['Aluminium.001']} />
      </Select>
      {/* <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[-88.353, 0.326, -109.097]} scale={[950, 1, 950]} /> */}
    </group>
  )
}

useGLTF.preload('/models/building/en105/en105-1.glb')
