/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/building/en104/en104.glb -t -k -E -R -f 
*/
"use client"

import * as THREE from 'three'
import React, { useCallback, useEffect, useState } from 'react'
import { Html, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Table, TableBody, TableCell, TableRow } from '@/components/shadcn-ui/table'
import { getData } from '@/actions/actions'
import { useEN104Store } from '@/stores/use-building-store'
import { IFloorDetails } from '@/types/model'
import { Select } from '@react-three/postprocessing'
import Link from 'next/link'
import { Button } from '@/components/shadcn-ui/button'
import { ExternalLink } from 'lucide-react'

type GLTFResult = GLTF & {
  nodes: {
    ['10x75']: THREE.Mesh
    ['10x75_1']: THREE.Mesh
    ['10x75_2']: THREE.Mesh
    ['10x75_3']: THREE.Mesh
    ['10x75_4']: THREE.Mesh
    ['10x75_5']: THREE.Mesh
    ['10x75_6']: THREE.Mesh
    ['10x75_7']: THREE.Mesh
    ['10x75_8']: THREE.Mesh
    ['10x75_9']: THREE.Mesh
    ['10x75_10']: THREE.Mesh
    ['10x75_11']: THREE.Mesh
    ['10x75_12']: THREE.Mesh
    ['10x75_13']: THREE.Mesh
    ['50x250']: THREE.Mesh
    ['50x250_1']: THREE.Mesh
    ['50x250_2']: THREE.Mesh
    ['50x250_3']: THREE.Mesh
    ['50x250_4']: THREE.Mesh
    ['50x250_5']: THREE.Mesh
    ['50x250_6']: THREE.Mesh
    ['50x25x25RHS231']: THREE.Mesh
    ['50x25x25RHS231_1']: THREE.Mesh
    ['50x25x25RHS231_2']: THREE.Mesh
    ['50x25x25RHS231_3']: THREE.Mesh
    ['50x25x25RHS231_4']: THREE.Mesh
    ['50x25x25RHS231_5']: THREE.Mesh
    ['50x25x25RHS231_6']: THREE.Mesh
    ['50x25x25RHS231_7']: THREE.Mesh
    ['50x25x25RHS231_8']: THREE.Mesh
    ['50x25x25RHS231_9']: THREE.Mesh
    ['50x25x25RHS231_10']: THREE.Mesh
    ['50x25x25RHS231_11']: THREE.Mesh
    ['50x25x25RHS231_12']: THREE.Mesh
    ['50x25x25RHS231_13']: THREE.Mesh
    ['50x25x25RHS231_14']: THREE.Mesh
    ['50x25x25RHS231_15']: THREE.Mesh
    ['50x25x25RHS231_16']: THREE.Mesh
  }
  materials: {
    ['Wisawa-ruamjai-Crimson-red']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.001']: THREE.MeshStandardMaterial
    ['Granite.001']: THREE.MeshStandardMaterial
    ['Glass-Gray01.001']: THREE.MeshStandardMaterial
    ['Metal Deck.001']: THREE.MeshStandardMaterial
    ['Wisawa-ruamjai-Front-coverway-white.001']: THREE.MeshStandardMaterial
    ['Default Wall.001']: THREE.MeshStandardMaterial
    ['Steel, 45-345.001']: THREE.MeshStandardMaterial
    ['Glass very light green.001']: THREE.MeshStandardMaterial
    ['Aluminium-silver.001']: THREE.MeshStandardMaterial
    ['Aluminium silver.001']: THREE.MeshStandardMaterial
    ['Gypsum Wall Board.001']: THREE.MeshStandardMaterial
    ['Clear Toughened Glass.001']: THREE.MeshStandardMaterial
    ['Die-cast aluminium - Powder Coated in Black.001']: THREE.MeshStandardMaterial
    ['Softwood, Lumber']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.002']: THREE.MeshStandardMaterial
    ['Wisawa-ruamjai-Crimson-red.001']: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['Wisawa-ruamjai-Front-coverway-white.002']: THREE.MeshStandardMaterial
    ['Default Wall.002']: THREE.MeshStandardMaterial
    ['Wisawa-ruamjai-Front-coverway-Crimson-red.001']: THREE.MeshStandardMaterial
    ['Steel, 45-345.002']: THREE.MeshStandardMaterial
    ['Concrete, Cast-in-Place gray.003']: THREE.MeshStandardMaterial
    ['Plastic, Opaque White.001']: THREE.MeshStandardMaterial
    ['Glass-Gray01.002']: THREE.MeshStandardMaterial
    ['Metal Deck.002']: THREE.MeshStandardMaterial
    ['Granite.002']: THREE.MeshStandardMaterial
    ['Wisawa-ruamjai-Front-coverway-white.003']: THREE.MeshStandardMaterial
    ['Default Wall.003']: THREE.MeshStandardMaterial
    ['Gypsum Wall Board.002']: THREE.MeshStandardMaterial
    ['Glass very light green.002']: THREE.MeshStandardMaterial
    ['Aluminium-silver.002']: THREE.MeshStandardMaterial
    ['Aluminium silver.002']: THREE.MeshStandardMaterial
    ['Steel, Paint Finish, Ivory, Matte.001']: THREE.MeshStandardMaterial
    ['Color RGB 212-204-191.001']: THREE.MeshStandardMaterial
    ['Color RGB 040-040-040.001']: THREE.MeshStandardMaterial
    ['Clear Toughened Glass.002']: THREE.MeshStandardMaterial
    ['Die-cast aluminium - Powder Coated in Black.002']: THREE.MeshStandardMaterial
  }
}

export const en104Floors = [
  "EN10401",
  "EN10402",
] as const;

export type EN104Floor = typeof en104Floors[number];

type Props = JSX.IntrinsicElements["group"] & {
  isManage: boolean;
};

export default function EN104Building(props: Props) {
  const { nodes, materials } = useGLTF('/models/building/en104/en104.glb') as GLTFResult
  const [hover, setHover] = useState<EN104Floor | null>(null);
  const { select, setSelect } = useEN104Store(state => (state));
  const [floorDetail, setFloorDetail] = useState<IFloorDetails | null>(null);

  const handleObjectHover = useCallback((object: EN104Floor | null) => {
    setHover(object);
  }, []);

  const handleObjectSelect = useCallback((object: EN104Floor) => {
    setSelect(object);
  }, [setSelect]);

  useEffect(() => {
    const fetchFloorDetail = async () => {
      const data = await getData(`buildingFloorDetail/${select?.toUpperCase()}`);
      setFloorDetail(data);
    }

    fetchFloorDetail();
  }, [select]);

  const renderModalDetail = (floorCode: string) => {
    if (select === floorCode && !props.isManage) {
      return (
        <Html distanceFactor={60}>
          <div className="pt-[10px] transform translate-x-[80%] bg-secondary text-left p-[10px_15px] rounded-md w-[320px] relative before:content-[''] before:absolute before:top-[25px] before:-left-10 before:h-[2px] before:w-[40px] before:bg-secondary">
            <div className="flex justify-between items-center">
              <label className="font-bold text-xl">
                {`ชั้น ${floorCode.substring(5, 7)} - ${floorCode}`}
              </label>
              <Link href={`/floor/${floorCode.toUpperCase()}`} target="_blank">
                <Button variant={"ghost"} size={"icon"}>
                  <ExternalLink className="size-5" />
                </Button>
              </Link>
            </div>
            {renderFloorDetail()}
          </div>
        </Html>
      )
    }
  }

  const renderFloorDetail = () => {
    if (floorDetail) {
      return (
        <Table className="border rounded-md">
          <TableBody>
            <TableRow>
              <TableCell className="p-2">Building Code</TableCell>
              <TableCell className="p-2">
                {floorDetail?.buildingCode || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Floor</TableCell>
              <TableCell className="p-2">
                {floorDetail?.floorNumber || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Meter Energy</TableCell>
              <TableCell className="p-2">
                {floorDetail?.floorMeter || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Meter Power</TableCell>
              <TableCell className="p-2">
                {floorDetail?.floorPower || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Average PM 2.5</TableCell>
              <TableCell className="p-2">
                {floorDetail?.averagefloorPM25 || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Average Temperature</TableCell>
              <TableCell className="p-2">
                {floorDetail?.averagefloorTemp || "-"}
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="p-2">Average Humidity</TableCell>
              <TableCell className="p-2">
                {floorDetail?.averagefloorHumidity || "-"}
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      )
    }
  }
  
  return (
    <group {...props} dispose={null} position={[0, 0.1 ,0]}>
      <group name="EN104RF" position={[0.358, 7.408, -1.367]} rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
        <mesh name="50x250" geometry={nodes['50x250'].geometry} material={materials['Softwood, Lumber']} />
        <mesh name="50x250_1" geometry={nodes['50x250_1'].geometry} material={materials['Concrete, Cast-in-Place gray.002']} />
        <mesh name="50x250_2" geometry={nodes['50x250_2'].geometry} material={materials['Wisawa-ruamjai-Crimson-red.001']} />
        <mesh name="50x250_3" geometry={nodes['50x250_3'].geometry} material={materials.Glass} />
        <mesh name="50x250_4" geometry={nodes['50x250_4'].geometry} material={materials['Wisawa-ruamjai-Front-coverway-white.002']} />
        <mesh name="50x250_5" geometry={nodes['50x250_5'].geometry} material={materials['Default Wall.002']} />
        <mesh name="50x250_6" geometry={nodes['50x250_6'].geometry} material={materials['Wisawa-ruamjai-Front-coverway-Crimson-red.001']} />
      </group>
      <Select
        name="EN10401"
        enabled={hover === "EN10401" || select === "EN10401"}
        onPointerOver={() => {
          handleObjectHover("EN10401");
        }}
        onPointerOut={() => {
          handleObjectHover(null);
        }}
        onClick={() => {
          handleObjectSelect("EN10401");
        }}
        position={[0.589, 1.991, -1.083]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.3}
      >
        {renderModalDetail("EN10401")}
        <mesh name="50x25x25RHS231" geometry={nodes['50x25x25RHS231'].geometry} material={materials['Steel, 45-345.002']} />
        <mesh name="50x25x25RHS231_1" geometry={nodes['50x25x25RHS231_1'].geometry} material={materials['Concrete, Cast-in-Place gray.003']} />
        <mesh name="50x25x25RHS231_2" geometry={nodes['50x25x25RHS231_2'].geometry} material={materials['Plastic, Opaque White.001']} />
        <mesh name="50x25x25RHS231_3" geometry={nodes['50x25x25RHS231_3'].geometry} material={materials['Glass-Gray01.002']} />
        <mesh name="50x25x25RHS231_4" geometry={nodes['50x25x25RHS231_4'].geometry} material={materials['Metal Deck.002']} />
        <mesh name="50x25x25RHS231_5" geometry={nodes['50x25x25RHS231_5'].geometry} material={materials['Granite.002']} />
        <mesh name="50x25x25RHS231_6" geometry={nodes['50x25x25RHS231_6'].geometry} material={materials['Wisawa-ruamjai-Front-coverway-white.003']} />
        <mesh name="50x25x25RHS231_7" geometry={nodes['50x25x25RHS231_7'].geometry} material={materials['Default Wall.003']} />
        <mesh name="50x25x25RHS231_8" geometry={nodes['50x25x25RHS231_8'].geometry} material={materials['Gypsum Wall Board.002']} />
        <mesh name="50x25x25RHS231_9" geometry={nodes['50x25x25RHS231_9'].geometry} material={materials['Glass very light green.002']} />
        <mesh name="50x25x25RHS231_10" geometry={nodes['50x25x25RHS231_10'].geometry} material={materials['Aluminium-silver.002']} />
        <mesh name="50x25x25RHS231_11" geometry={nodes['50x25x25RHS231_11'].geometry} material={materials['Aluminium silver.002']} />
        <mesh name="50x25x25RHS231_12" geometry={nodes['50x25x25RHS231_12'].geometry} material={materials['Steel, Paint Finish, Ivory, Matte.001']} />
        <mesh name="50x25x25RHS231_13" geometry={nodes['50x25x25RHS231_13'].geometry} material={materials['Color RGB 212-204-191.001']} />
        <mesh name="50x25x25RHS231_14" geometry={nodes['50x25x25RHS231_14'].geometry} material={materials['Color RGB 040-040-040.001']} />
        <mesh name="50x25x25RHS231_15" geometry={nodes['50x25x25RHS231_15'].geometry} material={materials['Clear Toughened Glass.002']} />
        <mesh name="50x25x25RHS231_16" geometry={nodes['50x25x25RHS231_16'].geometry} material={materials['Die-cast aluminium - Powder Coated in Black.002']} />
      </Select>
      <Select
        name="EN10402"
        enabled={hover === "EN10402" || select === "EN10402"}
        onPointerOver={() => {
          handleObjectHover("EN10402");
        }}
        onPointerOut={() => {
          handleObjectHover(null);
        }}
        onClick={() => {
          handleObjectSelect("EN10402");
        }}
        position={[0.96, 5.056, 0.803]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.3}
      >
        {renderModalDetail("EN10402")}
        <mesh name="10x75" geometry={nodes['10x75'].geometry} material={materials['Wisawa-ruamjai-Crimson-red']} />
        <mesh name="10x75_1" geometry={nodes['10x75_1'].geometry} material={materials['Concrete, Cast-in-Place gray.001']} />
        <mesh name="10x75_2" geometry={nodes['10x75_2'].geometry} material={materials['Granite.001']} />
        <mesh name="10x75_3" geometry={nodes['10x75_3'].geometry} material={materials['Glass-Gray01.001']} />
        <mesh name="10x75_4" geometry={nodes['10x75_4'].geometry} material={materials['Metal Deck.001']} />
        <mesh name="10x75_5" geometry={nodes['10x75_5'].geometry} material={materials['Wisawa-ruamjai-Front-coverway-white.001']} />
        <mesh name="10x75_6" geometry={nodes['10x75_6'].geometry} material={materials['Default Wall.001']} />
        <mesh name="10x75_7" geometry={nodes['10x75_7'].geometry} material={materials['Steel, 45-345.001']} />
        <mesh name="10x75_8" geometry={nodes['10x75_8'].geometry} material={materials['Glass very light green.001']} />
        <mesh name="10x75_9" geometry={nodes['10x75_9'].geometry} material={materials['Aluminium-silver.001']} />
        <mesh name="10x75_10" geometry={nodes['10x75_10'].geometry} material={materials['Aluminium silver.001']} />
        <mesh name="10x75_11" geometry={nodes['10x75_11'].geometry} material={materials['Gypsum Wall Board.001']} />
        <mesh name="10x75_12" geometry={nodes['10x75_12'].geometry} material={materials['Clear Toughened Glass.001']} />
        <mesh name="10x75_13" geometry={nodes['10x75_13'].geometry} material={materials['Die-cast aluminium - Powder Coated in Black.001']} />
      </Select>
    </group>
  )
}

useGLTF.preload('/models/building/en104/en104.glb')
